/*
 * ContractRateReportPanel.java
 *
 * Created on 2015/11/04
 */
package com.geobeck.sosia.pos.hair.report;

import java.awt.*;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;

import com.geobeck.sosia.pos.system.SystemInfo;
import com.geobeck.sosia.pos.report.bean.*;
import com.geobeck.sosia.pos.hair.report.logic.ReportLogic;
import com.geobeck.sosia.pos.hair.report.util.JExcelApi;
import com.geobeck.sql.*;
import com.geobeck.swing.*;
import com.geobeck.sosia.pos.master.company.*;
import com.geobeck.sosia.pos.master.customer.MstFirstComingMotive;
import com.geobeck.sosia.pos.util.*;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

/**
 *
 * @author lvtu
 */
public class ContractRateReportPanel extends com.geobeck.sosia.pos.swing.AbstractImagePanelEx {

    //declare variable
    
    /**
     * Creates new form ContractReportPanel
     */
    public ContractRateReportPanel() {
        initComponents();
        addMouseCursorChange();
        this.setSize(720, 500);
        this.setPath("分析帳票＞＞役務帳票");
        this.setTitle("契約率集計");
        this.setKeyListener();
        //LVTu start edit 2016/01/15 New request #46599
        cmbShop.addItem(SystemInfo.getGroup());
        //SystemInfo.initGroupShopComponents(cmbShop, 3);
        SystemInfo.getGroup().addGroupDataToJComboBox(cmbShop, 3);
        if (!SystemInfo.isGroup()) {
            cmbShop.setSelectedItem(SystemInfo.getCurrentShop());
        }
        //LVTu end edit 2016/01/15 New request #46599
        this.initStaff();
        this.loadFirstComingMotives();
        cmbTargetPeriodStart.setDate(SystemInfo.getCurrentShop().getSystemDate().getTime());
        cmbTargetPeriodEnd.setDate(SystemInfo.getCurrentShop().getSystemDate().getTime());
 
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportTypeGroup = new javax.swing.ButtonGroup();
        taxGroup = new javax.swing.ButtonGroup();
        staffGroup = new javax.swing.ButtonGroup();
        newVisitGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTargetPeriod = new javax.swing.JLabel();
        cmbTargetPeriodStart = new jp.co.flatsoft.fscomponent.FSCalenderCombo();
        jLabel1 = new javax.swing.JLabel();
        cmbTargetPeriodEnd = new jp.co.flatsoft.fscomponent.FSCalenderCombo();
        lblStaff = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        btnOutputExcel = new javax.swing.JButton();
        rdoTaxUnit = new javax.swing.JRadioButton();
        rdoTaxBlank = new javax.swing.JRadioButton();
        lblOutput = new javax.swing.JLabel();
        rdoNewContract = new javax.swing.JRadioButton();
        rdoReturnRate = new javax.swing.JRadioButton();
        cmbstaff = new javax.swing.JComboBox();
        rdoContractRate = new javax.swing.JRadioButton();
        lblShop = new javax.swing.JLabel();
        cmbFirstVisit = new javax.swing.JComboBox();
        lblFirstVisit = new javax.swing.JLabel();
        cmbShop = new com.geobeck.sosia.pos.swing.JComboBoxLabel();

        setFocusCycleRoot(true);

        jPanel1.setOpaque(false);

        lblTargetPeriod.setText("集計期間");

        cmbTargetPeriodStart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cmbTargetPeriodStart.setForeground(java.awt.Color.white);
        cmbTargetPeriodStart.setMaximumSize(new java.awt.Dimension(65, 20));
        cmbTargetPeriodStart.setMinimumSize(new java.awt.Dimension(65, 20));
        cmbTargetPeriodStart.setPreferredSize(new java.awt.Dimension(85, 20));
        cmbTargetPeriodStart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbTargetPeriodStartFocusGained(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("～");

        cmbTargetPeriodEnd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cmbTargetPeriodEnd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbTargetPeriodEndFocusGained(evt);
            }
        });

        lblStaff.setText("担当者");

        lblTax.setText("税区分");

        btnOutputExcel.setIcon(SystemInfo.getImageIcon("/button/print/excel_off.jpg"));
        btnOutputExcel.setBorderPainted(false);
        btnOutputExcel.setContentAreaFilled(false);
        btnOutputExcel.setFocusCycleRoot(true);
        btnOutputExcel.setPressedIcon(SystemInfo.getImageIcon("/button/print/excel_on.jpg"));
        btnOutputExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutputExcelActionPerformed(evt);
            }
        });

        taxGroup.add(rdoTaxUnit);
        rdoTaxUnit.setSelected(true);
        rdoTaxUnit.setText("税込");
        rdoTaxUnit.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoTaxUnit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rdoTaxUnit.setOpaque(false);

        taxGroup.add(rdoTaxBlank);
        rdoTaxBlank.setText("税抜");
        rdoTaxBlank.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoTaxBlank.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rdoTaxBlank.setOpaque(false);

        lblOutput.setText("出力帳票");

        staffGroup.add(rdoNewContract);
        rdoNewContract.setSelected(true);
        rdoNewContract.setText("新規契約客リスト");
        rdoNewContract.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoNewContract.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rdoNewContract.setOpaque(false);

        staffGroup.add(rdoReturnRate);
        rdoReturnRate.setText("リターン率集計");
        rdoReturnRate.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoReturnRate.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rdoReturnRate.setOpaque(false);

        cmbstaff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        staffGroup.add(rdoContractRate);
        rdoContractRate.setText("レスポンス別契約率");
        rdoContractRate.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoContractRate.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rdoContractRate.setOpaque(false);
        rdoContractRate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdoContractRateStateChanged(evt);
            }
        });

        lblShop.setText("対象店舗");

        cmbFirstVisit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblFirstVisit.setText("初回来店動機");

        cmbShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbShopActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblOutput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, lblShop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, lblTargetPeriod, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, lblTax, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, lblStaff, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, lblFirstVisit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(rdoNewContract, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rdoContractRate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rdoReturnRate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(cmbTargetPeriodStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(0, 0, 0)
                                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(0, 0, 0)
                                        .add(cmbTargetPeriodEnd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(cmbShop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 198, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(btnOutputExcel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cmbFirstVisit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 198, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(rdoTaxUnit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(5, 5, 5)
                                .add(rdoTaxBlank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cmbstaff, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblOutput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(rdoNewContract, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(rdoContractRate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(rdoReturnRate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(5, 5, 5)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(lblShop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cmbShop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(btnOutputExcel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(5, 5, 5)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblTargetPeriod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cmbTargetPeriodStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cmbTargetPeriodEnd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblStaff, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cmbstaff, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblFirstVisit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cmbFirstVisit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblTax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rdoTaxUnit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rdoTaxBlank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnOutputExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutputExcelActionPerformed

        btnOutputExcel.setCursor(null);

        try {

            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            ReportParameterBean paramBean = new ReportParameterBean();

            // 税区分(税抜き)
            if (this.rdoTaxBlank.isSelected()) {
                paramBean.setTaxType(ReportParameterBean.TAX_TYPE_BLANK);
            } // 税区分(税込み)
            else if (this.rdoTaxUnit.isSelected()) {
                paramBean.setTaxType(ReportParameterBean.TAX_TYPE_UNIT);
            }

            if (this.rdoNewContract.isSelected()) {
                paramBean.setStaffType(ReportParameterBean.STAFF_TYPE_MAIN);
            } else {
                paramBean.setStaffType(ReportParameterBean.STAFF_TYPE_TECH);
            }

            boolean logicResult = true;
            try {

                //グループ
                if (cmbShop.getSelectedItem() instanceof MstGroup) {
                    MstGroup mg = (MstGroup) cmbShop.getSelectedItem();
                    paramBean.setTargetName(mg.getGroupName());
                    paramBean.setShopIDList(mg.getShopIDListAll());
                } //店舗
                else if (cmbShop.getSelectedItem() instanceof MstShop) {
                    MstShop ms = (MstShop) cmbShop.getSelectedItem();
                    paramBean.setTargetName(ms.getShopName());
                    paramBean.setShopIDList(ms.getShopID().toString());
                }

                //対象となる店舗が存在しない場合
                if (paramBean.getShopIDList().equals("")) {
                    MessageDialog.showMessageDialog(this,
                            MessageUtil.getMessage(4001),
                            this.getTitle(),
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (0 < cmbstaff.getSelectedIndex()) {
                    MstStaff ms = (MstStaff) cmbstaff.getSelectedItem();
                    paramBean.setStaffId(ms.getStaffID());
                    paramBean.setStaffName(ms.getFullStaffName());
                }

                if (this.cmbTargetPeriodStart.getDate() == null
                        || this.cmbTargetPeriodEnd.getDate() == null) {
                    MessageDialog.showMessageDialog(this,
                            MessageUtil.getMessage(MessageUtil.ERROR_INPUT_WRONG, "対象期間"),
                            this.getTitle(),
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
                Calendar start = Calendar.getInstance();
                Calendar end = Calendar.getInstance();

                start.setTime(this.cmbTargetPeriodStart.getDate());
                end.setTime(this.cmbTargetPeriodEnd.getDate());
                if (start.compareTo(end) != 0) {
                    if (start.after(end)) {
                        MessageDialog.showMessageDialog(this,
                                MessageUtil.getMessage(MessageUtil.ERROR_INPUT_WRONG, "対象期間"),
                                this.getTitle(),
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }

                paramBean.setTargetStartDate(this.cmbTargetPeriodStart.getDateStr());
                paramBean.setTargetEndDate(this.cmbTargetPeriodEnd.getDateStr());

                Calendar cal = Calendar.getInstance();
                cal.setTime(cmbTargetPeriodStart.getDate());
                cal.set(Calendar.HOUR_OF_DAY, 0);
                cal.set(Calendar.MINUTE, 0);
                cal.set(Calendar.SECOND, 0);
                paramBean.setTargetStartDateObj(cal.getTime());

                cal.setTime(cmbTargetPeriodEnd.getDate());
                cal.set(Calendar.HOUR_OF_DAY, 23);
                cal.set(Calendar.MINUTE, 59);
                cal.set(Calendar.SECOND, 59);
                paramBean.setTargetEndDateObj(cal.getTime());
               
                if (this.rdoNewContract.isSelected()) {
                    logicResult = getNewContractCustomer(paramBean);
                } //レスポンス別契約率
                else if (this.rdoContractRate.isSelected()) {
                    logicResult = getContractRateCustomer(paramBean);

                } //リターン率集計
                else if (this.rdoReturnRate.isSelected()) {
                    logicResult = getContractRateReturnCustomer(paramBean);
                } 
                
                
            } catch (Exception e) {
                SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
                MessageDialog.showMessageDialog(this,
                        MessageUtil.getMessage(1099),
                        this.getTitle(),
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // エラー時
            if (!logicResult) {
                MessageDialog.showMessageDialog(this,
                        MessageUtil.getMessage(4001),
                        this.getTitle(),
                        JOptionPane.ERROR_MESSAGE);
            }

        } finally {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }

    }//GEN-LAST:event_btnOutputExcelActionPerformed

    private void cmbTargetPeriodEndFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbTargetPeriodEndFocusGained
        cmbTargetPeriodEnd.getInputContext().setCharacterSubsets(null);
    }//GEN-LAST:event_cmbTargetPeriodEndFocusGained

    private void cmbTargetPeriodStartFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbTargetPeriodStartFocusGained
        cmbTargetPeriodStart.getInputContext().setCharacterSubsets(null);
    }//GEN-LAST:event_cmbTargetPeriodStartFocusGained

    private void cmbShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShopActionPerformed
        
    }//GEN-LAST:event_cmbShopActionPerformed

    private void rdoContractRateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdoContractRateStateChanged
         changeRadioButton();
    }//GEN-LAST:event_rdoContractRateStateChanged

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOutputExcel;
    private javax.swing.JComboBox cmbFirstVisit;
    private com.geobeck.sosia.pos.swing.JComboBoxLabel cmbShop;
    private jp.co.flatsoft.fscomponent.FSCalenderCombo cmbTargetPeriodEnd;
    private jp.co.flatsoft.fscomponent.FSCalenderCombo cmbTargetPeriodStart;
    private javax.swing.JComboBox cmbstaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFirstVisit;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblShop;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblTargetPeriod;
    private javax.swing.JLabel lblTax;
    private javax.swing.ButtonGroup newVisitGroup;
    private javax.swing.JRadioButton rdoContractRate;
    private javax.swing.JRadioButton rdoNewContract;
    private javax.swing.JRadioButton rdoReturnRate;
    private javax.swing.JRadioButton rdoTaxBlank;
    private javax.swing.JRadioButton rdoTaxUnit;
    private javax.swing.ButtonGroup reportTypeGroup;
    private javax.swing.ButtonGroup staffGroup;
    private javax.swing.ButtonGroup taxGroup;
    // End of variables declaration//GEN-END:variables
    private ContractRateReportPanelFocusTraversalPolicy ftp =
            new ContractRateReportPanelFocusTraversalPolicy();

    /**
     * ボタンにマウスカーソルが乗ったときにカーソルを変更するイベントを追加する。
     */
    private void addMouseCursorChange() {
        SystemInfo.addMouseCursorChange(btnOutputExcel);
    }

    private void setKeyListener() {
        cmbTargetPeriodEnd.addKeyListener(SystemInfo.getMoveNextField());
        cmbTargetPeriodEnd.addFocusListener(SystemInfo.getSelectText());
        cmbTargetPeriodStart.addKeyListener(SystemInfo.getMoveNextField());
        cmbTargetPeriodStart.addFocusListener(SystemInfo.getSelectText());
        rdoTaxBlank.addKeyListener(SystemInfo.getMoveNextField());
        rdoTaxUnit.addKeyListener(SystemInfo.getMoveNextField());
        cmbstaff.addKeyListener(SystemInfo.getMoveNextField());
    }

    /**
     * レジ担当者を初期化する。
     */
    private void initStaff() {
        cmbstaff.addItem(new MstStaff());
        SystemInfo.initStaffComponent(cmbstaff);
        cmbstaff.setSelectedIndex(0);
    }
    
    /**
     * レスポンス別契約率の場合は非活性。それ以外は活性化
     */
    private void changeRadioButton() {
        if ( rdoContractRate.isSelected()) {
            cmbFirstVisit.setSelectedIndex(0);
            cmbFirstVisit.setEnabled(false);
        }else {
             cmbFirstVisit.setEnabled(true);
        }
    }
    
    /**
     * 初回来店動機
     *
     * @return void
     */
    private void loadFirstComingMotives() {

        cmbFirstVisit.addItem(new MstFirstComingMotive());
        ConnectionWrapper con = SystemInfo.getConnection();

        try {
            ResultSetWrapper rs = con.executeQuery(MstFirstComingMotive.getSelectAllSQL());

            while (rs.next()) {
                MstFirstComingMotive mfcm = new MstFirstComingMotive();

                mfcm.setData(rs);

                cmbFirstVisit.addItem(mfcm);
            }
        } catch (SQLException e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        }
        cmbFirstVisit.setSelectedIndex(0);
    }
    //IVS_LVTu start edit 2016/02/17 New request #48268
    private String getNewCustomerNum(ReportParameterBean paramBean , Integer firstComingMotives) {
        StringBuilder sql = new StringBuilder();
        
        sql.append("  select count(distinct ds.customer_id) as new_customer  \n");
        sql.append("  from view_data_sales_detail_valid ds  \n");
        sql.append("  inner join mst_customer mc on ds.customer_id = mc.customer_id  \n");
        sql.append("  where mc.customer_no <>'0'   \n");
        sql.append("  and ds.shop_id  in (" + paramBean.getShopIDList() + ")\n");
        if ( paramBean.getStaffId() != null) {
            sql.append("  and ds.detail_staff_id = " + paramBean.getStaffId() +"  \n");
        }
        if (firstComingMotives != null ) {
            sql.append("  and mc.first_coming_motive_class_id = " + firstComingMotives +"  \n");
        }
        //sql.append("  and mc.before_visit_num + get_visit_count(mc.customer_id,ds.sales_date) = 1  \n");
        sql.append("  and ((mc.before_visit_num + get_visit_count(mc.customer_id,ds.sales_date) = 1 )   \n");

        sql.append("        )  \n");
        sql.append("  and ds.sales_date between  '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        
        return sql.toString();
    }
    private boolean getNewContractCustomer(ReportParameterBean paramBean) {
        Integer firstComingMotives = null;
        String firstComingMotiveName = "";
        if ( cmbFirstVisit.isEnabled() == true ) {
            if (0 < cmbFirstVisit.getSelectedIndex()) {
                firstComingMotives = ((MstFirstComingMotive)cmbFirstVisit.getSelectedItem()).getFirstComingMotiveClassId();
                firstComingMotiveName = ((MstFirstComingMotive)cmbFirstVisit.getSelectedItem()).getFirstComingMotiveName();
            }
        }
        StringBuilder sql = new StringBuilder();
          
        sql.append("  SELECT t.*,  \n");
        sql.append("  	   array_to_string(array  \n");
        sql.append("  						 (SELECT CASE WHEN (t.detail_staff_id IS NULL  \n");
        sql.append("  						AND dsd1.staff_id IS NULL)  \n");
        sql.append("  						  OR (t.detail_staff_id IS NOT NULL  \n");
        sql.append("  							  AND dsd1.staff_id = t.detail_staff_id) THEN mc.course_name ELSE '' END   \n");
        sql.append("  						  FROM data_sales ds1  \n");
        sql.append("  						  INNER JOIN data_sales_detail dsd1 ON ds1.slip_no = dsd1.slip_no  \n");
        sql.append("  						  AND ds1.shop_id = dsd1.shop_id  \n");
        sql.append("  						  INNER JOIN mst_course mc ON dsd1.product_id = mc.course_id  \n");
        sql.append("  						  inner join data_contract dc1 on dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is null  \n");
        sql.append("  						  WHERE ds1.customer_id = t.customer_id  \n");
        sql.append("  							AND ds1.shop_id = t.shop_id  \n");
        sql.append("  							AND product_division = 5  \n");
        sql.append("  							AND ds1.sales_date = t.sales_date  \n");
        sql.append("  							AND ds1.insert_date = t.insert_date   \n");
        sql.append("                                                    and ds1.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
	sql.append("                                                    and ds1.delete_date is null   \n");
	sql.append("                                                    and dsd1.delete_date is null   \n");
        sql.append("   ), ', ') AS course_name,  \n");
        sql.append("    (SELECT coalesce(sum(CASE WHEN (t.detail_staff_id IS NULL  \n");
        sql.append("  			 AND detail_staff_id IS NULL)  \n");
        sql.append("  			OR (t.detail_staff_id IS NOT NULL  \n");
        sql.append("  			 AND detail_staff_id = t.detail_staff_id) THEN  \n");
        if ( paramBean.getTaxType() == paramBean.TAX_TYPE_UNIT) {
            sql.append("  			discount_detail_value_in_tax  \n");
        }else {
            sql.append("  			discount_detail_value_no_tax  \n");
        }
        sql.append("  			ELSE 0 END),0)   \n");
        sql.append("     FROM data_sales ds1  \n");
        sql.append("     INNER JOIN view_data_sales_detail_valid dsd1 ON ds1.shop_id = dsd1.shop_id  \n");
        sql.append("     AND ds1.slip_no = dsd1.slip_no  \n");
        sql.append("     and dsd1.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        sql.append("     inner join data_sales_detail dsd2 on dsd2.shop_id = ds1.shop_id and dsd2.slip_no = ds1.slip_no and dsd1.slip_detail_no = dsd2.slip_detail_no \n");
        sql.append("     WHERE ds1.customer_id =t.customer_id  \n");
        sql.append("  	 AND ds1.shop_id = t.shop_id  \n");
        sql.append("  	 AND dsd1.product_division = 5  \n");
        sql.append("  	 AND ds1.sales_date = t.sales_date  \n");
        sql.append("  	 AND ds1.insert_date = t.insert_date   \n");
        sql.append("  	 and not exists (select 1 from  data_contract dc1 where dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is not null  \n");
	sql.append("  	 and dc1.product_id = dsd1.product_id and dsd2.contract_detail_no = dc1.contract_detail_no )  \n");
        sql.append("   ) AS price_value  \n");
        sql.append("  FROM  \n");
        sql.append("    (SELECT vds.shop_id,  \n");
        sql.append("  		  shop.shop_name,  \n");
        sql.append("  		  vds.customer_id,  \n");
        sql.append("  		  mc.customer_no,  \n");
        sql.append("  		  mc.customer_name1,  \n");
        sql.append("  		  mc.customer_name2,  \n");
        sql.append("  		  vds.detail_staff_id,  \n");
        sql.append("  		  staff.staff_name1,  \n");
        sql.append("  		  staff.staff_name2,  \n");
        sql.append("  		  vds.sales_date,  \n");
        sql.append("  	 (SELECT min(ds.insert_date)  \n");
        sql.append("  	  FROM data_sales ds  \n");
        sql.append("  	  INNER JOIN data_sales_detail dsd ON ds.slip_no = dsd.slip_no  \n");
        sql.append("  	  AND ds.shop_id = dsd.shop_id  \n");
        sql.append("  	  inner join data_contract dc1 on dc1.shop_id = ds.shop_id and dc1.slip_no = ds.slip_no and dc1.delete_date is null \n");
        sql.append("  	  WHERE ds.customer_id = vds.customer_id  \n");
        sql.append("  		AND ds.shop_id = vds.shop_id  \n");
        sql.append("            and ds.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
	sql.append("            and ds.delete_date is null   \n");
	sql.append("            and dsd.delete_date is null   \n");
        //Luc start add 20160112 #46345
        sql.append("            and dsd.product_value <>0  \n");
	//Luc end  add 20160112 #46345
        sql.append("  		AND dsd.product_division = 5 ) AS insert_date   \n");
        sql.append("     FROM view_data_sales_detail_valid vds  \n");
        sql.append("     INNER JOIN mst_shop shop ON shop.shop_id = vds.shop_id  \n");
        sql.append("     INNER JOIN mst_customer mc ON mc.customer_id = vds.customer_id  \n");
        sql.append("     LEFT JOIN mst_staff staff ON staff.staff_id = vds.detail_staff_id  \n");
        sql.append("     inner join data_contract dc on dc.shop_id = vds.shop_id and dc.slip_no = vds.slip_no and dc.delete_date is null \n");
        sql.append("     WHERE vds.product_division = 5  \n");
        sql.append("  	 AND shop.shop_id IN (" + paramBean.getShopIDList() + ")\n");
        if ( paramBean.getStaffId() != null) {
            sql.append("  AND staff.staff_id = " + paramBean.getStaffId() +"  \n");
        }
        if (firstComingMotives != null ) {
            sql.append("  AND mc.first_coming_motive_class_id = " + firstComingMotives +"  \n");
        }
        sql.append("  	 AND vds.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        sql.append("  	 AND NOT EXISTS  \n");
        sql.append("  	   (SELECT 1  \n");
        sql.append("  		FROM view_data_sales_detail_valid vds1  \n");
        sql.append("  		inner join data_contract dc1 on dc1.shop_id = vds1.shop_id and dc1.slip_no = vds1.slip_no and dc1.delete_date is null \n");
        sql.append("  		WHERE vds1.product_division = 5  \n");
        sql.append("  		  AND vds1.customer_id  = vds.customer_id  \n");
        //sql.append("  		  AND vds1.shop_id IN (" + paramBean.getShopIDList() + ")\n");
        //sql.append("  		  AND vds1.sales_date < '" + paramBean.getTargetStartDate() + "' )  \n");
        sql.append("    AND vds1.sales_date < vds.sales_date )\n");
        sql.append("  	 AND vds.sales_date =  \n");
        sql.append("  	   (SELECT min(sales_date)  \n");
        sql.append("  		FROM view_data_sales_detail_valid vds2  \n");
        sql.append("  		inner join data_contract dc1 on dc1.shop_id = vds2.shop_id and dc1.slip_no = vds2.slip_no and dc1.delete_date is null \n");
        sql.append("  		WHERE vds2.product_division = 5  \n");
        sql.append("  		  AND vds2.shop_id IN (" + paramBean.getShopIDList() + ")\n");
        sql.append("  		  AND vds2.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        //Luc start add 20160112 #46345
        sql.append("  		  And vds2.product_value <> 0 ");
        //Luc end add 20160112 #46345
        sql.append("  		  AND vds2.customer_id = mc.customer_id)  \n");
        sql.append("  	 AND mc.customer_no <> '0'   \n");
        sql.append("  	 AND EXISTS  \n");
        sql.append("  	   (SELECT 1  \n");
        sql.append("  		FROM data_sales ds1  \n");
        sql.append("  		inner join data_contract dc1 on dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is null \n");
        sql.append("  		WHERE ds1.slip_no = vds.slip_no  \n");
        sql.append("  		  AND ds1.shop_id = vds.shop_id  \n");
        sql.append("              and ds1.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
	sql.append("              and ds1.delete_date is null   \n");
        sql.append("  		  AND ds1.insert_date =  \n");
        sql.append("  			(SELECT min(ds.insert_date)  \n");
        sql.append("  			 FROM data_sales ds  \n");
        sql.append("  			 INNER JOIN data_sales_detail dsd ON ds.slip_no = dsd.slip_no  \n");
        sql.append("  			 AND ds.shop_id = dsd.shop_id  \n");
        sql.append("  			 inner join data_contract dc1 on dc1.shop_id = ds.shop_id and dc1.slip_no = ds.slip_no and dc1.delete_date is null \n");
        sql.append("  			 WHERE ds.customer_id = vds.customer_id  \n");
        sql.append("  			   AND ds.shop_id = vds.shop_id  \n");
        sql.append("  			   AND dsd.product_division = 5  \n");
        sql.append("  			   And  dsd.product_value <> 0  \n");
        sql.append("  			   AND ds.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "')) \n");
        
        sql.append("     GROUP BY vds.shop_id,  \n");
        sql.append("  			vds.customer_id,  \n");
        sql.append("  			shop.shop_name,  \n");
        sql.append("  			vds.customer_id,  \n");
        sql.append("  			mc.customer_no,  \n");
        sql.append("  			mc.customer_name1,  \n");
        sql.append("  			vds.sales_date,  \n");
        sql.append("  			mc.customer_name2,  \n");
        sql.append("  			vds.detail_staff_id,  \n");
        sql.append("  			staff.staff_name1,  \n");
        sql.append("  			staff.staff_name2)t  \n");
        //Luc start add 20160111 #46345
        sql.append("  	where ");
        sql.append("    (SELECT coalesce(sum(CASE WHEN (t.detail_staff_id IS NULL  \n");
        sql.append("  			 AND detail_staff_id IS NULL)  \n");
        sql.append("  			OR (t.detail_staff_id IS NOT NULL  \n");
        sql.append("  			 AND detail_staff_id = t.detail_staff_id) THEN  \n");
        if ( paramBean.getTaxType() == paramBean.TAX_TYPE_UNIT) {
            sql.append("  			discount_detail_value_in_tax  \n");
        }else {
            sql.append("  			discount_detail_value_no_tax  \n");
        }
        sql.append("  			ELSE 0 END),0)   \n");
        sql.append("     FROM data_sales ds1  \n");
        sql.append("     INNER JOIN view_data_sales_detail_valid dsd1 ON ds1.shop_id = dsd1.shop_id  \n");
        sql.append("     AND ds1.slip_no = dsd1.slip_no  \n");
        sql.append("     and dsd1.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        sql.append("     inner join data_sales_detail dsd2 on dsd2.shop_id = ds1.shop_id and dsd2.slip_no = ds1.slip_no and dsd1.slip_detail_no = dsd2.slip_detail_no \n");
        sql.append("     WHERE ds1.customer_id =t.customer_id  \n");
        sql.append("  	 AND ds1.shop_id = t.shop_id  \n");
        sql.append("  	 AND dsd1.product_division = 5  \n");
        sql.append("  	 AND ds1.sales_date = t.sales_date  \n");
        sql.append("  	 AND ds1.insert_date = t.insert_date   \n");
        sql.append("  	 and not exists (select 1 from  data_contract dc1 where dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is not null  \n");
	sql.append("  	 and dc1.product_id = dsd1.product_id and dsd2.contract_detail_no = dc1.contract_detail_no )  \n");
        sql.append("   ) <> 0 \n");
        //Luc end add 20160111  #46345
        sql.append("  ORDER BY t.sales_date  \n");
                
        SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
        ConnectionWrapper cw = SystemInfo.getConnection();
        ResultSetWrapper rs = new ResultSetWrapper();
        
        try {
            //新規来店客数（人）
            Integer newCustomerNum = 0;
            rs = cw.executeQuery(getNewCustomerNum(paramBean, firstComingMotives));
            if (rs.next()) {
                newCustomerNum = rs.getInt("new_customer");
            }
            rs.close();
            
            rs = cw.executeQuery(sql.toString());
            if (!rs.next()) {
                return false;
            }

            JExcelApi jx = new JExcelApi("新規契約客リスト");
            jx.setTemplateFile("/reports/新規契約客リスト.xls");
            jx.setValue(2, 3, paramBean.getTargetName());
            jx.setValue(2, 4, format.format(paramBean.getTargetStartDateObj()) + " ～ " + format.format(paramBean.getTargetEndDateObj()));
            jx.setValue(2, 5, paramBean.getStaffName());
            jx.setValue(2, 6, firstComingMotiveName);
            if (paramBean.getTaxType() == ReportParameterBean.TAX_TYPE_BLANK) {
                jx.setValue(2, 7, "税抜");
            }else {
                jx.setValue(2, 7, "税込");
            }
            //新規来店客数（人）
            jx.setValue(1, 10, newCustomerNum);

            if (newCustomerNum <= 0) {
                //新規客契約率（%）
                //契約人数÷新規来店数が1/0のような場合は100%とする
                jx.setValue(5, 10, 1);
            }

            int row = 13;
            rs.last();
            int num = 0;
            num = rs.getRow();

            //契約客数（人）
            HashMap<Integer, String> customerMap = new HashMap<Integer, String>();
            rs.beforeFirst();
            while (rs.next()) {
                if (!customerMap.containsKey(rs.getInt("customer_id"))) {
                    customerMap.put(rs.getInt("customer_id"), rs.getString("customer_no"));
                }
            }
            jx.setValue(3, 10, customerMap.size());
            // if 契約客数（人）= 0 then 契約客単価（円）
            if ( num <= 0 ) {
                jx.setValue(7, 10, num);
            }

            if(num > 2) {
                jx.insertRow(row, num - 2);
            }

            rs.beforeFirst();
             while (rs.next()) {
                 //mergecell
                 jx.mergeCells(6, row, 9, row);
                // add data
                String staffFullName = "";
                String courseName    = "";
                String[] arrCourse ;
                courseName = rs.getString("course_name");
                arrCourse = courseName.split(", ");
                courseName = "";
                for (int i = 0;i < arrCourse.length;i ++ ) {
                    //arrCourse[i] == "" then i ++
                    if ( arrCourse[i].equals("")) {
                        continue;
                    }
                    courseName += arrCourse[i];
                    // set , 
                    if ( (i + 1) < arrCourse.length ) {
                        courseName +=", ";
                    }
                }
                staffFullName =  rs.getString("staff_name1")!= null ? rs.getString("staff_name1") + " ": "";
                staffFullName +=  rs.getString("staff_name2")!= null ? rs.getString("staff_name2"): "";

                jx.setValue(1, row, rs.getString("shop_name"));
                jx.setValue(2, row, format.format(rs.getDate("sales_date")));
                jx.setValue(3, row, rs.getString("customer_no"));
                jx.setValue(4, row, rs.getString("customer_name1") + " " + rs.getString("customer_name2") );
                jx.setValue(5, row, staffFullName);
                jx.setValue(6, row, courseName);
                jx.setValue(10, row, rs.getLong("price_value"));

                row ++ ;
             }
            if(num < 2) {
                jx.removeRow(row);
            }
            jx.openWorkbook();
        } catch (Exception e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(1099),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    
    private boolean getContractRateCustomer(ReportParameterBean paramBean) {

        StringBuilder sql = new StringBuilder();
        
        sql.append("  select * from (  \n");
        sql.append("  select cm.first_coming_motive_class_id,cm.first_coming_motive_name,  \n");
        sql.append("  coalesce((select count(distinct ds1.customer_id) from view_data_sales_detail_valid ds1  \n");
        sql.append("  inner join mst_customer mc1 on ds1.customer_id = mc1.customer_id  \n");
        sql.append("  where mc1.customer_no <>'0'   \n");
        sql.append("  and ds1.shop_id in (" + paramBean.getShopIDList() + ")\n");
        //sql.append("  and mc1.before_visit_num + get_visit_count(mc1.customer_id,ds1.sales_date) = 1  \n");
        sql.append("  and ((mc1.before_visit_num + get_visit_count(mc1.customer_id,ds1.sales_date) = 1 )   \n");
        sql.append("      )  \n");
        sql.append("  and ds1.sales_date between  '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        sql.append("  and mc1.first_coming_motive_class_id = cm.first_coming_motive_class_id  \n");
        if ( paramBean.getStaffId() != null) {
            sql.append("  and ds1.detail_staff_id = " + paramBean.getStaffId() +"  \n");
        }
        sql.append("  ),0) as new_customer,  \n");
        sql.append("  coalesce((select count(distinct ds1.customer_id) from view_data_sales_detail_valid ds1  \n");
        sql.append("  inner join mst_customer mc1 on ds1.customer_id = mc1.customer_id  \n");
        sql.append("  inner join data_contract dc1 on dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is null  \n");
        sql.append("  where mc1.customer_no <>'0'   \n");
        sql.append("  and ds1.shop_id in (" + paramBean.getShopIDList() + ")\n");
        sql.append("  and ds1.product_division = 5  \n");
        sql.append("  and ds1.sales_date between  '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        sql.append("  and mc1.first_coming_motive_class_id = cm.first_coming_motive_class_id  \n");
        if ( paramBean.getStaffId() != null) {
            sql.append("  and ds1.detail_staff_id = " + paramBean.getStaffId() +"  \n");
        }
        sql.append("  and NOT EXISTS  \n");
        sql.append("  (SELECT 1  \n");
        sql.append("  FROM view_data_sales_detail_valid vds1  \n");
        sql.append("  inner join data_contract dc1 on dc1.shop_id = vds1.shop_id and dc1.slip_no = vds1.slip_no and dc1.delete_date is null  \n");
        sql.append("  WHERE vds1.product_division = 5  \n");
        sql.append("    and vds1.customer_id = mc1.customer_id  \n");
        //sql.append("    AND vds1.shop_id in (" + paramBean.getShopIDList() + ")\n");
        //sql.append("    AND vds1.sales_date < '" + paramBean.getTargetStartDate() + "' )  \n");
        sql.append("    AND vds1.sales_date < ds1.sales_date )\n");
        sql.append("  ),0) as contracted_customer,  \n");
        sql.append("  coalesce((select sum  \n");
        if ( paramBean.getTaxType() == paramBean.TAX_TYPE_UNIT) {
            sql.append("  (discount_detail_value_in_tax)  \n");
        }else {
            sql.append("  (discount_detail_value_no_tax)  \n");
        }
        sql.append("  from view_data_sales_detail_valid ds1  \n");
        sql.append("  inner join mst_customer mc1 on ds1.customer_id = mc1.customer_id  \n");
        sql.append("  inner join data_sales_detail dsd2 on dsd2.shop_id = ds1.shop_id and dsd2.slip_no = ds1.slip_no and ds1.slip_detail_no = dsd2.slip_detail_no \n");
        sql.append("  where mc1.customer_no <>'0'   \n");
        sql.append("  and ds1.shop_id in (" + paramBean.getShopIDList() + ")\n");
        sql.append("  and ds1.product_division = 5  \n");
        sql.append("  and not exists (select 1 from  data_contract dc1 where dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is not null\n");
	sql.append("  and dc1.product_id = ds1.product_id and dsd2.contract_detail_no = dc1.contract_detail_no	)\n");
        sql.append("  and ds1.sales_date between  '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        sql.append("  and mc1.first_coming_motive_class_id = cm.first_coming_motive_class_id  \n");
        //sql.append("  and mc1.before_visit_num + get_visit_count(mc1.customer_id,ds1.sales_date) = 1 \n");
        //sql.append("  and ((mc1.before_visit_num + get_visit_count(mc1.customer_id,ds1.sales_date) = 1 )   \n");

        //sql.append("        )  \n");
        if ( paramBean.getStaffId() != null) {
            sql.append("  and ds1.detail_staff_id = " + paramBean.getStaffId() +"  \n");
        }
        sql.append("  and NOT EXISTS  \n");
        sql.append("  (SELECT 1  \n");
        sql.append("  FROM view_data_sales_detail_valid vds1  \n");
        sql.append("  inner join data_contract dc1 on dc1.shop_id = vds1.shop_id and dc1.slip_no = vds1.slip_no and dc1.delete_date is null  \n");
        sql.append("  WHERE vds1.product_division = 5  \n");
        sql.append("    and vds1.customer_id = mc1.customer_id   \n");
        //sql.append("    AND vds1.shop_id IN (" + paramBean.getShopIDList() + ")\n");
        //sql.append("    AND vds1.sales_date < '" + paramBean.getTargetStartDate() + "' )  \n");
        sql.append("    AND vds1.sales_date < ds1.sales_date)\n");
        sql.append("  ),0) as contracted_value  \n");
        sql.append("   from   \n");
        sql.append("  mst_first_coming_motive cm   \n");
        sql.append("  where cm.delete_date is null  \n");
        
        //Luc start add 20160111 #46345 
        sql.append(" And coalesce((select sum  \n");
        if ( paramBean.getTaxType() == paramBean.TAX_TYPE_UNIT) {
            sql.append("  (discount_detail_value_in_tax)  \n");
        }else {
            sql.append("  (discount_detail_value_no_tax)  \n");
        }
        sql.append("  from view_data_sales_detail_valid ds1  \n");
        sql.append("  inner join mst_customer mc1 on ds1.customer_id = mc1.customer_id  \n");
        sql.append("  inner join data_sales_detail dsd2 on dsd2.shop_id = ds1.shop_id and dsd2.slip_no = ds1.slip_no and ds1.slip_detail_no = dsd2.slip_detail_no \n");
        sql.append("  where mc1.customer_no <>'0'   \n");
        sql.append("  and ds1.shop_id in (" + paramBean.getShopIDList() + ")\n");
        sql.append("  and ds1.product_division = 5  \n");
        sql.append("  and not exists (select 1 from  data_contract dc1 where dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is not null\n");
	sql.append("  and dc1.product_id = ds1.product_id and dsd2.contract_detail_no = dc1.contract_detail_no	)\n");
        sql.append("  and ds1.sales_date between  '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        sql.append("  and mc1.first_coming_motive_class_id = cm.first_coming_motive_class_id  \n");
        //sql.append("  and mc1.before_visit_num + get_visit_count(mc1.customer_id,ds1.sales_date) = 1 \n");
        //sql.append("  and ((mc1.before_visit_num + get_visit_count(mc1.customer_id,ds1.sales_date) = 1 )   \n");
        //sql.append("        )  \n");
        if ( paramBean.getStaffId() != null) {
            sql.append("  and ds1.detail_staff_id = " + paramBean.getStaffId() +"  \n");
        }
        sql.append("  and NOT EXISTS  \n");
        sql.append("  (SELECT 1  \n");
        sql.append("  FROM view_data_sales_detail_valid vds1  \n");
        sql.append("  inner join data_contract dc1 on dc1.shop_id = vds1.shop_id and dc1.slip_no = vds1.slip_no and dc1.delete_date is null  \n");
        sql.append("  WHERE vds1.product_division = 5  \n");
        sql.append("    and vds1.customer_id = mc1.customer_id   \n");
        //sql.append("    AND vds1.shop_id IN (" + paramBean.getShopIDList() + ")\n");
        //sql.append("    AND vds1.sales_date < '" + paramBean.getTargetStartDate() + "' )  \n");
        sql.append("    AND vds1.sales_date < ds1.sales_date )\n");
        sql.append("  ),0) <> 0  \n");
        //Luc end add 20160111 #46345 
        
        sql.append("  group by cm.first_coming_motive_class_id,cm.first_coming_motive_name  \n");
        sql.append("  order by cm.first_coming_motive_class_id   \n");
        sql.append("  ) t  \n");
        sql.append("  where t.new_customer > 0 or contracted_customer > 0  \n");

        ConnectionWrapper cw = SystemInfo.getConnection();
        ResultSetWrapper rs = new ResultSetWrapper();
        SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
        
        try {
            
            rs = cw.executeQuery(sql.toString());
            if (!rs.next()) {
                return false;
            }

            JExcelApi jx = new JExcelApi("レスポンス別契約率");
            jx.setTemplateFile("/reports/レスポンス別契約率.xls");
            jx.setValue(2, 3, paramBean.getTargetName());
            jx.setValue(2, 4, format.format(paramBean.getTargetStartDateObj()) + " ～ " + format.format(paramBean.getTargetEndDateObj()));
            jx.setValue(2, 5, paramBean.getStaffName());
            
            if (paramBean.getTaxType() == ReportParameterBean.TAX_TYPE_BLANK) {
                jx.setValue(2, 6, "税抜");
            }else {
                jx.setValue(2, 6, "税込");
            }

            int row = 9;
            rs.last();
            int num = 0;
            num = rs.getRow();

            if(num > 2) {
                jx.insertRow(row, num - 2);
            }

            rs.beforeFirst();
             while (rs.next()) {
                 //mergecell
                 jx.mergeCells(1, row, 2, row);
                 jx.mergeCells(3, row, 4, row);
                 jx.mergeCells(5, row, 6, row);
                 jx.mergeCells(7, row, 8, row);
                 jx.mergeCells(9, row, 10, row);
                 jx.mergeCells(11, row, 12, row);
               
                int numCustomer = rs.getInt("contracted_customer");
                jx.setValue(1, row, rs.getString("first_coming_motive_name"));
                jx.setValue(3, row, rs.getInt("new_customer"));
                jx.setValue(5, row, rs.getInt("contracted_customer"));
                if ( numCustomer > 0) {
                    jx.setValue(9, row, rs.getLong("contracted_value")/numCustomer);
                }else {
                    jx.setValue(9, row, rs.getLong("contracted_value"));
                }
                jx.setValue(11, row,rs.getLong("contracted_value"));
                
                if ( rs.getInt("new_customer") == 0) {
                    jx.setValue(7, row, 1);
                }

                row ++ ;
             }
            if(num < 2) {
                jx.removeRow(row);
            }
            jx.openWorkbook();
        } catch (Exception e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(1099),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    //IVS_LVTu end edit 2016/02/17 New request #48268
    
    //リターン率集計
    private boolean getContractRateReturnCustomer(ReportParameterBean paramBean) {
        Integer firstComingMotives = null;
        String firstComingMotiveName = "";
        if ( cmbFirstVisit.isEnabled() == true ) {
            if (0 < cmbFirstVisit.getSelectedIndex()) {
                firstComingMotives = ((MstFirstComingMotive)cmbFirstVisit.getSelectedItem()).getFirstComingMotiveClassId();
                firstComingMotiveName = ((MstFirstComingMotive)cmbFirstVisit.getSelectedItem()).getFirstComingMotiveName();
            }
        }
        StringBuilder sql = new StringBuilder();
               
        sql.append("	SELECT t.*,  \n");
        sql.append("		   array_to_string(array  \n");
        sql.append("		(SELECT CASE WHEN (t.detail_staff_id IS NULL  \n");
        sql.append("		AND dsd1.staff_id IS NULL)  \n");
        sql.append("            OR (t.detail_staff_id IS NOT NULL  \n");
        sql.append("		AND dsd1.staff_id = t.detail_staff_id) THEN mc.course_name ELSE '' END  \n");
        sql.append("		FROM data_sales ds1  \n");
        sql.append("		INNER JOIN data_sales_detail dsd1 ON ds1.slip_no = dsd1.slip_no  \n");
        sql.append("		AND ds1.shop_id = dsd1.shop_id  \n");
        sql.append("		INNER JOIN mst_course mc ON dsd1.product_id = mc.course_id  \n");
        sql.append("		inner join data_contract dc1 on dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is null \n");
        sql.append("		WHERE ds1.customer_id = t.customer_id  \n");
        sql.append("			AND ds1.shop_id = t.shop_id  \n");
        sql.append("			AND product_division = 5  \n");
        sql.append("			AND ds1.sales_date = t.sales_date  \n");
        sql.append("			and ds1.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
	sql.append("                    and ds1.delete_date is null   \n");
	sql.append("			and dsd1.delete_date is null   \n");
        sql.append("			AND ds1.insert_date = t.insert_date), ', ') AS course_name,  \n");
        sql.append("	  (SELECT coalesce(sum(CASE WHEN (t.detail_staff_id IS NULL  \n");
        sql.append("			AND detail_staff_id IS NULL)  \n");
        sql.append("			 OR (t.detail_staff_id IS NOT NULL  \n");
        sql.append("			 AND detail_staff_id = t.detail_staff_id) THEN \n");
        if ( paramBean.getTaxType() == paramBean.TAX_TYPE_UNIT) {
            sql.append("		discount_detail_value_in_tax   \n");   
        }else {
            sql.append("		discount_detail_value_no_tax   \n");   
        }
        sql.append("		ELSE 0 END),0)  \n");
        sql.append("	   FROM data_sales ds1  \n");
        sql.append("	   INNER JOIN view_data_sales_detail_valid dsd1 ON ds1.shop_id = dsd1.shop_id  \n");
        sql.append("	   AND ds1.slip_no = dsd1.slip_no  \n");
        sql.append("	   and dsd1.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        sql.append("	   inner join data_sales_detail dsd2 on dsd2.shop_id = ds1.shop_id and dsd2.slip_no = ds1.slip_no and dsd1.slip_detail_no = dsd2.slip_detail_no \n");
        sql.append("	   WHERE ds1.customer_id =t.customer_id  \n");
        sql.append("		 AND ds1.shop_id = t.shop_id  \n");
        sql.append("		 AND dsd1.product_division = 5  \n");
        sql.append("		 AND ds1.sales_date = t.sales_date  \n");
        sql.append("		 and ds1.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
	sql.append("             and ds1.delete_date is null   \n");
        sql.append("             and not exists (select 1 from  data_contract dc1 where dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is not null  \n");
	sql.append("             and dc1.product_id = dsd1.product_id and dsd2.contract_detail_no = dc1.contract_detail_no )  \n");
        sql.append("		 AND ds1.insert_date = t.insert_date) AS price_value  \n");
        sql.append("	FROM  \n");
        sql.append("	  (SELECT s.shop_id,  \n");
        sql.append("			  s.shop_name,  \n");
        sql.append("			  ds.sales_date,  \n");
        sql.append("			  mc.customer_id,  \n");
        sql.append("			  mc.customer_no,  \n");
        sql.append("			  mc.customer_name1, mc.customer_name2,  \n");
        sql.append("			ds.detail_staff_id,  \n");
        sql.append("			 st.staff_no,  \n");
        sql.append("			st.staff_name1, st.staff_name2,  \n");
        sql.append("		 (SELECT min(ds1.insert_date)  \n");
        sql.append("		  FROM data_sales ds1  \n");
        sql.append("		  INNER JOIN data_sales_detail dsd1 ON ds1.slip_no = dsd1.slip_no  \n");
        sql.append("		  AND ds1.shop_id = dsd1.shop_id  \n");
        sql.append("		  inner join data_contract dc1 on dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is null \n");
        sql.append("		  WHERE ds1.customer_id = mc.customer_id  \n");
        sql.append("			and ds1.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
	sql.append("                    and ds1.delete_date is null   \n");
	sql.append("			and dsd1.delete_date is null   \n");
        sql.append("			AND ds1.shop_id = s.shop_id  \n");
        //Luc start add 20160112 #46345
        sql.append("			and dsd1.product_value <> 0   \n");
        //Luc end add 20160112 #46345
        sql.append("			AND dsd1.product_division = 5) AS insert_date  \n");
        sql.append("	   FROM view_data_sales_detail_valid ds  \n");
        sql.append("	   INNER JOIN mst_customer mc ON ds.customer_id = mc.customer_id  \n");
        sql.append("	   INNER JOIN mst_shop s ON ds.shop_id = s.shop_id  \n");
        sql.append("	   LEFT JOIN mst_staff st ON ds.detail_staff_id = st.staff_id  \n");
        sql.append("	   inner join data_contract dc1 on dc1.shop_id = ds.shop_id and dc1.slip_no = ds.slip_no and dc1.delete_date is null \n");
        sql.append("	   WHERE ds.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        sql.append("		 AND ds.shop_id IN (" + paramBean.getShopIDList() + ")\n");
        if ( paramBean.getStaffId() != null) {
            sql.append("  AND st.staff_id = " + paramBean.getStaffId() +"  \n");
        }
        if (firstComingMotives != null ) {
            sql.append("  AND mc.first_coming_motive_class_id = " + firstComingMotives +"  \n");
        }
        sql.append("		 AND mc.customer_no <> '0'  \n");
        sql.append("		 AND product_division = 5  \n"); 
        //-- dk mua truoc do kh?ng ph?i l? course
        sql.append("	AND exists   \n");
        sql.append("		   (SELECT 1  \n");
        sql.append("			FROM view_data_sales_detail_valid vds1  \n");
        sql.append("			WHERE vds1.shop_id IN (" + paramBean.getShopIDList() + ")\n");
        sql.append("			  AND vds1.product_division <> 5  \n");
        sql.append("			  and vds1.customer_id = ds.customer_id  \n");
        //Luc start edit 20160120 
        //sql.append("			  AND vds1.sales_date < '" + paramBean.getTargetStartDate() + "' )  \n"); 
        sql.append("			  AND vds1.sales_date <= ds.sales_date  \n");
	sql.append("			  		  and vds1.slip_no <> ds.slip_no)  \n");
        //Luc start edit 20160120 
        
        sql.append("	AND not exists    \n"); 
	sql.append("	   (SELECT 1   \n"); 
	sql.append("		FROM view_data_sales_detail_valid vds1   \n"); 
	sql.append("		inner join data_contract dc1 on dc1.shop_id = vds1.shop_id and dc1.slip_no = vds1.slip_no and dc1.delete_date is null \n"); 
	sql.append("			WHERE vds1.shop_id IN (" + paramBean.getShopIDList() + ")\n");
        sql.append("			  AND vds1.product_division = 5  \n");
        sql.append("			  and vds1.customer_id = ds.customer_id  \n");
        sql.append("			  AND vds1.sales_date < '" + paramBean.getTargetStartDate() + "' )  \n");
        //--Dieu kien lan dau tien mua course
        sql.append("	AND sales_date =  \n");
        sql.append("		   (SELECT min(sales_date)  \n");
        sql.append("			FROM view_data_sales_detail_valid ds1  \n");
        sql.append("			inner join data_contract dc1 on dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is null \n");
        sql.append("			WHERE ds1.customer_id = ds.customer_id  \n");
        sql.append("			  AND ds1.shop_id = ds.shop_id  \n");
        sql.append("			  AND ds1.product_division = 5  \n");
        //Luc start add 20160112 #46345
        sql.append("			 and ds1.product_value <> 0 \n");
        //Luc start end 20160112 #46345
        sql.append("			  AND ds1.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "' )  \n"); //-- dk check neu c?ng ng?y mua th? check ng?y insert_date
        sql.append("	AND EXISTS  \n");
        sql.append("		   (SELECT 1  \n");
        sql.append("			FROM data_sales ds1  \n");
        sql.append("			inner join data_contract dc1 on dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is null \n");
        sql.append("			INNER JOIN data_sales_detail dsd1 ON ds1.slip_no = dsd1.slip_no  \n");
        sql.append("			AND ds1.shop_id = dsd1.shop_id  \n");
        sql.append("			AND customer_id = ds.customer_id  \n");
        sql.append("			AND ds1.insert_date =  \n");
        sql.append("			  (SELECT min(ds2.insert_date)  \n");
        sql.append("			   FROM data_sales ds2  \n");
        sql.append("			   INNER JOIN data_sales_detail dsd2 ON ds2.slip_no = dsd2.slip_no  \n");
        sql.append("			   AND ds2.shop_id = dsd2.shop_id  \n");
        sql.append("			   WHERE ds2.customer_id = ds.customer_id  \n");
        sql.append("				 AND ds2.shop_id = ds.shop_id  \n");
        sql.append("				 AND dsd2.product_division = 5  \n");
        //Luc start add 20160112 #46345
        sql.append("				 and dsd2.product_value <> 0  \n");
        //Luc start end 20160112 #46345
        sql.append("				 AND ds2.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'))  \n");
        sql.append("	   GROUP BY s.shop_id,  \n");
        sql.append("				s.shop_name,  \n");
        sql.append("				ds.sales_date,  \n");
        sql.append("				mc.customer_id,  \n");
        sql.append("				mc.customer_no,  \n");
        sql.append("				mc.customer_name1,  \n");
        sql.append("				mc.customer_name2,  \n");
        sql.append("				ds.detail_staff_id,  \n");
        sql.append("				st.staff_no,  \n");
        sql.append("				st.staff_name1,  \n");
        sql.append("				st.staff_name2)t  \n");
        
        //Luc start add 20160111 #46345
        sql.append("	 where (SELECT coalesce(sum(CASE WHEN (t.detail_staff_id IS NULL  \n");
        sql.append("			AND detail_staff_id IS NULL)  \n");
        sql.append("			 OR (t.detail_staff_id IS NOT NULL  \n");
        sql.append("			 AND detail_staff_id = t.detail_staff_id) THEN \n");
        if ( paramBean.getTaxType() == paramBean.TAX_TYPE_UNIT) {
            sql.append("		discount_detail_value_in_tax   \n");   
        }else {
            sql.append("		discount_detail_value_no_tax   \n");   
        }
        sql.append("		ELSE 0 END),0)  \n");
        sql.append("	   FROM data_sales ds1  \n");
        sql.append("	   INNER JOIN view_data_sales_detail_valid dsd1 ON ds1.shop_id = dsd1.shop_id  \n");
        sql.append("	   AND ds1.slip_no = dsd1.slip_no  \n");
        sql.append("	   and dsd1.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        sql.append("	   inner join data_sales_detail dsd2 on dsd2.shop_id = ds1.shop_id and dsd2.slip_no = ds1.slip_no and dsd1.slip_detail_no = dsd2.slip_detail_no \n");
        sql.append("	   WHERE ds1.customer_id =t.customer_id  \n");
        sql.append("		 AND ds1.shop_id = t.shop_id  \n");
        sql.append("		 AND dsd1.product_division = 5  \n");
        sql.append("		 AND ds1.sales_date = t.sales_date  \n");
        sql.append("		 and ds1.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
	sql.append("             and ds1.delete_date is null   \n");
        sql.append("             and not exists (select 1 from  data_contract dc1 where dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is not null  \n");
	sql.append("             and dc1.product_id = dsd1.product_id and dsd2.contract_detail_no = dc1.contract_detail_no )  \n");
        sql.append("		 AND ds1.insert_date = t.insert_date) <> 0  \n");
        //Luc end add 20160111 #46345
        
        sql.append("	ORDER BY t.sales_date  \n");
                
        SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
        ConnectionWrapper cw = SystemInfo.getConnection();
        ResultSetWrapper rs = new ResultSetWrapper();
        
        try {
            //新規来店客数（人）
            Integer newCustomerNum = 0;
            rs = cw.executeQuery(getNewCustomerNumNoCourse(paramBean, firstComingMotives));
            if (rs.next()) {
                newCustomerNum = rs.getInt("new_no_course");
            }
            rs.close();
            
            rs = cw.executeQuery(sql.toString());
            if (!rs.next()) {
                return false;
            }

            JExcelApi jx = new JExcelApi("リターン率集計");
            jx.setTemplateFile("/reports/リターン率集計.xls");
            jx.setValue(2, 3, paramBean.getTargetName());
            jx.setValue(2, 4, format.format(paramBean.getTargetStartDateObj()) + " ～ " + format.format(paramBean.getTargetEndDateObj()));
            jx.setValue(2, 5, paramBean.getStaffName());
            jx.setValue(2, 6, firstComingMotiveName);
            if (paramBean.getTaxType() == ReportParameterBean.TAX_TYPE_BLANK) {
                jx.setValue(2, 7, "税抜");
            }else {
                jx.setValue(2, 7, "税込");
            }
            //新規来店客数（人）
            jx.setValue(1, 10, newCustomerNum);

            if (newCustomerNum <= 0) {
                //新規客契約率（%）
                //契約人数÷新規来店数が1/0のような場合は100%とする
                jx.setValue(5, 10, 1);
            }

            int row = 13;
            rs.last();
            int num = 0;
            num = rs.getRow();

            //契約客数（人）
            HashMap<Integer, String> customerMap = new HashMap<Integer, String>();
            rs.beforeFirst();
            while (rs.next()) {
                if (!customerMap.containsKey(rs.getInt("customer_id"))) {
                    customerMap.put(rs.getInt("customer_id"), rs.getString("customer_no"));
                }
            }
            jx.setValue(3, 10, customerMap.size());
            // if 契約客数（人）= 0 then 契約客単価（円）
            if ( num <= 0 ) {
                jx.setValue(7, 10, num);
            }

            if(num > 2) {
                jx.insertRow(row, num - 2);
            }

            rs.beforeFirst();
             while (rs.next()) {
                 //mergecell
                 jx.mergeCells(6, row, 9, row);
                // add data
                String staffFullName = "";
                String courseName    = "";
                String[] arrCourse ;
                courseName = rs.getString("course_name");
                arrCourse = courseName.split(", ");
                courseName = "";
                for (int i = 0;i < arrCourse.length;i ++ ) {
                    //arrCourse[i] == "" then i ++
                    if ( arrCourse[i].equals("")) {
                        continue;
                    }
                    courseName += arrCourse[i];
                    // set , 
                    if ( (i + 1) < arrCourse.length ) {
                        courseName +=", ";
                    }
                }
                staffFullName =  rs.getString("staff_name1")!= null ? rs.getString("staff_name1") + " ": "";
                staffFullName +=  rs.getString("staff_name2")!= null ? rs.getString("staff_name2"): "";

                jx.setValue(1, row, rs.getString("shop_name"));
                jx.setValue(2, row, format.format(rs.getDate("sales_date")));
                jx.setValue(3, row, rs.getString("customer_no"));
                jx.setValue(4, row, rs.getString("customer_name1") + " " + rs.getString("customer_name2") );
                jx.setValue(5, row, staffFullName);
                jx.setValue(6, row, courseName);
                jx.setValue(10, row, rs.getLong("price_value"));

                row ++ ;
             }
            if(num < 2) {
                jx.removeRow(row);
            }
            jx.openWorkbook();
        } catch (Exception e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(1099),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    //初回来店客数（人）
    private String getNewCustomerNumNoCourse(ReportParameterBean paramBean , Integer firstComingMotives) {
        StringBuilder sql = new StringBuilder();
        
        sql.append("  SELECT count(DISTINCT ds.customer_id) AS new_no_course  \n");
        sql.append("  FROM view_data_sales_detail_valid ds  \n");
        sql.append("  INNER JOIN mst_customer mc ON ds.customer_id = mc.customer_id  \n");
        sql.append("  WHERE ds.sales_date BETWEEN '" + paramBean.getTargetStartDate() + "' and '" + paramBean.getTargetEndDate() + "'\n");
        sql.append("    AND ds.shop_id IN (" + paramBean.getShopIDList() + ")\n");
        if ( paramBean.getStaffId() != null) {
            sql.append("  and ds.detail_staff_id = " + paramBean.getStaffId() +"  \n");
        }
        if (firstComingMotives != null ) {
            sql.append("  and mc.first_coming_motive_class_id = " + firstComingMotives +"  \n");
        }
        sql.append("    AND mc.before_visit_num + get_visit_count(mc.customer_id,ds.sales_date) = 1  \n");
        sql.append("    AND mc.customer_no <> '0'  \n");
        sql.append("    AND ds.sales_date IS NOT NULL  \n");
        sql.append("    AND NOT EXISTS  \n");
        sql.append("      (SELECT 1  \n");
        sql.append("       FROM view_data_sales_detail_valid ds1  \n");
        sql.append("       inner join data_contract dc1 on dc1.shop_id = ds1.shop_id and dc1.slip_no = ds1.slip_no and dc1.delete_date is null \n");
        sql.append("       WHERE ds1.slip_no = ds.slip_no  \n");
        sql.append("         AND ds1.shop_id = ds.shop_id  \n");
        sql.append("         AND ds1.product_division = 5)  \n");
               
        return sql.toString();
    }

    /**
     * 業務報告画面用FocusTraversalPolicyを取得する。
     *
     * @return 業務報告画面用FocusTraversalPolicy
     */
    public ContractRateReportPanelFocusTraversalPolicy getFocusTraversalPolicy() {
        return ftp;
    }

    /**
     * 業務報告画面用FocusTraversalPolicy
     */
    private class ContractRateReportPanelFocusTraversalPolicy
            extends FocusTraversalPolicy {

        /**
         * aComponBusinessReportFocusTraversalPolicy。 aContainer は aComponent
         * のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダでなければなりません。
         *
         * @param aContainer aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
         * @param aComponent aContainer のおそらく間接的な子、または aContainer 自体
         * @return aComponent のあとにフォーカスを受け取る Component。適切な Component が見つからない場合は
         * null
         */
        public Component getComponentAfter(Container aContainer,
                Component aComponent) {
            if (aComponent.equals(rdoNewContract)) {
                    return rdoContractRate;
            }else if (aComponent.equals(rdoContractRate)) {
                return rdoReturnRate;
            }else if (aComponent.equals(rdoReturnRate)) {
                return cmbShop;
            } else if (aComponent.equals(cmbShop)) {
                return cmbTargetPeriodStart;
            } else if (aComponent.equals(cmbTargetPeriodStart)) {
                return cmbTargetPeriodEnd;
            } else if (aComponent.equals(cmbTargetPeriodEnd)) {
                return cmbstaff;
            } else if (aComponent.equals(cmbstaff)) {
                return cmbFirstVisit;
            } else if (aComponent.equals(cmbFirstVisit)) {
                return rdoTaxUnit;
            }else if (aComponent.equals(rdoTaxUnit)) {
                return rdoTaxBlank;
            }
            return rdoNewContract;
        }

        /**
         * aComponent の前にフォーカスを受け取る Component を返します。 aContainer は aComponent
         * のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダでなければなりません。
         *
         * @param aContainer aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
         * @param aComponent aContainer のおそらく間接的な子、または aContainer 自体
         * @return aComponent の前にフォーカスを受け取る Component。適切な Component が見つからない場合は
         * null
         */
        public Component getComponentBefore(Container aContainer,
                Component aComponent) {
            if (aComponent.equals(rdoNewContract)) {
                    return rdoContractRate;
            }else if (aComponent.equals(rdoContractRate)) {
                return rdoReturnRate;
            }else if (aComponent.equals(rdoReturnRate)) {
                return cmbShop;
            } else if (aComponent.equals(cmbShop)) {
                return cmbTargetPeriodStart;
            } else if (aComponent.equals(cmbTargetPeriodStart)) {
                return cmbTargetPeriodEnd;
            } else if (aComponent.equals(cmbTargetPeriodEnd)) {
                return cmbstaff;
            } else if (aComponent.equals(cmbstaff)) {
                return cmbFirstVisit;
            } else if (aComponent.equals(cmbFirstVisit)) {
                return rdoTaxUnit;
            }else if (aComponent.equals(rdoTaxUnit)) {
                return rdoTaxBlank;
            }
            return rdoNewContract;
        }

        /**
         * トラバーサルサイクルの最初の Component を返します。 このメソッドは、順方向のトラバーサルがラップするときに、次にフォーカスする
         * Component を判定するために使用します。
         *
         * @param aContainer 先頭の Component
         * を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
         * @return aContainer のトラバーサルサイクルの先頭の Componet、または適切な Component
         * が見つからない場合は null
         */
        public Component getFirstComponent(Container aContainer) {
            return rdoNewContract;
        }

        /**
         * トラバーサルサイクルの最後の Component を返します。 このメソッドは、逆方向のトラバーサルがラップするときに、次にフォーカスする
         * Component を判定するために使用します。
         *
         * @param aContainer aContainer - 最後の Component
         * を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
         * @return aContainer のトラバーサルサイクルの最後の Componet、または適切な Component
         * が見つからない場合は null
         */
        public Component getLastComponent(Container aContainer) {
            return rdoTaxBlank;
        }

        /**
         * フォーカスを設定するデフォルトコンポーネントを返します。 aContainer
         * をルートとするフォーカストラバーサルサイクルが新しく開始されたときに、このコンポーネントに最初にフォーカスが設定されます。
         *
         * @param aContainer デフォルトの Component
         * を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
         * @return aContainer のトラバーサルサイクルのデフォルトの Componet、または適切な Component
         * が見つからない場合は null
         */
        public Component getDefaultComponent(Container aContainer) {
            return rdoNewContract;
        }

        /**
         * ウィンドウが最初に表示されたときにフォーカスが設定されるコンポーネントを返します。 show() または setVisible(true)
         * の呼び出しで一度ウィンドウが表示されると、 初期化コンポーネントはそれ以降使用されません。
         * 一度別のウィンドウに移ったフォーカスが再び設定された場合、 または、一度非表示状態になったウィンドウが再び表示された場合は、
         * そのウィンドウの最後にフォーカスが設定されたコンポーネントがフォーカス所有者になります。
         * このメソッドのデフォルト実装ではデフォルトコンポーネントを返します。
         *
         * @param window 初期コンポーネントが返されるウィンドウ
         * @return 最初にウィンドウが表示されるときにフォーカス設定されるコンポーネント。適切なコンポーネントがない場合は null
         */
    }
}
