/*
 * StaffResultRepeatReportPanel.java
 *
 * Created on 2008/06/14, 15:00
 */

package com.geobeck.sosia.pos.hair.report;

import com.geobeck.sosia.pos.basicinfo.SimpleMaster;
import com.geobeck.sosia.pos.system.SystemInfo;
import java.awt.*;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.text.*;
import com.geobeck.swing.*;
import com.geobeck.sosia.pos.master.company.*;
import com.geobeck.sosia.pos.report.bean.ReportParameterBean;
import com.geobeck.sosia.pos.hair.report.logic.ReportLogic;
import com.geobeck.sosia.pos.master.MstData;
import com.geobeck.sosia.pos.swing.SelectTableCellRenderer;
import com.geobeck.sosia.pos.util.*;
import com.geobeck.sql.ConnectionWrapper;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  saito
 */
public class StaffResultRepeatReportPanel extends com.geobeck.sosia.pos.swing.AbstractImagePanelEx
{
        //IVS_vtnhan start add 20140723 MASHU_担当再来分析
        private MstShopCategorys		mscg		=	new MstShopCategorys();
        private MstShopCategorys mrsRef = new MstShopCategorys();
        private MstShopCategorys mrsUse = new MstShopCategorys();
        private int useShopCategory = 0;
        private boolean isHideCategory = false;
        //IVS_vtnhan end add 20140723 MASHU_担当再来分析
	/** Creates new form StaffResultRepeatReportPanel */
	public StaffResultRepeatReportPanel()
	{
		initComponents();
		addMouseCursorChange();
                //IVS_vtnhan start edit 20140723 MASHU_担当再来分析
               // this.setSize(450, 603);
                this.setSize(720, 603);
                //IVS_vtnhan end add 20140723 MASHU_担当再来分析
		this.setPath("帳票出力");
		this.setTitle("担当別再来成績");
		this.setKeyListener();
                
                target.addItem(SystemInfo.getGroup());
                SystemInfo.getGroup().addGroupDataToJComboBox(target, 3);
                if (!SystemInfo.isGroup()) {
                    target.setSelectedItem(SystemInfo.getCurrentShop());
                }
                
                //対象期間の設定
		this.termFrom.setDate(new Date());
		this.termTo.setDate(new Date());
		
		//税抜、税込の初期設定
		if(SystemInfo.getAccountSetting().getReportPriceType() == 0)
		{
			rdoTaxBlank.setSelected(false);
			rdoTaxUnit.setSelected(true);
		}
		else
		{
			rdoTaxBlank.setSelected(true);
			rdoTaxUnit.setSelected(false);
		}
   
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportTypeGroup = new javax.swing.ButtonGroup();
        taxGroup = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlMain = new javax.swing.JPanel();
        targetLabel = new javax.swing.JLabel();
        target = new com.geobeck.sosia.pos.swing.JComboBoxLabel();
        jPanel1 = new javax.swing.JPanel();
        termtLabe = new javax.swing.JLabel();
        termFrom = new jp.co.flatsoft.fscomponent.FSCalenderCombo();
        termtLabe1 = new javax.swing.JLabel();
        termTo = new jp.co.flatsoft.fscomponent.FSCalenderCombo();
        termtLabe2 = new javax.swing.JLabel();
        calculationTo = new jp.co.flatsoft.fscomponent.FSCalenderCombo();
        termtLabe3 = new javax.swing.JLabel();
        calculationFrom = new jp.co.flatsoft.fscomponent.FSCalenderCombo();
        btnOutput1 = new javax.swing.JButton();
        lblTargetPeriod4 = new javax.swing.JLabel();
        txtFixedCount = new javax.swing.JTextField();
        ((PlainDocument)txtFixedCount.getDocument()).setDocumentFilter(
            new CustomFilter(3, CustomFilter.NUMERIC));
        lblTargetPeriod5 = new javax.swing.JLabel();
        lblNewDivision = new javax.swing.JLabel();
        radnewShop = new javax.swing.JRadioButton();
        radNewAllShop = new javax.swing.JRadioButton();
        lblTargetPeriod10 = new javax.swing.JLabel();
        rdoSameShopCatVisit = new javax.swing.JRadioButton();
        rdoDiffShopCatVisit = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        lblTax = new javax.swing.JLabel();
        rdoTaxUnit = new javax.swing.JRadioButton();
        rdoTaxBlank = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        referenceCategoryLeftScrollPane = new javax.swing.JScrollPane();
        tblReferenceCategoryName = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        selectButton = new javax.swing.JButton();
        selectAllButton = new javax.swing.JButton();
        releaseButton = new javax.swing.JButton();
        releaseAllButton = new javax.swing.JButton();
        selectCategoryRightScrollPane = new javax.swing.JScrollPane();
        tblSelectCategoryName = new javax.swing.JTable();
        lblCategory = new javax.swing.JLabel();

        setFocusCycleRoot(true);

        pnlMain.setFocusCycleRoot(true);
        pnlMain.setOpaque(false);

        targetLabel.setText("対象");
        targetLabel.setFocusCycleRoot(true);

        target.setFocusCycleRoot(true);
        target.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlMainLayout = new org.jdesktop.layout.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .add(targetLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21)
                .add(target, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(targetLabel)
                    .add(target, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "担当別再来成績", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(51, 51, 51)));
        jPanel1.setOpaque(false);

        termtLabe.setText("評価期間");

        termFrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        termFrom.setDate(new java.util.Date());
        termFrom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                termFromItemStateChanged(evt);
            }
        });

        termtLabe1.setText("～");

        termTo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        termTo.setDate(new java.util.Date());

        termtLabe2.setText("集計期間");

        calculationTo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        calculationTo.setDate(new java.util.Date());

        termtLabe3.setText("～");

        calculationFrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        calculationFrom.setDate(new java.util.Date());

        btnOutput1.setIcon(SystemInfo.getImageIcon("/button/print/excel_off.jpg"));
        btnOutput1.setBorderPainted(false);
        btnOutput1.setContentAreaFilled(false);
        btnOutput1.setFocusCycleRoot(true);
        btnOutput1.setPressedIcon(SystemInfo.getImageIcon("/button/print/excel_on.jpg"));
        btnOutput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutput1ActionPerformed(evt);
            }
        });

        lblTargetPeriod4.setText("固定回数");

        txtFixedCount.setText("4");

        lblTargetPeriod5.setText("回以上");

        lblNewDivision.setText("新規区分");
        lblNewDivision.setFocusCycleRoot(true);

        buttonGroup2.add(radnewShop);
        radnewShop.setSelected(true);
        radnewShop.setText("自店新規");
        radnewShop.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radnewShop.setFocusCycleRoot(true);
        radnewShop.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radnewShop.setOpaque(false);

        buttonGroup2.add(radNewAllShop);
        radNewAllShop.setText("全店新規");
        radNewAllShop.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radNewAllShop.setFocusCycleRoot(true);
        radNewAllShop.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radNewAllShop.setOpaque(false);

        lblTargetPeriod10.setText("業態再来");

        buttonGroup1.add(rdoSameShopCatVisit);
        rdoSameShopCatVisit.setSelected(true);
        rdoSameShopCatVisit.setText("同業態での再来のみ対象");
        rdoSameShopCatVisit.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoSameShopCatVisit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rdoSameShopCatVisit.setOpaque(false);

        buttonGroup1.add(rdoDiffShopCatVisit);
        rdoDiffShopCatVisit.setText("他業態での再来も対象");
        rdoDiffShopCatVisit.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoDiffShopCatVisit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rdoDiffShopCatVisit.setOpaque(false);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(termtLabe, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(termFrom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(termtLabe2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(calculationFrom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(termtLabe3)
                            .add(termtLabe1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(termTo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(38, 38, 38)
                                .add(btnOutput1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(calculationTo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblTargetPeriod4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblNewDivision)
                            .add(lblTargetPeriod10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(radnewShop)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(radNewAllShop))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(txtFixedCount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(lblTargetPeriod5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(rdoDiffShopCatVisit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rdoSameShopCatVisit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(termtLabe, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(termFrom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(termtLabe1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(termtLabe2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(termtLabe3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(calculationFrom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnOutput1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(termTo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(calculationTo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblTargetPeriod4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtFixedCount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblTargetPeriod5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblNewDivision)
                    .add(radnewShop)
                    .add(radNewAllShop))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblTargetPeriod10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rdoSameShopCatVisit)
                    .add(rdoDiffShopCatVisit)))
        );

        jPanel2.setOpaque(false);

        lblTax.setText("税区分");
        lblTax.setFocusCycleRoot(true);

        taxGroup.add(rdoTaxUnit);
        rdoTaxUnit.setText("税込");
        rdoTaxUnit.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoTaxUnit.setFocusCycleRoot(true);
        rdoTaxUnit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rdoTaxUnit.setOpaque(false);

        taxGroup.add(rdoTaxBlank);
        rdoTaxBlank.setText("税抜");
        rdoTaxBlank.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoTaxBlank.setFocusCycleRoot(true);
        rdoTaxBlank.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rdoTaxBlank.setOpaque(false);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(lblTax)
                .add(44, 44, 44)
                .add(rdoTaxUnit)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rdoTaxBlank)
                .addContainerGap(598, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblTax)
                    .add(rdoTaxUnit)
                    .add(rdoTaxBlank))
                .addContainerGap())
        );

        jPanel3.setOpaque(false);

        tblReferenceCategoryName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "業態名", "業態ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReferenceCategoryName.setSelectionForeground(new java.awt.Color(0, 0, 0));
        //nhanvt
        tblReferenceCategoryName.getTableHeader().setReorderingAllowed(false);
        SwingUtil.setJTableHeaderRenderer(tblReferenceCategoryName, SystemInfo.getTableHeaderRenderer());
        tblReferenceCategoryName.setRowHeight(SystemInfo.TABLE_ROW_HEIGHT);
        SelectTableCellRenderer.setSelectTableCellRenderer(tblReferenceCategoryName);
        //nhanvt
        tblReferenceCategoryName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblReferenceCategoryNameMouseMoved(evt);
            }
        });
        referenceCategoryLeftScrollPane.setViewportView(tblReferenceCategoryName);
        tblReferenceCategoryName.getColumnModel().getColumn(0).setMinWidth(250);
        tblReferenceCategoryName.getColumnModel().getColumn(0).setMaxWidth(250);
        tblReferenceCategoryName.getColumnModel().getColumn(1).setMinWidth(0);
        tblReferenceCategoryName.getColumnModel().getColumn(1).setPreferredWidth(0);
        tblReferenceCategoryName.getColumnModel().getColumn(1).setMaxWidth(0);

        jPanel4.setOpaque(false);

        selectButton.setIcon(SystemInfo.getImageIcon("/button/arrow/right_off.jpg"));
        selectButton.setBorderPainted(false);
        selectButton.setContentAreaFilled(false);
        selectButton.setPressedIcon(SystemInfo.getImageIcon("/button/arrow/right_on.jpg"));
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        selectAllButton.setIcon(SystemInfo.getImageIcon("/button/arrow/right2_off.jpg"));
        selectAllButton.setBorderPainted(false);
        selectAllButton.setContentAreaFilled(false);
        selectAllButton.setPressedIcon(SystemInfo.getImageIcon("/button/arrow/right2_on.jpg"));
        selectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });

        releaseButton.setIcon(SystemInfo.getImageIcon("/button/arrow/left_off.jpg"));
        releaseButton.setBorderPainted(false);
        releaseButton.setContentAreaFilled(false);
        releaseButton.setPressedIcon(SystemInfo.getImageIcon("/button/arrow/left_on.jpg"));
        releaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                releaseButtonActionPerformed(evt);
            }
        });

        releaseAllButton.setIcon(SystemInfo.getImageIcon("/button/arrow/left2_off.jpg"));
        releaseAllButton.setBorderPainted(false);
        releaseAllButton.setContentAreaFilled(false);
        releaseAllButton.setPressedIcon(SystemInfo.getImageIcon("/button/arrow/left2_on.jpg"));
        releaseAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                releaseAllButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(selectButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(releaseButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(releaseAllButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(selectAllButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(selectAllButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(selectButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 39, Short.MAX_VALUE)
                .add(releaseButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(releaseAllButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        tblSelectCategoryName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "業態名", "業態ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSelectCategoryName.setSelectionForeground(new java.awt.Color(0, 0, 0));
        //nhanvt
        tblSelectCategoryName.getTableHeader().setReorderingAllowed(false);
        SwingUtil.setJTableHeaderRenderer(tblSelectCategoryName, SystemInfo.getTableHeaderRenderer());
        tblSelectCategoryName.setRowHeight(SystemInfo.TABLE_ROW_HEIGHT);
        SelectTableCellRenderer.setSelectTableCellRenderer(tblSelectCategoryName);
        //TableColumnModel model = tblSelectCategoryName.getColumnModel();
        //model.getColumn(2).setCellEditor(new IntegerCellEditor(new JTextField()));
        //model.getColumn(3).setCellEditor(new IntegerCellEditor(new JTextField()));
        //model.getColumn(4).setCellEditor(new IntegerCellEditor(new JTextField()));
        //model.getColumn(5).setCellEditor(new IntegerCellEditor(new JTextField()));
        //nhanvt
        tblSelectCategoryName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSelectCategoryNameMouseClicked(evt);
            }
        });
        tblSelectCategoryName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblSelectCategoryNamePropertyChange(evt);
            }
        });
        selectCategoryRightScrollPane.setViewportView(tblSelectCategoryName);
        tblSelectCategoryName.getColumnModel().getColumn(0).setMinWidth(250);
        tblSelectCategoryName.getColumnModel().getColumn(0).setMaxWidth(250);
        tblSelectCategoryName.getColumnModel().getColumn(1).setMinWidth(0);
        tblSelectCategoryName.getColumnModel().getColumn(1).setPreferredWidth(0);
        tblSelectCategoryName.getColumnModel().getColumn(1).setMaxWidth(0);

        lblCategory.setText("集計業態");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(lblCategory)
                .add(32, 32, 32)
                .add(referenceCategoryLeftScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(selectCategoryRightScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lblCategory)
                    .add(selectCategoryRightScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(referenceCategoryLeftScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlMain, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(pnlMain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOutput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutput1ActionPerformed
                
                if (!this.checkInput()) return;
                if (!SystemInfo.checkAuthorityPassword(246)) return;

                ReportLogic logic = new ReportLogic();
		ReportParameterBean paramBean = new ReportParameterBean();
		paramBean.setMainReportType(ReportParameterBean.MAIN_REPORT_STAFF);
		
		//グループ
		if(target.getSelectedItem() instanceof MstGroup) {
			MstGroup	mg	=	(MstGroup)target.getSelectedItem();
			paramBean.setTargetName(mg.getGroupName());
			paramBean.setShopIDList(mg.getShopIDListAll());
		}
		//店舗
		else if(target.getSelectedItem() instanceof MstShop) {
			MstShop		ms	=	(MstShop)target.getSelectedItem();
			paramBean.setTargetName(ms.getShopName());
			paramBean.setShopIDList(ms.getShopID().toString());
		}
		
		//対象となる店舗が存在しない場合
		if(paramBean.getShopIDList().equals("")) {
			MessageDialog.showMessageDialog(this,
				MessageUtil.getMessage(4001),
				this.getTitle(),
				JOptionPane.ERROR_MESSAGE);
			return;
		}
		
                //税区分
		if(this.rdoTaxBlank.isSelected()) {
			paramBean.setTaxType(ReportParameterBean.TAX_TYPE_BLANK);	// 税区分(税抜き)
		} else if(this.rdoTaxUnit.isSelected()) {
			paramBean.setTaxType(ReportParameterBean.TAX_TYPE_UNIT);	// 税区分(税込み)
		}
                //IVS_vtnhan start add 20140723 MASHU_担当再来分析
                
                //nhanvt start add 20150121 New request #34998
                if(rdoDiffShopCatVisit.isSelected()){
                        paramBean.setDiffShopCatVisit(true);
                }else{
                        paramBean.setDiffShopCatVisit(false);
                }
                
                
                    String lstShopCategoryId = "";
                String lstNameShopCategory = "";
                if(mrsUse.size() >0){
                    int count = 0;
                            for(MstShopCategory category : mrsUse){
                                if(category.getShopCategoryId() != null){
                                    lstShopCategoryId += category.getShopCategoryId();
                            lstNameShopCategory += category.getShopClassName();
                                    count++;
                            if(count < mrsUse.size()){
                                        lstShopCategoryId += ",";
                                lstNameShopCategory += "、";
                                    }
                                }
                            }
                        }
                        if(!lstShopCategoryId.equals("")){
                            paramBean.setListCategoryId(lstShopCategoryId);
                        }else{
                            paramBean.setListCategoryId(null);
                        }
                
                paramBean.setListCategoryName(lstNameShopCategory);
		//nhanvt end add 20150121 New request #34998
                
                paramBean.setIsHideCategory(isHideCategory);
                if(this.radnewShop.isSelected()) {
			paramBean.setNewDevision(ReportParameterBean.NEW_DEVISION);	//自店新規
                        paramBean.setDevisionName("自店新規");
		} else if(this.radNewAllShop.isSelected()) {
			paramBean.setNewDevision(ReportParameterBean.NEW_ALL_DEVISION);	// 全店新規
                        paramBean.setDevisionName("全店新規");
		}
                paramBean.setUseShopCategory(useShopCategory);
                //IVS_vtnhan end add 20140723 MASHU_担当再来分析
		
		//割引の区分の設定
		Integer discountType = SystemInfo.getAccountSetting().getDiscountType();
		paramBean.setDiscountType(discountType);
		
                //対象期間
		paramBean.setCalculationStartDate(this.termFrom.getDateStr("/"));
		paramBean.setCalculationEndDate(this.termTo.getDateStr("/"));
		paramBean.setCalculationStartDateObj(this.termFrom.getDate());
		paramBean.setCalculationEndDateObj(this.termTo.getDate());
                //集計期間
		paramBean.setTargetStartDate(this.calculationFrom.getDateStr("/"));
		paramBean.setTargetEndDate(this.calculationTo.getDateStr("/"));
		paramBean.setTargetStartDateObj(this.calculationFrom.getDate());
		paramBean.setTargetEndDateObj(this.calculationTo.getDate());
		
		Calendar start = Calendar.getInstance();
		Calendar end = Calendar.getInstance();
		start.setTime(this.termFrom.getDate());
		end.setTime(this.termTo.getDate());
                
		if(start.compareTo(end) != 0) {
                        //対象期間が開始日＞終了日ならエラー
			if(start.after(end)) {
				MessageDialog.showMessageDialog(this,
					MessageUtil.getMessage(MessageUtil.ERROR_INPUT_WRONG, "対象期間"),
					this.getTitle(),
					JOptionPane.ERROR_MESSAGE);
				return;
			}
		}
		
		start.setTime(this.calculationFrom.getDate());
		end.setTime(this.calculationTo.getDate());
		
		if(start.compareTo(end) != 0) {
                        //集計期間が開始日＞終了日ならエラー
			if(start.after(end)) {
				MessageDialog.showMessageDialog(this,
					MessageUtil.getMessage(MessageUtil.ERROR_INPUT_WRONG, "集計期間"),
					this.getTitle(),
					JOptionPane.ERROR_MESSAGE);
				return;
			}
		}
                
                // 固定回数
                int fixedCount = 5;
                try {
                    fixedCount = Integer.parseInt(this.txtFixedCount.getText());
                } catch(NumberFormatException e){
                    
                }
                paramBean.setFixedCount(fixedCount);
		
		
		//出力処理
		boolean logicResult = true;
		try {
        		//担当別再来成績
			logicResult = logic.outStaffReportReappearance(paramBean);
		} catch (Exception e) {
			SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
			MessageDialog.showMessageDialog(this,
				MessageUtil.getMessage(1099),
				this.getTitle(),
				JOptionPane.ERROR_MESSAGE);
			return;
		}
		
		// エラー時
		if(!logicResult) {
			MessageDialog.showMessageDialog(this,
				MessageUtil.getMessage(4001),
				this.getTitle(),
				JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_btnOutput1ActionPerformed
    
    private boolean checkInput()
	{
                 //  5. From of 評価期間 = End of 評価期間 = NUll => error : 開始日もしくは終了日が設定されていません。
                if(termFrom.getDate() == null && termTo.getDate() == null   )
		{
			MessageDialog.showMessageDialog(this,
					"開始日もしくは終了日が設定されていません。", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                         termFrom.requestFocusInWindow();
			return	false;
		} 
		//6. From of 評価期間 OR End of 評価期間 = NULL => error : 開始日もしくは終了日が設定されていません。 
                else if(termFrom.getDate() == null || termTo.getDate() == null   )
		{
			MessageDialog.showMessageDialog(this,
					"開始日もしくは終了日が設定されていません。", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                        if(termFrom.getDate() == null){
                            termFrom.requestFocusInWindow();
                        }else{
                            termTo.requestFocusInWindow();
                        }
			return	false;
		}
                //7. From of 評価期間 > End of 評価期間 => error : 開始日が終了日より前の日付になっています。
                 else if(termFrom.getDate().after( termTo.getDate()))
		{
			MessageDialog.showMessageDialog(this,
					"開始日が終了日より前の日付になっています。", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                        termFrom.requestFocusInWindow();
			return	false;
		}
             
                // 集計期間
                // 2. From of 集計期間 = End of 集計期間 = NUll => error : 開始日もしくは終了日が設定されていません。
                if(calculationFrom.getDate() == null && calculationTo.getDate() == null   )
		{
			MessageDialog.showMessageDialog(this,
					"開始日もしくは終了日が設定されていません。", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                         calculationFrom.requestFocusInWindow();
			return	false;
		} 
		//3. From of 集計期間 OR End of 集計期間 = NULL => error : 開始日もしくは終了日が設定されていません。 
                else if(calculationFrom.getDate() == null || calculationTo.getDate() == null   )
		{
			MessageDialog.showMessageDialog(this,
					"開始日もしくは終了日が設定されていません。", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                        if(calculationFrom.getDate() == null){
                            calculationFrom.requestFocusInWindow();
                        }else{
                            calculationTo.requestFocusInWindow();
                        }
			return	false;
		}
                //4. From of 集計期間 > End of 集計期間 => error : 開始日が終了日より前の日付になっています。
                 else if(calculationFrom.getDate().after( calculationTo.getDate()))
		{
			MessageDialog.showMessageDialog(this,
					"開始日が終了日より前の日付になっています。", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                        calculationFrom.requestFocusInWindow();
			return	false;
		}
                // 1. From of 集計期間　＜　from of 評価期間　＝＞error :  集計期間の設定が間違っています。
                    //  集計期間のFromは評価期間のFrom以降の日付で設定してください。
		if(calculationFrom.getDate().before(termFrom.getDate()))
		{
			MessageDialog.showMessageDialog(this,
					"集計期間の設定が間違っています。\n集計期間のFromは評価期間のFrom以降の日付で設定してください。 ", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                        calculationFrom.requestFocusInWindow();
			return	false;
		}
		return	true;
	}
    
    private void termFromItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_termFromItemStateChanged
      //nhanvt edit 20141013 Request #31243
         calculationFrom.setDate(termFrom.getDate());
        //nhanvt edit 20141013 Request #31243
    }//GEN-LAST:event_termFromItemStateChanged

    private void tblReferenceCategoryNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReferenceCategoryNameMouseMoved

    }//GEN-LAST:event_tblReferenceCategoryNameMouseMoved

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
         //IVS_vtnhan start add 20140723 MASHU_担当再来分析
        this.moveMutiCategory(true);
         //IVS_vtnhan end add 20140723 MASHU_担当再来分析
    }//GEN-LAST:event_selectButtonActionPerformed

    private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
        //IVS_vtnhan start add 20140723 MASHU_担当再来分析
        this.moveCategoryAll(true);
         //IVS_vtnhan end add 20140723 MASHU_担当再来分析
    }//GEN-LAST:event_selectAllButtonActionPerformed

    private void releaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_releaseButtonActionPerformed
        //IVS_vtnhan start add 20140723 MASHU_担当再来分析
        this.moveMutiCategory(false);
         //IVS_vtnhan end add 20140723 MASHU_担当再来分析
    }//GEN-LAST:event_releaseButtonActionPerformed

    private void releaseAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_releaseAllButtonActionPerformed
        //IVS_vtnhan start add 20140723 MASHU_担当再来分析
        this.moveCategoryAll(false);
         //IVS_vtnhan end add 20140723 MASHU_担当再来分析
    }//GEN-LAST:event_releaseAllButtonActionPerformed

    private void tblSelectCategoryNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSelectCategoryNameMouseClicked
       
    }//GEN-LAST:event_tblSelectCategoryNameMouseClicked

    private void tblSelectCategoryNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblSelectCategoryNamePropertyChange

    }//GEN-LAST:event_tblSelectCategoryNamePropertyChange

    private void targetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetActionPerformed
        // TODO add your handling code here:
         //IVS_vtnhan start add 20140723 MASHU_担当再来分析
        this.chargeDataCombo();
         //IVS_vtnhan end add 20140723 MASHU_担当再来分析
    }//GEN-LAST:event_targetActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOutput1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private jp.co.flatsoft.fscomponent.FSCalenderCombo calculationFrom;
    private jp.co.flatsoft.fscomponent.FSCalenderCombo calculationTo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblNewDivision;
    private javax.swing.JLabel lblTargetPeriod10;
    private javax.swing.JLabel lblTargetPeriod4;
    private javax.swing.JLabel lblTargetPeriod5;
    private javax.swing.JLabel lblTax;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JRadioButton radNewAllShop;
    private javax.swing.JRadioButton radnewShop;
    private javax.swing.JRadioButton rdoDiffShopCatVisit;
    private javax.swing.JRadioButton rdoSameShopCatVisit;
    private javax.swing.JRadioButton rdoTaxBlank;
    private javax.swing.JRadioButton rdoTaxUnit;
    private javax.swing.JScrollPane referenceCategoryLeftScrollPane;
    private javax.swing.JButton releaseAllButton;
    private javax.swing.JButton releaseButton;
    private javax.swing.ButtonGroup reportTypeGroup;
    private javax.swing.JButton selectAllButton;
    private javax.swing.JButton selectButton;
    private javax.swing.JScrollPane selectCategoryRightScrollPane;
    private com.geobeck.sosia.pos.swing.JComboBoxLabel target;
    private javax.swing.JLabel targetLabel;
    private javax.swing.ButtonGroup taxGroup;
    private javax.swing.JTable tblReferenceCategoryName;
    private javax.swing.JTable tblSelectCategoryName;
    private jp.co.flatsoft.fscomponent.FSCalenderCombo termFrom;
    private jp.co.flatsoft.fscomponent.FSCalenderCombo termTo;
    private javax.swing.JLabel termtLabe;
    private javax.swing.JLabel termtLabe1;
    private javax.swing.JLabel termtLabe2;
    private javax.swing.JLabel termtLabe3;
    private javax.swing.JTextField txtFixedCount;
    // End of variables declaration//GEN-END:variables
	
	private	StaffResultRepeatReportFocusTraversalPolicy	ftp	=
			new StaffResultRepeatReportFocusTraversalPolicy();
	
	/**
	 * ボタンにマウスカーソルが乗ったときにカーソルを変更するイベントを追加する。
	 */
	private void addMouseCursorChange()
	{
		SystemInfo.addMouseCursorChange(btnOutput1);
	}
	
	private void setKeyListener()
	{
		calculationTo.addKeyListener(SystemInfo.getMoveNextField());
		calculationTo.addFocusListener(SystemInfo.getSelectText());
		termTo.addKeyListener(SystemInfo.getMoveNextField());
		termTo.addFocusListener(SystemInfo.getSelectText());
		termFrom.addKeyListener(SystemInfo.getMoveNextField());
		termFrom.addFocusListener(SystemInfo.getSelectText());
		rdoTaxBlank.addKeyListener(SystemInfo.getMoveNextField());
		rdoTaxUnit.addKeyListener(SystemInfo.getMoveNextField());
                //IVS_vtnhan start add 20140730 MASHU_担当再来分析
                tblReferenceCategoryName.addKeyListener(SystemInfo.getMoveNextField());
                selectAllButton.addKeyListener(SystemInfo.getMoveNextField());
                selectButton.addKeyListener(SystemInfo.getMoveNextField());
                releaseButton.addKeyListener(SystemInfo.getMoveNextField());
                releaseAllButton.addKeyListener(SystemInfo.getMoveNextField());
                tblSelectCategoryName.addKeyListener(SystemInfo.getMoveNextField());
                radnewShop.addKeyListener(SystemInfo.getMoveNextField());
                radNewAllShop.addKeyListener(SystemInfo.getMoveNextField());
                //IVS_vtnhan end add 20140730 MASHU_担当再来分析
		target.addKeyListener(SystemInfo.getMoveNextField());
		target.addFocusListener(SystemInfo.getSelectText());
		txtFixedCount.addKeyListener(SystemInfo.getMoveNextField());
		txtFixedCount.addFocusListener(SystemInfo.getSelectText());
	}
	
	/**
	 * 担当別再来成績画面用FocusTraversalPolicyを取得する。
	 * @return  担当別再来成績画面用FocusTraversalPolicy
	 */
	public StaffResultRepeatReportFocusTraversalPolicy getFocusTraversalPolicy()
	{
		return	ftp;
	}
          //IVS_vtnhan start add 20140723 MASHU_担当再来分析
  
        /**
        * init data for table 業態名 left with group shop
        */
       private void initCategoryWithGroupShop() {
           mrsRef = new MstShopCategorys();
           SimpleMaster sm = new SimpleMaster(
                   "",
                   "mst_shop_category",
                   "shop_category_id",
                   "shop_class_name", 0);

           sm.loadData();
           for (MstData md : sm) {
               if(md != null){
                   MstShopCategory category = new MstShopCategory();
                   category.setShopCategoryId(md.getID());
                   category.setShopClassName(md.getName());
                   category.setDisplaySeq(md.getDisplaySeq());
                   mrsRef.add(category);
               }

           }

       } 

       /**
        * init data for table 業態名 left with muti shop
        */
       private void initCategoryWithMutiShop() {
            mrsRef = new MstShopCategorys();
            MstShop ms = (MstShop)target.getSelectedItem();
            if(ms.getShopID() != null){
               try
               {
                       mscg = new MstShopCategorys();
                       ConnectionWrapper	con	=	SystemInfo.getConnection();

                       mscg.loadByShop(con,ms.getShopID());

                       if(mscg.size() > 0){
                           mrsRef = mscg;
                       }

               }
               catch(SQLException e)
               {

                       SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
               }
            }

       }  

       /**
        * change combo and show again two table
        * change combo
        * @param evt 
        */
        private void chargeDataCombo() {   

            mrsRef = new MstShopCategorys();
            mrsUse = new MstShopCategorys();
            //グループ
            if(target.getSelectedItem() instanceof MstGroup) {
                     displayForDesign(true, 1);
                      useShopCategory = 1;
                     isHideCategory = true;
                     initCategoryWithGroupShop();

            }
            //店舗
            else if(target.getSelectedItem() instanceof MstShop) {
                 MstShop ms = (MstShop)target.getSelectedItem();
                 if(ms.getUseShopCategory().equals(1)){
                        displayForDesign(false, 1);
                        useShopCategory = 1;
                        isHideCategory = true;
                        initCategoryWithMutiShop();

                 }else{

                        displayForDesign(false, 0);
                        useShopCategory = 0;
                        isHideCategory = false;

                 }

            }
           

            this.showItems();
       } 

     /**
      * move item
      * @param isSelect 
      */
      public void moveMutiCategory(boolean isSelect) {

        JTable fromTable = (isSelect ? tblReferenceCategoryName : tblSelectCategoryName);

        int index = fromTable.getSelectedRow();
        if (index < 0) return;
        ArrayList<MstShopCategory> tmp = new ArrayList<MstShopCategory>();
        if (isSelect) {
             int[]  selectedIndex = fromTable.getSelectedRows();
            if (selectedIndex.length > 0) {
                for (int i = 0; i < selectedIndex.length; i++) {
                    mrsUse.add(mrsRef.get(selectedIndex[i]));
                    tmp.add(mrsRef.get(selectedIndex[i]));
                }
                mrsRef.removeAll(tmp);
            }
    
        } else {
           
            int[]  selectedIndex = fromTable.getSelectedRows();
            if (selectedIndex.length > 0) {
                for (int i = 0; i < selectedIndex.length; i++) { 
                    mrsRef.add(mrsUse.get(selectedIndex[i]));
                    tmp.add(mrsUse.get(selectedIndex[i]));
                }
                 mrsUse.removeAll(tmp);
            }
           
        }

        this.showItems();
    }
      
    /**
     * move all item
     * @param isSelect 
     */
    public void moveCategoryAll(boolean isSelect) {

        JTable fromTable = (isSelect ? tblReferenceCategoryName : tblSelectCategoryName);

        if (fromTable.getRowCount() == 0) return;

        if (isSelect) {
            for (MstShopCategory mr : mrsRef) mrsUse.add(mr);
            mrsRef.clear();
        } else {
            for (MstShopCategory mr : mrsUse) mrsRef.add(mr);
            mrsUse.clear();
        }

        this.showItems();
    }
      
    /**
     * show data on two table
     */
    private void showItems() {
        this.showItems(mrsRef, tblReferenceCategoryName);
        this.showItems(mrsUse, tblSelectCategoryName);
    } 
    
    /**
     * show data detail on two table
     * @param list
     * @param table 
     */
    private void showItems(ArrayList<MstShopCategory> list, JTable table) {

        Collections.sort(list, new ItemComparator());

        if (table.getCellEditor() != null) table.getCellEditor().stopCellEditing();
        SwingUtil.clearTable(table);
        
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        for (MstShopCategory mr : list) {
            model.addRow(new Object[]{
                mr.getShopClassName()
            });
           
        }
    }
    
    /**
     * control design screen follow combo 対象
     * @param isGroup
     * @param useShopCategory 
     */
    public void displayForDesign(boolean isGroup, Integer useShopCategory){
       
        if(isGroup){
            SwingUtil.clearTable(tblReferenceCategoryName);
            SwingUtil.clearTable(tblSelectCategoryName);
            lblCategory.setVisible(true);
            referenceCategoryLeftScrollPane.setVisible(true);
            tblReferenceCategoryName.setVisible(true);
            selectCategoryRightScrollPane.setVisible(true);
            tblSelectCategoryName.setVisible(true);

            selectAllButton.setVisible(true);
            selectButton.setVisible(true);
            releaseButton.setVisible(true);
            releaseAllButton.setVisible(true);
            //Luc start edit 20150213 #35207
            if(SystemInfo.getSetteing().isUseShopCategory()) {
            jPanel3.setVisible(true);
            lblTargetPeriod10.setVisible(true);
            rdoSameShopCatVisit.setVisible(true);
            rdoDiffShopCatVisit.setVisible(true);
            }else {
                jPanel3.setVisible(false);
                lblTargetPeriod10.setVisible(false);
                rdoSameShopCatVisit.setVisible(false);
                rdoDiffShopCatVisit.setVisible(false);
            }
            //Luc end edit 20150213 #35207
            radnewShop.setSelected(false);
            radNewAllShop.setSelected(true);
            radnewShop.setEnabled(false);
            radNewAllShop.setEnabled(true);
            //nhanvt start add 20150122 New request #34998
            
            //nhanvt end add 20150122 New request #34998        
        }else{
            MstShop ms = (MstShop)target.getSelectedItem();
            if(ms.getUseShopCategory().equals(1)){
                   SwingUtil.clearTable(tblReferenceCategoryName);
                   SwingUtil.clearTable(tblSelectCategoryName);
                   lblCategory.setVisible(true);
                   referenceCategoryLeftScrollPane.setVisible(true);
                   tblReferenceCategoryName.setVisible(true);

                   selectCategoryRightScrollPane.setVisible(true);
                   tblSelectCategoryName.setVisible(true);

                   selectAllButton.setVisible(true);
                   selectButton.setVisible(true);
                   releaseButton.setVisible(true);
                   releaseAllButton.setVisible(true);

                   radnewShop.setSelected(true);
                   radNewAllShop.setSelected(false);
                   radnewShop.setEnabled(true);
                   radNewAllShop.setEnabled(true);
                   jPanel3.setVisible(true);
                   //nhanvt start add 20150122 New request #34998
                   lblTargetPeriod10.setVisible(true);
                   rdoSameShopCatVisit.setVisible(true);
                   rdoDiffShopCatVisit.setVisible(true);
                   //nhanvt end add 20150122 New request #34998

            }else{

                   SwingUtil.clearTable(tblReferenceCategoryName);
                   SwingUtil.clearTable(tblSelectCategoryName);

                   lblCategory.setVisible(false);
                   referenceCategoryLeftScrollPane.setVisible(false);
                   tblReferenceCategoryName.setVisible(false);

                   selectCategoryRightScrollPane.setVisible(false);
                   tblSelectCategoryName.setVisible(false);

                   selectAllButton.setVisible(false);
                   selectButton.setVisible(false);
                   releaseButton.setVisible(false);
                   releaseAllButton.setVisible(false);
                   jPanel3.setVisible(false);
                   radnewShop.setSelected(true);
                   radNewAllShop.setSelected(false);
                   radnewShop.setEnabled(true);
                   radNewAllShop.setEnabled(true);
                   //nhanvt start add 20150122 New request #34998
                   lblTargetPeriod10.setVisible(false);
                   rdoSameShopCatVisit.setVisible(false);
                   rdoDiffShopCatVisit.setVisible(false);
                   //nhanvt end add 20150122 New request #34998

            }
        }

    }
    
    /**
     * compare data
     */
   private class ItemComparator implements java.util.Comparator {
        public int compare(Object s, Object t) {
            return ((MstShopCategory) s).getDisplaySeq()- ((MstShopCategory) t).getDisplaySeq();
	}
   }
    //IVS_vtnhan end add 20140723 MASHU_担当再来分析
	
	
	/**
	 * 担当別再来成績画面用FocusTraversalPolicy
	 */
	private class StaffResultRepeatReportFocusTraversalPolicy
					extends FocusTraversalPolicy
	{
		/**
		 * aComponentStaffResultRepeatReportFocusTraversalPolicy。
		 * aContainer は aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダでなければなりません。
		 * @param aContainer aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @param aComponent aContainer のおそらく間接的な子、または aContainer 自体
		 * @return aComponent のあとにフォーカスを受け取る Component。適切な Component が見つからない場合は null
		 */
		public Component getComponentAfter(Container aContainer,
										   Component aComponent)
		{
			if (aComponent.equals(target))
			{
				return this.getSelectedTaxType();
			}
                        
                        else if (aComponent.equals(rdoTaxBlank) ||
					aComponent.equals(rdoTaxUnit))
			{
				return termFrom;
			}
			else if (aComponent.equals(termFrom))
			{
				return termTo;
			}
			else if (aComponent.equals(termTo))
			{
				return calculationTo;
			}
			else if (aComponent.equals(calculationTo))
			{
				return txtFixedCount;
                        }
                        //IVS_vtnhan start add 20140723 MASHU_担当再来分析
			/*else if (aComponent.equals(txtFixedCount))
			{
				return target;
			}*/
                        else if (aComponent.equals(txtFixedCount))
			{
                            if(radnewShop.isEnabled() && radnewShop.isSelected()){
                                return radnewShop;
                            }
                            if(radNewAllShop.isEnabled() && radNewAllShop.isSelected()){
                                return radNewAllShop;
                            }
                            return target;
			}
                        else if (aComponent.equals(radnewShop) && radnewShop.isEnabled() && radnewShop.isSelected())
			{
				return target;
			}
                         else if (aComponent.equals(radNewAllShop) && radNewAllShop.isEnabled() && radNewAllShop.isSelected())
			{
				return target;
			}
			//IVS_vtnhan end add 20140723 MASHU_担当再来分析
                        return target;
		}

		/**
		 * aComponent の前にフォーカスを受け取る Component を返します。
		 * aContainer は aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダでなければなりません。
		 * @param aContainer aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @param aComponent aContainer のおそらく間接的な子、または aContainer 自体
		 * @return aComponent の前にフォーカスを受け取る Component。適切な Component が見つからない場合は null
		 */
		public Component getComponentBefore(Container aContainer,
											Component aComponent)
		{
                         //IVS_vtnhan start edit 20140723 MASHU_担当再来分析
			if (aComponent.equals(target))
			{
                            if(radnewShop.isEnabled() && radnewShop.isSelected()){
                                return radnewShop;
                            }
                             if(radNewAllShop.isEnabled() && radNewAllShop.isSelected()){
                                return radNewAllShop;
                            }
                            return txtFixedCount;
			}else if(aComponent.equals(radnewShop)&& radnewShop.isEnabled() && radnewShop.isSelected() ){
                             return txtFixedCount;
                        }else if(aComponent.equals(radNewAllShop)&& radNewAllShop.isEnabled() && radNewAllShop.isSelected() ){
                             return txtFixedCount;
                        }
                         //IVS_vtnhan end edit 20140723 MASHU_担当再来分析
                        else if (aComponent.equals(txtFixedCount))
			{
				return calculationTo;
			}
                        else if (aComponent.equals(rdoTaxBlank) ||
					aComponent.equals(rdoTaxUnit))
			{
                                return target;
			}
			else if (aComponent.equals(termFrom))
			{
				return this.getSelectedTaxType();
			}
			else if (aComponent.equals(termTo))
			{
				return termFrom;
			}
			else if (aComponent.equals(calculationTo))
			{
				return termTo;
			}
			
                        return target;
		}

		/**
		 * トラバーサルサイクルの最初の Component を返します。
		 * このメソッドは、順方向のトラバーサルがラップするときに、次にフォーカスする Component を判定するために使用します。
		 * @param aContainer 先頭の Component を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @return aContainer のトラバーサルサイクルの先頭の Componet、または適切な Component が見つからない場合は null
		 */
		public Component getFirstComponent(Container aContainer)
		{
                        return target;
		}

		/**
		 * トラバーサルサイクルの最後の Component を返します。
		 * このメソッドは、逆方向のトラバーサルがラップするときに、次にフォーカスする Component を判定するために使用します。
		 * @param aContainer aContainer - 最後の Component を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @return aContainer のトラバーサルサイクルの最後の Componet、または適切な Component が見つからない場合は null
		 */
		public Component getLastComponent(Container aContainer)
		{
                        return calculationTo;
		}

		/**
		 * フォーカスを設定するデフォルトコンポーネントを返します。
		 * aContainer をルートとするフォーカストラバーサルサイクルが新しく開始されたときに、このコンポーネントに最初にフォーカスが設定されます。
		 * @param aContainer デフォルトの Component を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @return aContainer のトラバーサルサイクルのデフォルトの Componet、または適切な Component が見つからない場合は null
		 */
		public Component getDefaultComponent(Container aContainer)
		{
                        return calculationTo;
		}
		
		/**
		 * ウィンドウが最初に表示されたときにフォーカスが設定されるコンポーネントを返します。
		 * show() または setVisible(true) の呼び出しで一度ウィンドウが表示されると、
		 * 初期化コンポーネントはそれ以降使用されません。
		 * 一度別のウィンドウに移ったフォーカスが再び設定された場合、
		 * または、一度非表示状態になったウィンドウが再び表示された場合は、
		 * そのウィンドウの最後にフォーカスが設定されたコンポーネントがフォーカス所有者になります。
		 * このメソッドのデフォルト実装ではデフォルトコンポーネントを返します。
		 * @param window 初期コンポーネントが返されるウィンドウ
		 * @return 最初にウィンドウが表示されるときにフォーカス設定されるコンポーネント。適切なコンポーネントがない場合は null
		 */
		public Component getInitialComponent(Window window)
		{
                        return calculationTo;
		}
		
                /**
                 * 選択中の税区分を返します。
                 */
		private Component getSelectedTaxType()
		{
			if(rdoTaxUnit.isSelected())
			{
				return	rdoTaxUnit;
			}
			
			return	rdoTaxBlank;
		}
	}
}

