/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geobeck.sosia.pos.basicinfo.company;

import com.geobeck.sosia.pos.basicinfo.SimpleMaster;
import com.geobeck.sosia.pos.system.SystemInfo;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.text.*;

import com.geobeck.swing.*;
import com.geobeck.sosia.pos.master.*;
import com.geobeck.sosia.pos.swing.*;
import com.geobeck.sosia.pos.util.*;
import com.geobeck.util.CheckUtil;

/**
 *
 * @author Vo.Thanh.An
 */
public class MstSortStorePanelNons extends AbstractImagePanelEx {

    /**
     * Creates new form MstSortStorePanel
     */
    public MstSortStorePanelNons(String masterName,
                String tableName,
                String idColName,
                String nameColName,
                int nameLength,
                TableCellRenderer headerRenderer) 
    {
                super();
		this.init(masterName, tableName, idColName, nameColName, nameLength);
		initComponents();
		addMouseCursorChange();
		this.setSize(410, 500);
		SwingUtil.setJTableHeaderRenderer(datas, headerRenderer);
		this.setListener();
		this.refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        dataNameLabel = new javax.swing.JLabel();
        dataName = new com.geobeck.swing.JFormattedTextFieldEx();
        ((PlainDocument)dataName.getDocument()).setDocumentFilter(
            new CustomFilter(ms.getNameLength()));
        displaySeqLabel = new javax.swing.JLabel();
        displaySeq = new com.geobeck.swing.JFormattedTextFieldEx();
        ((PlainDocument)displaySeq.getDocument()).setDocumentFilter(
            new CustomFilter(4, CustomFilter.NUMERIC));
        renewButton = new javax.swing.JButton();
        datasScrollPane = new javax.swing.JScrollPane();
        datas = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(440, 441));

        closeButton.setIcon(SystemInfo.getImageIcon("/button/common/close_off.jpg"));
        closeButton.setBorderPainted(false);
        closeButton.setPressedIcon(SystemInfo.getImageIcon("/button/common/close_on.jpg"));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        dataNameLabel.setText("店舗名");

        dataName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        dataName.setColumns(ms.getNameLength());
        dataName.setInputKanji(true);

        displaySeqLabel.setText("挿入位置");

        displaySeq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        displaySeq.setColumns(4);
        displaySeq.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        renewButton.setIcon(SystemInfo.getImageIcon("/button/common/update_off.jpg"));
        renewButton.setBorderPainted(false);
        renewButton.setEnabled(false);
        renewButton.setPressedIcon(SystemInfo.getImageIcon("/button/common/update_on.jpg"));
        renewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renewButtonActionPerformed(evt);
            }
        });

        datasScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        datas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null}
            },
            new String []
            {
                "店舗名", "表示順"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        datas.setFocusTraversalPolicy(this.getFocusTraversalPolicy());
        datas.setSelectionBackground(new java.awt.Color(220, 220, 220));
        datas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        datas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        datas.getTableHeader().setReorderingAllowed(false);
        SwingUtil.setJTableHeaderRenderer(datas, SystemInfo.getTableHeaderRenderer());
        datas.setRowHeight(SystemInfo.TABLE_ROW_HEIGHT);
        this.initTableColumnWidth();
        SelectTableCellRenderer.setSelectTableCellRenderer(datas);
        datas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                datasMouseReleased(evt);
            }
        });
        datas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datasKeyReleased(evt);
            }
        });
        datasScrollPane.setViewportView(datas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datasScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 323, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(renewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(displaySeqLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(displaySeq, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNameLabel)
                    .addComponent(dataName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displaySeqLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displaySeq, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(renewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        ((JDialog)this.getParent().getParent().getParent().getParent()).setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void renewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renewButtonActionPerformed
        if(this.checkInput())
        {
            this.regist(false);
        }
    }//GEN-LAST:event_renewButtonActionPerformed

    private void datasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datasMouseReleased
        this.changeCurrentData();
    }//GEN-LAST:event_datasMouseReleased

    private void datasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datasKeyReleased
        this.changeCurrentData();
    }//GEN-LAST:event_datasKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private com.geobeck.swing.JFormattedTextFieldEx dataName;
    private javax.swing.JLabel dataNameLabel;
    private javax.swing.JTable datas;
    private javax.swing.JScrollPane datasScrollPane;
    private com.geobeck.swing.JFormattedTextFieldEx displaySeq;
    private javax.swing.JLabel displaySeqLabel;
    private javax.swing.JButton renewButton;
    // End of variables declaration//GEN-END:variables

    private MstSortStore                ms              =     null;
    private Integer			currentIndex	=	-1;
    
    private MstSortStoreFocusTraversalPolicy  ftp       = new MstSortStoreFocusTraversalPolicy();
    
    public MstSortStoreFocusTraversalPolicy getFocusTraversalPolicy()
        {
               return ftp;
                
        }
            
    
    private void addMouseCursorChange()
	{
		
		SystemInfo.addMouseCursorChange(renewButton);
		SystemInfo.addMouseCursorChange(closeButton);
	}
    
    private void setListener()
	{
		dataName.addKeyListener(SystemInfo.getMoveNextField());
		dataName.addFocusListener(SystemInfo.getSelectText());
		displaySeq.addKeyListener(SystemInfo.getMoveNextField());
		displaySeq.addFocusListener(SystemInfo.getSelectText());
	}
    private void init(String masterName,
						String tableName,
						String idColName,
						String nameColName,
						int	nameLength)
	{
		this.setTitle(masterName + "店舗");
		ms = new MstSortStore(masterName, tableName, idColName, nameColName, nameLength);
	}
    private void clear()
	{
		dataName.setText("");
		displaySeq.setText("");
		if(0 < datas.getRowCount())
				datas.removeRowSelectionInterval(0, datas.getRowCount() - 1);
		currentIndex = -1;
		this.changeCurrentData();
	}
    
    private void refresh()
	{
		//マスタをデータベースから読み込む
		ms.loadData();
		//テーブルにマスタデータを表示する
		this.showTableData();
		//入力をクリアする
		this.clear();
		
		dataName.requestFocusInWindow();
	}
    private void showTableData()
	{
		DefaultTableModel	model	=	(DefaultTableModel)datas.getModel();
		
		//全行削除
		model.setRowCount(0);
		datas.removeAll();
		
		for(MstStore md : ms)
		{
			Object[]	rowData	=	{	md.getName(), md.getDisplaySeq()	};
			model.addRow(rowData);
		}
	}
	
    private void changeCurrentData()
	{
		int	index	=	datas.getSelectedRow();
		
		if(0 <= index && index < ms.size() && currentIndex != index)
		{
			currentIndex	=	index;
			//選択されているデータを表示
			this.showCurrentData();
		}
		
		//データが選択されている場合、更新・削除ボタンを使用可能にする
		renewButton.setEnabled(0 <= currentIndex);
		
	}
    private void showCurrentData()
	{
		dataName.setText(ms.get(currentIndex).getName());
		displaySeq.setText(ms.get(currentIndex).getDisplaySeq().toString());
	}
    private boolean checkInput()
	{
		//名称
                if(dataName.getText().equals(""))
		{
			MessageDialog.showMessageDialog(this,
					MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY, ms.getMasterName() + "名"),
					this.getTitle(),
					JOptionPane.ERROR_MESSAGE);
			dataName.requestFocusInWindow();
			return	false;
		}

             
                if(displaySeq.getText().equals(""))
                    {
                        MessageDialog.showMessageDialog(this,
                                MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY, "挿入位置"),
                                this.getTitle(),
                                JOptionPane.ERROR_MESSAGE);
                        displaySeq.requestFocusInWindow();
                        return	false;
                    }
                else
                    {
                        if(!CheckUtil.isNumber(displaySeq.getText()))
                            {
                                MessageDialog.showMessageDialog(this,
                                        MessageUtil.getMessage(MessageUtil.ERROR_INPUT_WRONG, "挿入位置"),
                                        this.getTitle(),
                                        JOptionPane.ERROR_MESSAGE);
                                 displaySeq.requestFocusInWindow();
                                 return	false;
                            }
                    }
             return true;   
	}
 
     
    private void regist(boolean isInsert)
	{
		MstStore	temp	=	new MstStore();
		
		//行が選択されている場合、元のデータをセットする
		if(0 <= currentIndex)
		{
			temp.setID(ms.get(currentIndex).getID());
			temp.setName(ms.get(currentIndex).getName());
			temp.setDisplaySeq(ms.get(currentIndex).getDisplaySeq());
		}
		
		//入力されたデータをセット
		temp.setName(dataName.getText());
		temp.setDisplaySeq((displaySeq.getText().equals("") ? -1 : Integer.parseInt(displaySeq.getText())));
		
		//データを登録
		if(ms.regist(temp, (isInsert ? -1 : currentIndex)))
		{
			this.refresh();
		}
		else
		{
			MessageDialog.showMessageDialog(this,
					MessageUtil.getMessage(MessageUtil.ERROR_REGIST_FAILED,
							ms.getMasterName()),
					ms.getMasterName() + "店舗",
					JOptionPane.ERROR_MESSAGE);
		}
                
                
	} 
   
    private class MstSortStoreFocusTraversalPolicy
					extends FocusTraversalPolicy
	{
		/**
		 * aComponent のあとでフォーカスを受け取る Component を返します。
		 * aContainer は aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダでなければなりません。
		 * @param aContainer aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @param aComponent aContainer のおそらく間接的な子、または aContainer 自体
		 * @return aComponent のあとにフォーカスを受け取る Component。適切な Component が見つからない場合は null
		 */
		public Component getComponentAfter(Container aContainer,Component aComponent)
		{
			if (aComponent.equals(dataName))
			{
				return displaySeq;
			}
			else if (aComponent.equals(displaySeq))
			{
				return dataName;
			}
			
			return dataName;
		}

		/**
		 * aComponent の前にフォーカスを受け取る Component を返します。
		 * aContainer は aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダでなければなりません。
		 * @param aContainer aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @param aComponent aContainer のおそらく間接的な子、または aContainer 自体
		 * @return aComponent の前にフォーカスを受け取る Component。適切な Component が見つからない場合は null
		 */
		public Component getComponentBefore(Container aContainer,
											Component aComponent)
		{
			if (aComponent.equals(dataName))
			{
				return displaySeq;
			}
			else if (aComponent.equals(displaySeq))
			{
				return dataName;
			}
			
			return dataName;
		}

		/**
		 * トラバーサルサイクルの最初の Component を返します。
		 * このメソッドは、順方向のトラバーサルがラップするときに、次にフォーカスする Component を判定するために使用します。
		 * @param aContainer 先頭の Component を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @return aContainer のトラバーサルサイクルの先頭の Componet、または適切な Component が見つからない場合は null
		 */
		public Component getFirstComponent(Container aContainer)
		{
			return dataName;
		}

		/**
		 * トラバーサルサイクルの最後の Component を返します。
		 * このメソッドは、逆方向のトラバーサルがラップするときに、次にフォーカスする Component を判定するために使用します。
		 * @param aContainer aContainer - 最後の Component を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @return aContainer のトラバーサルサイクルの最後の Componet、または適切な Component が見つからない場合は null
		 */
		public Component getLastComponent(Container aContainer)
		{
			return displaySeq;
		}

		/**
		 * フォーカスを設定するデフォルトコンポーネントを返します。
		 * aContainer をルートとするフォーカストラバーサルサイクルが新しく開始されたときに、このコンポーネントに最初にフォーカスが設定されます。
		 * @param aContainer デフォルトの Component を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @return aContainer のトラバーサルサイクルのデフォルトの Componet、または適切な Component が見つからない場合は null
		 */
		public Component getDefaultComponent(Container aContainer)
		{
			return dataName;
		}
		
		/**
		 * ウィンドウが最初に表示されたときにフォーカスが設定されるコンポーネントを返します。
		 * show() または setVisible(true) の呼び出しで一度ウィンドウが表示されると、
		 * 初期化コンポーネントはそれ以降使用されません。
		 * 一度別のウィンドウに移ったフォーカスが再び設定された場合、
		 * または、一度非表示状態になったウィンドウが再び表示された場合は、
		 * そのウィンドウの最後にフォーカスが設定されたコンポーネントがフォーカス所有者になります。
		 * このメソッドのデフォルト実装ではデフォルトコンポーネントを返します。
		 * @param window 初期コンポーネントが返されるウィンドウ
		 * @return 最初にウィンドウが表示されるときにフォーカス設定されるコンポーネント。適切なコンポーネントがない場合は null
		 */
		public Component getInitialComponent(Window window)
		{
			return dataName;
		}
	}
    
    private void initTableColumnWidth()
	{
		//列の幅を設定する。
		datas.getColumnModel().getColumn(0).setPreferredWidth(240);
		datas.getColumnModel().getColumn(1).setPreferredWidth(50);
	}
    private class TableCellAlignRenderer extends DefaultTableCellRenderer
	{
		/** Creates a new instance of ReservationTableCellRenderer */
		public TableCellAlignRenderer()
		{
			super();
		}

		/**
		 * テーブルセルレンダリングを返します。
		 * @param table JTable
		 * @param value セルに割り当てる値
		 * @param isSelected セルが選択されている場合は true
		 * @param hasFocus フォーカスがある場合は true
		 * @param row 行
		 * @param column 列
		 * @return テーブルセルレンダリング
		 */
		public Component getTableCellRendererComponent(JTable table,
				Object value, boolean isSelected, boolean hasFocus, int row, int column)
		{
			super.getTableCellRendererComponent(table, value,
					isSelected, hasFocus, row, column);
			
			switch(column)
			{
				case 1:
					super.setHorizontalAlignment(SwingConstants.RIGHT);
					break;
				default:
					super.setHorizontalAlignment(SwingConstants.LEFT);
					break;
			}

			return this;
		}
	}
    
    
    
    
    
}
