/*
 * TimePanelBase.java
 *
 * Created on 2010/07/15, 11:45
 */

package com.geobeck.sosia.pos.basicinfo.company;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author geobeck
 */
public class TimePanelBase extends javax.swing.JPanel {
    
    private String fromTime;
    private String toTime;

    public JComboBox getFromHourCbo()
    {
        return fromHour;
    }

    public JComboBox getToHourCbo()
    {
        return toHour;
    }

    public String getFromTime()
    {
        if( fromHour.getSelectedIndex() <= 0 || toHour.getSelectedIndex() <= 0 ){
            // –¢Ý’è
            return "";
        }else{
            StringBuilder sb = new StringBuilder();
            sb.append(fromHour.getSelectedItem());
            return sb.toString();
        }
    }
    
    public void setFromTime(String time)
    {
        fromHour.setSelectedItem(time);
    }
        
    public String getToTime()
    {
        if( fromHour.getSelectedIndex() <= 0 || toHour.getSelectedIndex() <= 0 ){
            // –¢Ý’è
            return "";
        }else{
            StringBuilder sb = new StringBuilder();
            sb.append(toHour.getSelectedItem());
            return sb.toString();
        }
    }
    
    public void setToTime(String time)
    {
        toHour.setSelectedItem(time);
    }
    
    String[] hourData   = {"",
                           "00", "01", "02", "03", "04", "05", "06", "07", "08", "09",
                           "10", "11", "12", "13", "14", "15", "16", "17", "18", "19",
                           "20", "21", "22", "23", "24", "25", "26", "27", "28", "29",
                           "30", "31", "32", "33", "34", "35", "36" };
    
    /**
     * Creates new form TimePanelBase
     */
    public TimePanelBase() {
        initComponents();
        
        DefaultComboBoxModel fromModel = (DefaultComboBoxModel)fromHour.getModel();
        DefaultComboBoxModel toModel = (DefaultComboBoxModel)toHour.getModel();
        fromModel.addElement(new String());
        toModel.addElement(new String());
        for( int ii = 0; ii < 37; ii++ ){
            String str = String.format( "%02d", ii );
            fromModel.addElement(str);
            toModel.addElement(str);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        fromHour = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        toHour = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(200, 40));
        fromHour.setMaximumRowCount(20);
        fromHour.setOpaque(false);
        add(fromHour);
        fromHour.setBounds(10, 10, 50, 20);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("\u6642");
        add(jLabel3);
        jLabel3.setBounds(170, 10, 20, 20);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("\uff5e");
        add(jLabel5);
        jLabel5.setBounds(80, 10, 40, 20);

        toHour.setMaximumRowCount(20);
        toHour.setOpaque(false);
        add(toHour);
        toHour.setBounds(120, 10, 50, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("\u6642");
        add(jLabel1);
        jLabel1.setBounds(60, 10, 20, 20);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fromHour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox toHour;
    // End of variables declaration//GEN-END:variables
}
