/*
 * TimeStaffHelpPanel.java
 *
 * Created on 2016/08/22, 11:45
 */

package com.geobeck.sosia.pos.basicinfo.company;

import com.geobeck.sosia.pos.data.company.StaffWorkTime;
import com.geobeck.sosia.pos.system.SystemInfo;
import com.geobeck.sql.ResultSetWrapper;
import com.geobeck.util.SQLUtil;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;

/**
 *
 * @author lvtu
 */
public class TimeStaffHelpPanel extends javax.swing.JPanel {
    
    private String helpTime;
    private String workTime;

    
    /**
     * Creates new form TimeStaffHelpPanel
     * @param swt
     * @param dt
     */
    public TimeStaffHelpPanel(StaffWorkTime swt, Date dt) {
        initComponents();
        
        this.helpTime = swt.getScheduleTime();
        this.workTime = swt.getShiftTime();
        int countStaff = getCountStaffDetail(swt, dt);
        
        if(this.workTime.trim().equals("")) {
            this.lbWorkTime.setText(this.workTime.trim());
        }else {
            this.lbWorkTime.setText("(" + this.workTime + ")");
        }
        
        if(countStaff > 1) {
            this.lbHelpTime.setText(this.helpTime + "Å@ëº");
        }else {
            this.lbHelpTime.setText(this.helpTime);
        }
    }
    
    private Integer getCountStaffDetail(StaffWorkTime swt, Date dt) {
        try {
            String sql ="";
            sql +=" select count(*) as count_staff from data_schedule_detail a "
                    + " where a.delete_date is null and  a.staff_id = " + SQLUtil.convertForSQL(swt.getStaff().getStaffID())
                    + " AND a.schedule_date = " + SQLUtil.convertForSQL(dt)
                    + " AND a.shop_id = " + SQLUtil.convertForSQL(swt.getWorkingShopId());
                ResultSetWrapper rs = SystemInfo.getConnection().executeQuery(sql);
                if (rs.next())
                {
                    return rs.getInt("count_staff");
                }
                rs.close();
            } catch(SQLException e) {
                SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
            }
        return 0;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbWorkTime = new javax.swing.JLabel();
        lbHelpTime = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(200, 33));
        setLayout(null);

        lbWorkTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWorkTime.setText("lable");
        add(lbWorkTime);
        lbWorkTime.setBounds(0, 14, 110, 14);

        lbHelpTime.setForeground(java.awt.Color.blue);
        lbHelpTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHelpTime.setText("lable");
        add(lbHelpTime);
        lbHelpTime.setBounds(0, 0, 110, 14);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbHelpTime;
    private javax.swing.JLabel lbWorkTime;
    // End of variables declaration//GEN-END:variables
}
