/*
 * ShiftPanelBase.java
 *
 * Created on 2009/04/28, 16:27
 */

package com.geobeck.sosia.pos.basicinfo.company;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author  takeda
 */
public class ShiftPanelBase extends javax.swing.JPanel {
    
    /* hhmmÇSï∂éöÇ≈ç\ê¨Ç≥ÇÍÇÈéûä‘Çï\Ç∑ï∂éöóÒÇê›íËÇÈ */
    private String fromTime;
    private String toTime;

    public JComboBox getFromHourCbo()
    {
        return fromHour;
    }

    public JComboBox getFromMinuteCbo()
    {
        return fromMinute;
    }

    public JComboBox getToHourCbo()
    {
        return toHour;
    }

    public JComboBox getToMinuteCbo()
    {
        return toMinute;
    }
    
    public String getFromTime()
    {
        if( fromHour.getSelectedIndex() <= 0 || toHour.getSelectedIndex() <= 0 ){
            // ñ¢ê›íË
            return "";
        }else{
            StringBuilder sb = new StringBuilder();
            sb.append(fromHour.getSelectedItem());
            //IVS_Ptthu start edit 20160606 Bug #51059
            if(fromMinute.getSelectedItem().equals(""))
            {
                sb.append("00");
            }
            else
            {
                sb.append(fromMinute.getSelectedItem());
            }
            //IVS_Ptthu end edit 20160606 Bug #51059
            return sb.toString();
        }
    }
    
    public void setFromTime(String time)
    {
        if( time != null && time.length() == 4 ){
            String hour   = time.substring(0, 2);
            String minute = time.substring(2, 4);
            fromHour.setSelectedItem(hour);
            fromMinute.setSelectedItem(minute);
        }else{
            fromHour.setSelectedItem("");
            fromMinute.setSelectedItem("");
        }
    }
        
    public String getToTime()
    {
        if( fromHour.getSelectedIndex() <= 0 || toHour.getSelectedIndex() <= 0 ){
            // ñ¢ê›íË
            return "";
        }else{
            StringBuilder sb = new StringBuilder();
            sb.append(toHour.getSelectedItem());
            //IVS_Ptthu start edit 20160606 Bug #51059
            if(toMinute.getSelectedItem().equals(""))
            {
                sb.append("00");
            }
            else
            {
                sb.append(toMinute.getSelectedItem());
            }
            //IVS_Ptthu end edit 20160606 Bug #51059
            return sb.toString();
        }
    }
    
    public void setToTime(String time)
    {
        if( time != null && time.length() == 4 ){
            String hour   = time.substring(0, 2);
            String minute = time.substring(2, 4);
            toHour.setSelectedItem(hour);
            toMinute.setSelectedItem(minute);
        }else{
            toHour.setSelectedItem("");
            toMinute.setSelectedItem("");
        }
    }
    
    String[] hourData   = {"",
                           "00", "01", "02", "03", "04", "05", "06", "07", "08", "09",
                           "10", "11", "12", "13", "14", "15", "16", "17", "18", "19",
                           "20", "21", "22", "23", "24", "25", "26", "27", "28", "29",
                           "30", "31", "32", "33", "34", "35", "36" };
    String[] minuteData = {"", "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"};
    
    /**
     * Creates new form ShiftPanelBase
     */
    public ShiftPanelBase() {
        initComponents();
        
        DefaultComboBoxModel fromModel = (DefaultComboBoxModel)fromHour.getModel();
        DefaultComboBoxModel toModel = (DefaultComboBoxModel)toHour.getModel();
        fromModel.addElement(new String());
        toModel.addElement(new String());
        for( int ii = 0; ii < 37; ii++ ){
            String str = String.format( "%02d", ii );
            fromModel.addElement(str);
            toModel.addElement(str);
        }
        
        fromModel = (DefaultComboBoxModel)fromMinute.getModel();
        toModel = (DefaultComboBoxModel)toMinute.getModel();
        fromModel.addElement(new String());
        toModel.addElement(new String());
        for( int ii = 0; ii < 60; ii = ii + 5 ){
            String str = String.format( "%02d", ii );
            fromModel.addElement(str);
            toModel.addElement(str);
        }
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromHour = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        fromMinute = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        toHour = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        toMinute = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(268, 40));
        setLayout(null);

        fromHour.setMaximumRowCount(20);
        fromHour.setOpaque(false);
        add(fromHour);
        fromHour.setBounds(10, 10, 40, 20);

        jLabel3.setText("éû");
        add(jLabel3);
        jLabel3.setBounds(192, 10, 12, 20);

        fromMinute.setMaximumRowCount(20);
        fromMinute.setOpaque(false);
        add(fromMinute);
        fromMinute.setBounds(70, 10, 40, 20);

        jLabel4.setText("ï™");
        add(jLabel4);
        jLabel4.setBounds(252, 10, 12, 20);

        jLabel5.setText("Å`");
        add(jLabel5);
        jLabel5.setBounds(130, 10, 12, 20);

        toHour.setMaximumRowCount(20);
        toHour.setOpaque(false);
        add(toHour);
        toHour.setBounds(150, 10, 40, 20);

        jLabel1.setText("éû");
        add(jLabel1);
        jLabel1.setBounds(52, 10, 12, 20);

        toMinute.setMaximumRowCount(20);
        toMinute.setOpaque(false);
        add(toMinute);
        toMinute.setBounds(210, 10, 40, 20);

        jLabel2.setText("ï™");
        add(jLabel2);
        jLabel2.setBounds(112, 10, 12, 20);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fromHour;
    private javax.swing.JComboBox fromMinute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox toHour;
    private javax.swing.JComboBox toMinute;
    // End of variables declaration//GEN-END:variables
}
