/*
 * CollectBillPanel.java
 *
 * Created on 2006/10/18, 19:50
 */

package com.geobeck.sosia.pos.account;

import com.geobeck.sosia.pos.data.account.DataPaymentDetail;
import com.geobeck.sosia.pos.data.account.DataSalesDetail;
import com.geobeck.sosia.pos.master.company.MstStaff;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;

import com.geobeck.swing.*;
import com.geobeck.sosia.pos.master.account.*;
import com.geobeck.sosia.pos.master.company.MstShop;
import com.geobeck.sosia.pos.swing.*;
import com.geobeck.sosia.pos.util.*;
import com.geobeck.sosia.pos.system.*;
import com.geobeck.sql.ConnectionWrapper;
import com.geobeck.util.CheckUtil;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jp.co.flatsoft.fscomponent.*;

/**
 *
 * @author  katagiri
 */
public class CollectBillPanel extends com.geobeck.sosia.pos.swing.AbstractImagePanelEx
{
	/**
	 * 行の高さ
	 */
	private final int ROW_HEIGHT = 21;
	
	private	CollectBillFocusTraversalPolicy	ftp = new CollectBillFocusTraversalPolicy();
	protected CollectBill cb = new CollectBill();
        //IVS_LVTu start add 2015/07/29 New request #41101
        protected MstShop mstShop = new MstShop();
        //IVS_PTQUANG start add 2017/05/05 New Request #61615 [gb]売掛回収時にレシートを出力したい
        protected MstReceiptSetting mstReceiptSetting = null;
        private static String MESSAGE_COMFIRM_REPORT = "ご入金確認書を印刷しますか？";
        //IVS_PTQUANG  end add 2017/05/05 New Request #61615 [gb]売掛回収時にレシートを出力したい

        public MstShop getMstShop() {
            return mstShop;
        }

        public void setMstShop(MstShop mstShop) {
            this.mstShop = mstShop;
        }

        public CollectBill getCb() {
            return cb;
        }

        public void setCb(CollectBill cb) {
            this.cb = cb;
        }
        //IVS_LVTu end add 2015/07/29 New request #41101
	
        private BillsList bl = new BillsList();
        private Integer customerID=null;
	
	/** Creates new form CollectBillPanel */
	public CollectBillPanel()
	{
		super();
		initComponents();
		addMouseCursorChange();
		this.setSize(604, 700);//348
		this.setListener();
		this.setPath("精算管理");
		this.setTitle("売掛金回収");
               
	}
	
	public CollectBillPanel(Component opener)
	{
		this.setOpener(opener);
		initComponents();
		addMouseCursorChange();
		this.setSize(710, 700);//368
		this.setListener();
		this.setPath("精算管理");
		this.setTitle("売掛金回収");
                
                
	}
        public void init1(BillsList bl  )
	{
		this.showCollectedBillData(bl);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billValueLabel = new javax.swing.JLabel();
        slipNoLabel = new javax.swing.JLabel();
        slipNo = new com.geobeck.swing.JFormattedTextFieldEx();
        customerLabel = new javax.swing.JLabel();
        paymentDateLabel = new javax.swing.JLabel();
        registButton = new javax.swing.JButton();
        salesDateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        paymentsScrollPane = new javax.swing.JScrollPane();
        payments = new com.geobeck.swing.JTableEx();
        paymentDate = new FSCalenderCombo(SystemInfo.getSystemDate());
        billValue = new com.geobeck.swing.JFormattedTextFieldEx();
        salesDate = new jp.co.flatsoft.fscomponent.FSCalenderCombo();
        totalsScrollPane = new javax.swing.JScrollPane();
        totals = new javax.swing.JTable();
        customerName = new com.geobeck.swing.JFormattedTextFieldEx();
        customerNo = new com.geobeck.swing.JFormattedTextFieldEx();
        staff = new javax.swing.JComboBox();
        backButton = new javax.swing.JButton();
        slipNoLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        collects = new javax.swing.JTable();

        billValueLabel.setText("売掛金額");

        slipNoLabel.setText("伝票No.");

        slipNo.setEditable(false);
        slipNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        customerLabel.setText("顧客");

        paymentDateLabel.setText("回収日");

        registButton.setIcon(SystemInfo.getImageIcon("/button/common/regist_off.jpg"));
        registButton.setBorderPainted(false);
        registButton.setContentAreaFilled(false);
        registButton.setPressedIcon(SystemInfo.getImageIcon("/button/common/regist_on.jpg"));
        registButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registButtonActionPerformed(evt);
            }
        });

        salesDateLabel.setText("売上日");

        jLabel1.setText("確認者");

        paymentsScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        payments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "支払区分", "支払方法", "金額"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        payments.setSelectionBackground(new java.awt.Color(220, 220, 220));
        payments.setSelectionForeground(new java.awt.Color(0, 0, 0));
        JTableHeader paymentsHeader = payments.getTableHeader();
        paymentsHeader.setReorderingAllowed(false);
        paymentsHeader.setBackground(new Color(40, 60, 80));
        payments.setRowHeight(SystemInfo.TABLE_ROW_HEIGHT);
        SelectTableCellRenderer.setSelectTableCellRenderer(payments);
        payments.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentsFocusGained(evt);
            }
        });
        payments.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                paymentsPropertyChange(evt);
            }
        });
        payments.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paymentsKeyPressed(evt);
            }
        });
        paymentsScrollPane.setViewportView(payments);

        paymentDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        paymentDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentDateFocusLost(evt);
            }
        });

        billValue.setEditable(false);
        billValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        billValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        salesDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        salesDate.setEditable(false);

        totalsScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        totals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"現金支払",  new Long(0)},
                {"カード支払",  new Long(0)},
                {"信販支払",  new Long(0)},
                {"お釣り",  new Long(0)}
            },
            new String [] {
                "項目", "金額"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        totals.setSelectionBackground(new java.awt.Color(220, 220, 220));
        totals.setSelectionForeground(new java.awt.Color(0, 0, 0));
        totals.getTableHeader().setReorderingAllowed(false);
        SwingUtil.setJTableHeaderRenderer(totals, SystemInfo.getTableHeaderRenderer());
        totals.setRowHeight(SystemInfo.TABLE_ROW_HEIGHT);
        SelectTableCellRenderer.setSelectTableCellRenderer(totals);
        totalsScrollPane.setViewportView(totals);

        customerName.setEditable(false);
        customerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        customerNo.setEditable(false);
        customerNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        staff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffActionPerformed(evt);
            }
        });

        backButton.setIcon(SystemInfo.getImageIcon("/button/common/back_off.jpg"));
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setPressedIcon(SystemInfo.getImageIcon("/button/common/back_on.jpg"));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        slipNoLabel1.setText("支払履歴 ");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        collects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "回収日", "レジ担当", "回収金額", "売掛残"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        collects.setSelectionForeground(new java.awt.Color(0, 0, 0));
        collects.getTableHeader().setReorderingAllowed(false);
        collects.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        SwingUtil.setJTableHeaderRenderer(collects, SystemInfo.getTableHeaderRenderer());
        collects.setRowHeight(SystemInfo.TABLE_ROW_HEIGHT);
        SelectTableCellRenderer.setSelectTableCellRenderer(collects);
        jScrollPane1.setViewportView(collects);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(slipNoLabel)
                            .add(customerLabel)
                            .add(billValueLabel))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(slipNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(67, 67, 67)
                                .add(salesDateLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(salesDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(backButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(billValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(customerNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(customerName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 214, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(paymentDateLabel)
                        .add(18, 18, 18)
                        .add(paymentDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(48, 48, 48)
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(staff, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 202, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 275, Short.MAX_VALUE)
                        .add(registButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(paymentsScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(totalsScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 249, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(slipNoLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(salesDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(slipNoLabel)
                            .add(slipNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(salesDateLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(customerLabel)
                            .add(customerNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(customerName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(billValueLabel)
                            .add(billValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(backButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(paymentDateLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(paymentDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(staff, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(registButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(paymentsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .add(totalsScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .add(25, 25, 25)
                .add(slipNoLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void paymentsPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_paymentsPropertyChange
	{//GEN-HEADEREND:event_paymentsPropertyChange
		this.changePaymentValue();
	}//GEN-LAST:event_paymentsPropertyChange

	private void paymentDateFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_paymentDateFocusLost
	{//GEN-HEADEREND:event_paymentDateFocusLost
		this.changePaymentDate();
	}//GEN-LAST:event_paymentDateFocusLost

	private void staffActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_staffActionPerformed
	{//GEN-HEADEREND:event_staffActionPerformed
		this.changeStaff();
	}//GEN-LAST:event_staffActionPerformed

	private void registButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registButtonActionPerformed
	{//GEN-HEADEREND:event_registButtonActionPerformed

            //IVS_TMTrong start add 2015/08/31 Bug #42352
            //if( payments.getCellEditor() != null ) payments.getCellEditor().stopCellEditing();
            if(payments.isEditing())
            {
                 payments.getCellEditor().stopCellEditing();
            }
             changePaymentValue();
            //IVS_TMTrong end add 2015/08/31 Bug #42352
            if (this.checkInput()) {
                //IVS_PTQUANG start add 2017/05/05 New Request #61615 [gb]売掛回収時にレシートを出力したい
                boolean checkData = loadMstReceiptSetting();
                boolean comfirmMessage = comfirmMessageDialog();
                if (checkData == true && comfirmMessage == true)
                {
                    try {
                        this.regist();
                        // Print Report
                        printMstReceiptSetting();
                    } catch (Exception ex) {
                        Logger.getLogger(CollectBillPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                    this.regist();
                }
                //IVS_PTQUANG end add 2017/05/05 New Request #61615 [gb]売掛回収時にレシートを出力したい
            }
	}//GEN-LAST:event_registButtonActionPerformed

		//IVS_PTQUANG start add 2017/05/05 New Request #61615 [gb]売掛回収時にレシートを出力したい
        /**
         * 
         * @return 
         */
        private boolean loadMstReceiptSetting() {
            // check exists shop_id in mst_receipt_setting
            boolean checkExists = false;
            if (mstReceiptSetting == null) {
                mstReceiptSetting = new MstReceiptSetting();
                try {
                    ConnectionWrapper con = SystemInfo.getConnection();
                    mstReceiptSetting.setShop(mstShop);
                    checkExists = mstReceiptSetting.isExists(con);
                } catch(SQLException sqlex) {
                    Logger.getLogger(CollectBillPanel.class.getName()).log(Level.SEVERE, null, sqlex);
                }
                catch(NullPointerException nullex) {
                    Logger.getLogger(CollectBillPanel.class.getName()).log(Level.SEVERE, null, nullex);
                }
                catch(Exception ex) {
                    Logger.getLogger(CollectBillPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            return checkExists;
        }

        /**
         *
         */
        private boolean comfirmMessageDialog(){
            int flag = 0;
            int result = MessageDialog.showYesNoDialog(this,
                    MESSAGE_COMFIRM_REPORT,
                    this.getTitle(),
                    JOptionPane.QUESTION_MESSAGE,
                    JOptionPane.YES_OPTION);
            return flag == result;
        }

        /**
         *
         */
        public void printMstReceiptSetting() throws Exception {
            PrintReceipt pr = new PrintReceipt();
            if (!pr.canPrint()) {
                return;
            }
            if (!(pr.getReceiptSetting().getReceiptSize().equals(2))) {
               printReceiptGeneral(pr);
            }
        }

        /**
         * 
         * @param pr
         * @throws Exception 
         */
        private void printReceiptGeneral(PrintReceipt pr) throws Exception {
            // set value Customer
            pr.setCustomer(cb.getSales().getCustomer());
            // set value for 大元の伝票No
            pr.setSlipNo(cb.getSales().getSlipNo());
            // set value for 大元の売上日
            pr.setSalesDate(cb.getSales().getSalesDate());
            // set value for 売掛回収日
            pr.setPaymentDate(paymentDate.getDate());
            // set value for 売掛回収確認者
            pr.setStaff(((MstStaff)staff.getSelectedItem()));
            // set value for 回収前の残高
            pr.setTotalAmount(cb.getTotal(0).value);
            // set value for 回収金額
            pr.setOutOfValue(getPaymentDetails());
            // set value for お釣り
            pr.setPrevAmount(cb.getTotal(5).getValue() > 0 ? cb.getTotal(5).getValue() : 0);
            // set value for 売掛回収後の残高
            pr.setUseAmount(cb.getTotal(5).getValue() < 0 ? Math.abs(cb.getTotal(5).getValue()):0);
            //
            pr.setCashValue(cb.getPayment().get(0).getPaymentValue());
            //
            pr.setCardTitle(payments.getValueAt(1, 0).toString());
            pr.setCardValue(cb.getTotal(2).getValue());
            //
            pr.seteCashTitle(payments.getValueAt(2, 0).toString());
            pr.setECashValue(cb.getTotal(3).getValue());
            //
            pr.setGiftTitle(payments.getValueAt(3, 0).toString());
            pr.setGiftValue(cb.getTotal(4).getValue());
            pr.add(new ReceiptData());

        	switch (pr.getReceiptSetting().getReceiptSize()) {
            	case 0:
               		pr.setReceiptType(PrintReceipt.ReceiptType.LARGE);
                	break;
            	case 1:
                	pr.setReceiptType(PrintReceipt.ReceiptType.NORMAL);
                	break;
        	}
        	pr.print(true);
    	}

    /**
     *
     * @return 
     */
    private Long getPaymentDetails() {
        return cb.getTotal(1).getValue().longValue() + cb.getTotal(2).getValue().longValue() + cb.getTotal(3).getValue().longValue() + cb.getTotal(4).getValue().longValue();
    }
	//IVS_PTQUANG end add 2017/05/05 New Request #61615 [gb]売掛回収時にレシートを出力したい

    private void paymentsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentsKeyPressed
        if(payments.getSelectedRow() == payments.getRowCount() - 1 &&
            payments.getSelectedColumn() == 2 &&
            evt.getKeyCode() == evt.VK_ENTER)
        {
            if(registButton.isVisible())
            {
                registButton.requestFocusInWindow();
                payments.setColumnSelectionAllowed( false );
                payments.setRowSelectionAllowed( false );
            }
        }
    }//GEN-LAST:event_paymentsKeyPressed

    private void paymentsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentsFocusGained
        payments.getInputContext().setCharacterSubsets(null);
    }//GEN-LAST:event_paymentsFocusGained

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.showOpener();
    }//GEN-LAST:event_backButtonActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private com.geobeck.swing.JFormattedTextFieldEx billValue;
    private javax.swing.JLabel billValueLabel;
    private javax.swing.JTable collects;
    private javax.swing.JLabel customerLabel;
    private com.geobeck.swing.JFormattedTextFieldEx customerName;
    private com.geobeck.swing.JFormattedTextFieldEx customerNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected jp.co.flatsoft.fscomponent.FSCalenderCombo paymentDate;
    private javax.swing.JLabel paymentDateLabel;
    private com.geobeck.swing.JTableEx payments;
    private javax.swing.JScrollPane paymentsScrollPane;
    private javax.swing.JButton registButton;
    private jp.co.flatsoft.fscomponent.FSCalenderCombo salesDate;
    private javax.swing.JLabel salesDateLabel;
    private com.geobeck.swing.JFormattedTextFieldEx slipNo;
    private javax.swing.JLabel slipNoLabel;
    private javax.swing.JLabel slipNoLabel1;
    protected javax.swing.JComboBox staff;
    private javax.swing.JTable totals;
    private javax.swing.JScrollPane totalsScrollPane;
    // End of variables declaration//GEN-END:variables
	
	/**
	 * ボタンにマウスカーソルが乗ったときにカーソルを変更するイベントを追加する。
	 */
	private void addMouseCursorChange()
	{
		SystemInfo.addMouseCursorChange(backButton);
		SystemInfo.addMouseCursorChange(registButton);
	}
	
	/**
	 * 売掛回収画面用FocusTraversalPolicyを取得する。
	 * @return 売掛回収画面用FocusTraversalPolicy
	 */
	public CollectBillFocusTraversalPolicy getFocusTraversalPolicy()
	{
		return	ftp;
	}
	
	/**
	 * コンポーネントの各リスナーをセットする。
	 */
	private void setListener()
	{
		paymentDate.addKeyListener(SystemInfo.getMoveNextField());
		paymentDate.addFocusListener(SystemInfo.getSelectText());
		staff.addKeyListener(SystemInfo.getMoveNextField());
	}
	
	/**
	 * 初期化処理を行う。
	 * @param slipNo 伝票No.
	 */
	public void init(Integer slipNo)
	{
		cb.init(slipNo);
		this.initStaff();
		this.initPayments();
		this.initTotal();
		this.showData();
	}
	
	/**
	 * レジ担当者を初期化する。
	 */
	private void initStaff()
	{
		for(MstStaff ms : cb.getStaffs())
		{
			staff.addItem(ms);
		}
		
		staff.setSelectedIndex(0);
	}
	
	
	/**
	 * データを表示する。
	 */
	private void showData()
	{
		slipNo.setText(cb.getSales().getSlipNo().toString());
		salesDate.setDate(cb.getSales().getSalesDate());
		customerNo.setText(cb.getSales().getCustomer().getCustomerNo());
		customerName.setText(cb.getSales().getCustomer().getFullCustomerName());
		billValue.setText(FormatUtil.decimalFormat(cb.getBillValue()));
                
	}
        /**
	 * 回収済売掛金データを表示する。
	 */
	private void showCollectedBillData(BillsList bl)
	{
            
	    SwingUtil.clearTable(collects);
	    DefaultTableModel model = (DefaultTableModel)collects.getModel();
            int customerID1=cb.getSales().getCustomer().getCustomerID();
            int slipNo1=cb.getSales().getSlipNo();
	    for(CollectedBillData cbd : bl.getCollectedBills()) {
                int customerID2=cbd.getCustomer().getCustomerID();
                int slipNo2 = cbd.getSlipNo();
		///if((customerID1==customerID2) && (slipNo1==slipNo2))
                if(customerID1==customerID2)
                {
                    Object[] rowData = { String.format("%1$tY/%1$tm/%1$td", cbd.getPaymentDate()),
					cbd.getStaff().getFullStaffName(),
					cbd.getCollectedValue(),
					cbd.getBillValue() };
                    model.addRow(rowData);
                }
	    }
	}
	
	/**
	 * 支払データを初期化する。
	 */
	private void initPayments()
	{
		payments.setModel(new PaymentTableModel(SystemInfo.getPaymentClasses()));
		TableColumnModel model = payments.getColumnModel();
		model.getColumn(2).setCellEditor(new LongCellEditor(new JTextField()));
		SwingUtil.setJTableHeaderRenderer(payments, SystemInfo.getTableHeaderRenderer());
		this.initPaymentCells();
		this.addNewPaymentRow(true);
	}
	
	/**
	 * 支払データのセルを初期化する。
	 */
	private void initPaymentCells()
	{
		SwingUtil.clearTable(payments);
		
		PaymentTableModel	model	=	(PaymentTableModel)payments.getModel();
		
		for(MstPaymentClass mpc : SystemInfo.getPaymentClasses())
		{
			JComboBox	classes	=	new JComboBox(
					new Object[]{	mpc	});
			classes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
			
			Object		methods	=	this.getPaymentMethodObject(mpc);
			
			Object[]	rowData	=	{	mpc,
										methods,
										0l	};
			model.addRow(rowData);
			
            //IVS_LVTU start edit 2017/05/09 Bug #13457 [gb]売掛回収画面の不備
//			cb.getPayment().addPaymentDetail(mpc,
//					(0 == mpc.size() ? null : mpc.get(0)),
//					0l);
                    cb.getPayment().addPaymentDetail(mpc,
                            (1 == mpc.size() ? mpc.get(0) : null),
                            0l);
            //IVS_LVTU end edit 2017/05/09 Bug #13457 [gb]売掛回収画面の不備
		}
	}
	
	/**
	 * 支払データに新規行を追加する。
	 */
	private void addNewPaymentRow(boolean isAddData)
	{
		JComboBox	classes	=	new JComboBox();
		classes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
		Object		methods	=	null;
		MstPaymentClass mpc	=	null;
		
		for(MstPaymentClass temp : SystemInfo.getPaymentClasses())
		{
			//現金以外の場合、Itemに追加
			if(temp.getPaymentClassID() != 1)
					classes.addItem(temp.getPaymentClassName());
			
			//1つめのデータの場合、対応する支払方法のJComboBoxを作成
			if(classes.getItemCount() == 1)
			{
				mpc	=	temp;
				methods	=	this.getPaymentMethodObject(temp);
			}
		}
		
		//支払区分が変更されたときの処理を追加
		classes.addActionListener(new java.awt.event.ActionListener()
		{
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
				paymentActionPerformed(evt);
			}
		});
		
		PaymentTableModel	model	=	(PaymentTableModel)payments.getModel();
		
		model.addRow(new Object[]{	classes,
										methods,
										0l	});
		
		if(isAddData)
		{
            //IVS_LVTU start edit 2017/05/09 Bug #13457 [gb]売掛回収画面の不備
//			cb.getPayment().addPaymentDetail(mpc,
//					(0 == mpc.size() ? null : mpc.get(0)),
//					0l);
                    cb.getPayment().addPaymentDetail(mpc,
                            (1 == mpc.size() ? mpc.get(0) : null),
                            0l);
            //IVS_LVTU end edit 2017/05/09 Bug #13457 [gb]売掛回収画面の不備
		}
	}
	
	private class PaymentTableModel extends DefaultTableModel
	{
		MstPaymentClasses mpcs	=	null;
		
		/**
		 * コンストラクタ
		 * @param mpcs 
		 */
		public PaymentTableModel(MstPaymentClasses mpcs)
		{
			super(new String[]{"支払区分", "支払方法", "金額"}, 0);
			this.mpcs = mpcs;
			if(this.mpcs == null)
					this.mpcs	=	new MstPaymentClasses();
		}
		
		/**
		 * 列のクラスを取得
		 * @param col 列
		 * @return 
		 */
		public Class getColumnClass(int col)
		{
			if(col < 0)	return	null;
			return	this.getValueAt(0, col).getClass();
		}
		
		/**
		 * セルのデータが変更可能かを取得する。
		 * @param row 行
		 * @param col 列
		 * @return true - 変更可能
		 */
		public boolean isCellEditable(int row, int col)
		{
			//支払区分固定行の場合
			if(col == 0 && row < mpcs.size())
			{
				return	false;
			}
			//現金以外の場合
			if(col == 1 && this.getValueAt(row, col).getClass().getName().equals("java.lang.String"))
			{
				return	false;
			}
			
			return	true;
		}
	}
	
	
	/**
	 * 支払データが変更されたときの処理を行う。
	 * @param evt 
	 */
	public void paymentActionPerformed(java.awt.event.ActionEvent evt)
	{
		int			row		=	payments.getSelectedRow();
		int			col		=	payments.getSelectedColumn();
		
		MstPaymentClass		mpc		=	null;
		MstPaymentMethod	mpm		=	null;
		
		//支払区分固定行の場合
		if(0 <= row && row < SystemInfo.getPaymentClasses().size())
		{
			mpc	=	SystemInfo.getPaymentClasses().get(row);
		}
		else
		{
			JComboBox	mpccb	=	(JComboBox)payments.getValueAt(row, 0);
			mpccb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
			int			index	=	mpccb.getSelectedIndex() + 1;
			
			if(0 < index && index <= SystemInfo.getPaymentClasses().size())
			{
				mpc	=	SystemInfo.getPaymentClasses().get(index);
			}
		}
		
		switch(col)
		{
			//支払区分
			case 0:
				if(mpc != null)
				{
					Object	methods	=	this.getPaymentMethodObject(mpc);
					
					payments.setValueAt(methods, row, 1);
                    //IVS_LVTU start add 2017/05/09 Bug #13457 [gb]売掛回収画面の不備
                    if (mpc.size() == 1) {
                    	mpm = mpc.get(0);
                    }
                    //IVS_LVTU end add 2017/05/09 Bug #13457 [gb]売掛回収画面の不備
				}
				break;
			//支払方法
			case 1:
				if(mpc != null && mpc.size() != 0)
				{
					if(mpc.size() == 1)
					{
						mpm	=	mpc.get(0);
					}
					else
					{
						JComboBox	mpccb	=	(JComboBox)payments.getValueAt(row, 1);
						mpccb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
						int			index	=	mpccb.getSelectedIndex() - 1;
						
						if(0 <= index && index < mpc.size())
						{
							mpm	=	mpc.get(index);
						}
					}
				}
				
				break;
		}
		
		Long	value	=	(Long)payments.getValueAt(row, 2);
		
		cb.getPayment().setPaymentDetail(row, mpc, mpm, value);
		
		this.setTotal();
	}
	
	/**
	 * 支払方法のセルにセットするオブジェクトを取得する。
	 * @param mpc 支払区分
	 * @return 支払方法のセルにセットするオブジェクト
	 */
	private Object getPaymentMethodObject(MstPaymentClass mpc)
	{
		Object	methods	=	null;
		
		if(mpc.size() == 0)
		{
			methods	=	"";
		}
		else if(mpc.size() == 1)
		{
			methods	=	mpc.get(0).getPaymentMethodName();
		}
		else
		{
			methods	=	new JComboBox();
			((JComboBox)methods).setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
			((JComboBox)methods).addItem(new MstPaymentMethod());
			for(MstPaymentMethod mpm : mpc)
			{
				((JComboBox)methods).addItem(mpm.getPaymentMethodName());
			}
			
			//支払方法が変更されたときの処理を追加
			((JComboBox)methods).addActionListener(new java.awt.event.ActionListener()
			{
				public void actionPerformed(java.awt.event.ActionEvent evt)
				{
					paymentActionPerformed(evt);
				}
			});
		}
		
		return	methods;
	}
	
	
	/**
	 * 合計を初期化する。
	 */
	private void initTotal()
	{
		DefaultTableModel	model	=	(DefaultTableModel)totals.getModel();
		
		//全行削除
		model.setRowCount(0);
		totals.removeAll();
		
		for(NameValue nv : cb.getTotal())
		{
			model.addRow(new Object[]{	nv.getName(),
											0l	});
		}
		
		this.setTotal();
	}
	
	/**
	 * 合計をセットする。
	 */
	private void setTotal()
	{
		cb.setTotal();
		
		int	row	=	0;
		
		for(NameValue nv : cb.getTotal())
		{
			totals.setValueAt(nv.value, row, 1);
			row	++;
		}
	}
	
	/**
	 * 回収日が変更されたときの処理を行う。
	 */
	private void changePaymentDate()
	{
		cb.getPayment().setPaymentDate(paymentDate.getDate());
	}
	
	/**
	 * スタッフが変更されたときの処理を行う。
	 */
	private void changeStaff()
	{
		cb.getPayment().setStaff((MstStaff)staff.getSelectedItem());
		payments.requestFocusInWindow();
		payments.setColumnSelectionInterval( 2, 2 );
		payments.setRowSelectionInterval( 0, 0 );
	}
	
	/**
	 * 支払金額が変更されたときの処理を行う。
	 */
	private void changePaymentValue()
	{
		int	row		=	payments.getSelectedRow();
		int	col		=	payments.getSelectedColumn();
		
		if(row < 0 || col < 0)	return;
		
		//支払金額の列の場合
                //IVS_TMTrong start add 2015/08/31 Bug #42352
                for( int i = 0;i<payments.getModel().getRowCount();i++) {
                //IVS_TMTrong end add 2015/08/31 Bug #42352
                    row = i;
		if(col == 2)
		{
			Long	value	=	(Long)payments.getValueAt(row, col);
                       
			if(value == null)
			{
				payments.setValueAt(0l, row, col);
				value	=	0l;
			}
			
			if(0 < value && row == payments.getRowCount() - 1)
			{
				this.addNewPaymentRow(true);
			}
                        
                       
			//if(cb.getPayment().size()>0)
                        //{
                            DataPaymentDetail	dpd	=	cb.getPayment().get(row);
			
                            if(dpd != null)	dpd.setPaymentValue(value);
                        //}
		}
                }
		this.setTotal();
	}
	
	/**
	 * 入力チェックを行う。
	 * @return true - ＯＫ
	 */
	private boolean checkInput()
	{
		if(paymentDate.getDate() == null)
		{
			MessageDialog.showMessageDialog(this,
					MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY,
					"回収日"),
					this.getTitle(),
					JOptionPane.ERROR_MESSAGE);
			paymentDate.requestFocusInWindow();
			return	false;
		}
		
		GregorianCalendar	today	=	new GregorianCalendar();
		today.set(today.HOUR, 0);
		today.set(today.MINUTE, 0);
		today.set(today.SECOND, 0);
		today.set(today.MILLISECOND, 0);
		
		if(paymentDate.getDate().getTime() < salesDate.getDate().getTime() ||
				today.getTimeInMillis() < paymentDate.getDate().getTime())
		{
			MessageDialog.showMessageDialog(this,
					MessageUtil.getMessage(MessageUtil.ERROR_INPUT_WRONG,
					"回収日"),
					this.getTitle(),
					JOptionPane.ERROR_MESSAGE);
			paymentDate.requestFocusInWindow();
			return	false;
		}
		
		//確認者
		if(staff.getSelectedIndex() == 0)
		{
			MessageDialog.showMessageDialog(this,
					MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY,
					"確認者"),
					this.getTitle(),
					JOptionPane.ERROR_MESSAGE);
			staff.requestFocusInWindow();
			return	false;
		}

		//支払金額
		Long	temp	=	0l;
		for(int i = 1; i < cb.getTotal().size() - 1; i ++)
		{
			temp	+=	cb.getTotal(i).getValue();
		}
		if(temp <= 0)
		{
			MessageDialog.showMessageDialog(this,
					MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY,
					"支払金額"),
					this.getTitle(),
					JOptionPane.ERROR_MESSAGE);
			payments.requestFocusInWindow();
			return	false;
		}
                //IVS_TMTrong start add 2015/08/28 Bug #42352
                Long cardAndECashAmount = 0l;
                Long cardAmount = (Long)totals.getValueAt(2, 1);
                Long ECashAmount = (Long)totals.getValueAt(3, 1);
                cardAndECashAmount = cardAmount + ECashAmount;
                
                //temp	-=	cb.getTotal(1).getValue();
                //if(cb.getBillValue() < temp)
                if(cb.getBillValue() < cardAndECashAmount)
                //IVS_TMTrong end add 2015/08/28 Bug #42352
		{
			MessageDialog.showMessageDialog(this,
					MessageUtil.getMessage(3100),
					this.getTitle(),
					JOptionPane.ERROR_MESSAGE);
			payments.requestFocusInWindow();
			return	false;

                    }

            //IVS_LVTU start add 2017/05/09 Bug #13457 [gb]売掛回収画面の不備
            for (DataPaymentDetail dpd : cb.getPayment()) {
                if (dpd.getPaymentValue() != null && 0 < dpd.getPaymentValue()) {
                    if (dpd.getPaymentMethod() == null
                            || dpd.getPaymentMethod().getPaymentMethodID() == null) {
                        MessageDialog.showMessageDialog(this,
                                MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY, "支払方法"),
                                this.getTitle(),
                                JOptionPane.ERROR_MESSAGE);
                        return false;
                    }

                    if (dpd.getPaymentMethod().getPaymentClassID() == null) {
                        MessageDialog.showMessageDialog(this,
                                MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY, "支払区分"),
                                this.getTitle(),
                                JOptionPane.ERROR_MESSAGE);
                        return false;
                    }
                }
            }
            //IVS_LVTU end add 2017/05/09 Bug #13457 [gb]売掛回収画面の不備

		return	true;
	}
	
	/**
	 * 登録処理を行う。
	 */
	protected void regist()
	{
		//IVS_LVTu start edit 2015/07/29 New request #41101
                if ( this.getMstShop().getShopID() == null ) {
		cb.getPayment().setShop(SystemInfo.getCurrentShop());
                } else {
                    cb.getPayment().setShop(this.getMstShop());
                }
                //IVS_LVTu end edit 2015/07/29 New request #41101
		cb.getPayment().setPaymentDate(paymentDate.getDate());
		cb.getPayment().setStaff((MstStaff)staff.getSelectedItem());
		
		if(cb.regist())
		{
			if(this.getOpener() instanceof BillsListPanel)
			{
				BillsListPanel	blp	=	(BillsListPanel)this.getOpener();
				blp.init();
			}
			else if(this.getOpener() instanceof InputAccountPanel)
			{
				InputAccountPanel	iap	=	(InputAccountPanel)this.getOpener();
				iap.setBill();
			}
			
			this.showOpener();
		}
		else
		{
			
		}
	}
	
	
	/**
	 * 売掛回収画面用FocusTraversalPolicy
	 */
	private class CollectBillFocusTraversalPolicy
					extends FocusTraversalPolicy
	{
		/**
		 * aComponent のあとでフォーカスを受け取る Component を返します。
		 * aContainer は aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダでなければなりません。
		 * @param aContainer aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @param aComponent aContainer のおそらく間接的な子、または aContainer 自体
		 * @return aComponent のあとにフォーカスを受け取る Component。適切な Component が見つからない場合は null
		 */
		public Component getComponentAfter(Container aContainer,
										   Component aComponent)
		{
			if (aComponent.equals(slipNo))
			{
				return paymentDate;
			}
			else if (aComponent.equals(salesDate))
			{
				return paymentDate;
			}
			else if (aComponent.equals(customerNo))
			{
				return paymentDate;
			}
			else if (aComponent.equals(customerName))
			{
				return paymentDate;
			}
			else if (aComponent.equals(billValue))
			{
				return paymentDate;
			}
			else if (aComponent.equals(paymentDate))
			{
				return staff;
			}
			else if (aComponent.equals(staff))
			{
				return payments;
			}
			
			return slipNo;
		}

		/**
		 * aComponent の前にフォーカスを受け取る Component を返します。
		 * aContainer は aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダでなければなりません。
		 * @param aContainer aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @param aComponent aContainer のおそらく間接的な子、または aContainer 自体
		 * @return aComponent の前にフォーカスを受け取る Component。適切な Component が見つからない場合は null
		 */
		public Component getComponentBefore(Container aContainer,
											Component aComponent)
		{
			if (aComponent.equals(slipNo))
			{
				return slipNo;
			}
			else if (aComponent.equals(slipNo))
			{
				return slipNo;
			}
			else if (aComponent.equals(customerNo))
			{
				return slipNo;
			}
			else if (aComponent.equals(customerName))
			{
				return slipNo;
			}
			else if (aComponent.equals(billValue))
			{
				return slipNo;
			}
			else if (aComponent.equals(paymentDate))
			{
				return slipNo;
			}
			else if (aComponent.equals(staff))
			{
				return paymentDate;
			}
			
			return slipNo;
		}

		/**
		 * トラバーサルサイクルの最初の Component を返します。
		 * このメソッドは、順方向のトラバーサルがラップするときに、次にフォーカスする Component を判定するために使用します。
		 * @param aContainer 先頭の Component を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @return aContainer のトラバーサルサイクルの先頭の Componet、または適切な Component が見つからない場合は null
		 */
		public Component getFirstComponent(Container aContainer)
		{
			return slipNo;
		}

		/**
		 * トラバーサルサイクルの最後の Component を返します。
		 * このメソッドは、逆方向のトラバーサルがラップするときに、次にフォーカスする Component を判定するために使用します。
		 * @param aContainer aContainer - 最後の Component を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @return aContainer のトラバーサルサイクルの最後の Componet、または適切な Component が見つからない場合は null
		 */
		public Component getLastComponent(Container aContainer)
		{
			return payments;
		}

		/**
		 * フォーカスを設定するデフォルトコンポーネントを返します。
		 * aContainer をルートとするフォーカストラバーサルサイクルが新しく開始されたときに、このコンポーネントに最初にフォーカスが設定されます。
		 * @param aContainer デフォルトの Component を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
		 * @return aContainer のトラバーサルサイクルのデフォルトの Componet、または適切な Component が見つからない場合は null
		 */
		public Component getDefaultComponent(Container aContainer)
		{
			return slipNo;
		}
		
		/**
		 * ウィンドウが最初に表示されたときにフォーカスが設定されるコンポーネントを返します。
		 * show() または setVisible(true) の呼び出しで一度ウィンドウが表示されると、
		 * 初期化コンポーネントはそれ以降使用されません。
		 * 一度別のウィンドウに移ったフォーカスが再び設定された場合、
		 * または、一度非表示状態になったウィンドウが再び表示された場合は、
		 * そのウィンドウの最後にフォーカスが設定されたコンポーネントがフォーカス所有者になります。
		 * このメソッドのデフォルト実装ではデフォルトコンポーネントを返します。
		 * @param window 初期コンポーネントが返されるウィンドウ
		 * @return 最初にウィンドウが表示されるときにフォーカス設定されるコンポーネント。適切なコンポーネントがない場合は null
		 */
		public Component getInitialComponent(Window window)
		{
			return slipNo;
		}
	}
}
