/*
 * MainStaffForSettingBusiness.java
 *
 * Created on 2014/07/07, 09:00
 */
package com.geobeck.sosia.pos.hair.basicinfo.product;

import com.geobeck.sosia.pos.hair.account.HairInputAccount;
import com.geobeck.sosia.pos.hair.data.account.DataSalesMainstaff;
import com.geobeck.sosia.pos.hair.data.reservation.DataReservationMainstaff;
import com.geobeck.sosia.pos.hair.reservation.RegistReservation;
import com.geobeck.sosia.pos.system.SystemInfo;
import java.awt.*;
import java.util.logging.*;
import javax.swing.*;
import com.geobeck.swing.*;
import com.geobeck.sosia.pos.master.company.*;
import com.geobeck.sosia.pos.swing.SelectTableCellRenderer;
import com.geobeck.sosia.pos.util.*;
import com.geobeck.sql.ConnectionWrapper;
import com.geobeck.sql.ResultSetWrapper;
import com.geobeck.util.SQLUtil;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.text.PlainDocument;


/**
 *
 * @author DHThanh
 */
public class MainStaffForSettingBusiness extends com.geobeck.sosia.pos.swing.AbstractImagePanelEx {              
        MstShopRelations arrMsRelation = new MstShopRelations();
        private MstShop shop = new MstShop();
        public ArrayList<DataReservationMainstaff> arrDataReservationMainstaff = new ArrayList<DataReservationMainstaff>();
        public ArrayList<DataSalesMainstaff> saleMainstaff = new ArrayList<DataSalesMainstaff>();
        public ArrayList<DataSalesMainstaff> lastSaleMainstaffs = new ArrayList<DataSalesMainstaff>();
        Integer customerID = 0;
        public boolean flgSave = false;
    
    
    /**
     * called from 予約登録画面 vs お会計
     * @param shop the current shop
     * @param customerID the customer code
     * @param drm the data reservation main staff list
     * @author IVS_Thanh
     * @since 20140715
     */  
    public MainStaffForSettingBusiness(MstShop shop, Integer customerID, ArrayList<DataReservationMainstaff> drm, Boolean tempSave) {
        initComponents();
        this.setSize(480, 490);
        this.setTitle("業態主担当設定");
        this.shop = shop; 
        this.customerID = customerID;
        this.arrDataReservationMainstaff = drm;
         if (this.arrDataReservationMainstaff.size() > 0 && tempSave) {
            initDataTemp();
        }
        else
        {
            initData();
        }
              
    } 
    //nhanvt start add 20150128 New request #35057
    /**
     * 
     * @param customerId
     * @param shopId 
     */
    public MainStaffForSettingBusiness(Integer customerId,Integer shopId) {
        
       this.customerID = customerId;
       this.shop = new MstShop();
       this.shop.setShopID(shopId);
    } 
    //nhanvt end add 20150128 New request #35057
    /**
     * called from 予約登録画面 to init data
     * @param the current shop
     * @param rr a information about reservation
     * @author IVS_Thanh
     * @since 20140715
     */
    public MainStaffForSettingBusiness(MstShop shop, RegistReservation rr) {
        initComponents();
        this.setSize(480, 490);
        this.setTitle("業態主担当設定");
        this.shop = shop; 
        this.customerID = rr.getCustomer().getCustomerID();
        this.arrDataReservationMainstaff = rr.getReservationMainstaffs();
        if (rr.isTempSave()) {
            initDataTemp();
        }
        else
        {
            initDataReservation(rr.getReservation().getReservationNo()); 
        }               
    }  
    
    /**
     * called from お会計 to init data
     * @param shop the current shop
     * @param ia a information about order
     * @author IVS_Thanh
     * @since 20140715
     */
    public MainStaffForSettingBusiness(MstShop shop, HairInputAccount ia) {
        initComponents();
        this.setSize(480, 490);
        this.setTitle("業態主担当設定");
        this.shop = shop; 
        this.customerID = ia.getSales().getCustomer().getCustomerID();
        this.arrDataReservationMainstaff = ia.getReservationMainstaffs();
        if (ia.isTempSave()) {
            initDataTemp();
        }
        else
        {
            if (ia.getSales().getSlipNo()!=null && ia.getSales().getSlipNo() > 0) {
                initDataSale(ia.getSales().getSlipNo());
            }
            else
            {
                 initDataReservation(ia.reservationNo);

            }
        }
       
               
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchResultScrollPane = new javax.swing.JScrollPane();
        searchResult = new com.geobeck.swing.JTableEx();
        registButton2 = new javax.swing.JButton();

        setFocusCycleRoot(true);

        searchResultScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        searchResultScrollPane.setFocusable(false);

        searchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "業態名", "スタッフNO", "スタッフ", "指名", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchResult.setSelectionBackground(new java.awt.Color(255, 210, 142));
        searchResult.setSelectionForeground(new java.awt.Color(0, 0, 0));
        searchResult.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        searchResult.getTableHeader().setReorderingAllowed(false);
        SwingUtil.setJTableHeaderRenderer(searchResult, SystemInfo.getTableHeaderRenderer());
        searchResult.setRowHeight(SystemInfo.TABLE_ROW_HEIGHT);
        this.initTableColumnWidth();
        SelectTableCellRenderer.setSelectTableCellRenderer(searchResult);
        JFormattedTextFieldEx staffNoTextFiled = new com.geobeck.swing.JFormattedTextFieldEx();
        ((PlainDocument)staffNoTextFiled.getDocument()).setDocumentFilter(
            new CustomFilter(10, CustomFilter.ALPHAMERIC));
        TableColumnModel model = searchResult.getColumnModel();
        model.getColumn(1).setCellEditor(new StringCellEditor(staffNoTextFiled));
        searchResult.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchResultFocusLost(evt);
            }
        });
        searchResult.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                searchResultPropertyChange(evt);
            }
        });
        searchResultScrollPane.setViewportView(searchResult);
        searchResult.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        searchResult.getColumnModel().getColumn(4).setMinWidth(0);
        searchResult.getColumnModel().getColumn(4).setPreferredWidth(0);
        searchResult.getColumnModel().getColumn(4).setMaxWidth(0);

        registButton2.setIcon(SystemInfo.getImageIcon("/button/common/regist_off.jpg"));
        registButton2.setBorderPainted(false);
        registButton2.setPressedIcon(SystemInfo.getImageIcon("/button/common/regist_off.jpg"));
        registButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(searchResultScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(registButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(registButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(searchResultScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registButton2ActionPerformed
        registButton2.setCursor(null);        
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if (searchResult.getCellEditor() != null) {
                searchResult.getCellEditor().stopCellEditing();
            }
            ArrayList<DataReservationMainstaff> reservationMainstaff = new ArrayList<DataReservationMainstaff>();
            //arrDataReservationMainstaff.clear();            
            for (int i = 0; i < searchResult.getRowCount(); i++) {
                DataReservationMainstaff drm = new DataReservationMainstaff();
                MstShopRelation msr = (MstShopRelation)searchResult.getValueAt(i, 4);
                drm.setShopCategoryId(msr.getShopCategoryId());     
                JComboBox staffCombo = (JComboBox)searchResult.getValueAt(i, 2);
                drm.setStaff((MstStaff) staffCombo.getSelectedItem());
                drm.setDesignated((Boolean) searchResult.getValueAt(i, 3));
                boolean flag = false;
                flag = (Boolean) searchResult.getValueAt(i, 3);                
                if ((flag == true)&&(((MstStaff)staffCombo.getSelectedItem()).getStaffID() == null)){
                    MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(MessageUtil.REGIST_WARNING_MESSAGE, "業態主担当設定"),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
                    return;                    
               }
                if (((MstStaff)staffCombo.getSelectedItem()).getStaffID() == null) {
                    continue;
                }
                reservationMainstaff.add(drm); 
                //arrDataReservationMainstaff.add(drm); 
            }
            flgSave = true;
            arrDataReservationMainstaff = reservationMainstaff;
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(MessageUtil.INFO_REGIST_SUCCESS, "業態主担当設定"),
                    this.getTitle(),
                    JOptionPane.INFORMATION_MESSAGE);
            // Close 業態主担当設定画面
            ((JDialog) this.getParent().getParent().getParent().getParent()).setVisible(false);            
        }
        catch(Exception ex)
        {
            arrDataReservationMainstaff.clear();
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(MessageUtil.ERROR_REGIST_FAILED, "業態主担当設定"),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
        }
        finally {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_registButton2ActionPerformed

    private void searchResultPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_searchResultPropertyChange
        setStaffNo();
    }//GEN-LAST:event_searchResultPropertyChange

    private void searchResultFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchResultFocusLost
        setStaffNo();
    }//GEN-LAST:event_searchResultFocusLost
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton registButton2;
    private com.geobeck.swing.JTableEx searchResult;
    private javax.swing.JScrollPane searchResultScrollPane;
    // End of variables declaration//GEN-END:variables

    /**
     * init data for grid
     * @author IVS_Thanh
     * @since 20140715
     */
    private void initData() {
        
        ConnectionWrapper con = SystemInfo.getConnection();
        try {
            arrMsRelation.clear();
            arrMsRelation.loadByShop(con,shop.getShopID());   
            if (customerID!= null && customerID > 0) {
                loadLastSalesMainStaffByShopCategoryID();
            }
        } catch (SQLException e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        }
        showData();
    }
    
    /**
     * init temp data for grid
     * @author IVS_Thanh
     * @since 20140715
     */
    private void initDataTemp() {
        
        ConnectionWrapper con = SystemInfo.getConnection();
        try {
            arrMsRelation.clear();
            arrMsRelation.loadByShop(con,shop.getShopID());               
            SwingUtil.clearTable(searchResult);
            DefaultTableModel model = (DefaultTableModel) searchResult.getModel();
            for (MstShopRelation msr : arrMsRelation) {
                DataReservationMainstaff ms = getStaffByShopCategoryId(msr.getShopCategoryId());
                Object[] rowData = {
                    msr.getShopClassName(),
                    getStaffComboBox(ms.getStaff().getStaffID(),msr.getShopCategoryId()).getSelectedIndex() == 0 ? "" : ms.getStaff().getStaffNo(),
                    getStaffComboBox(ms.getStaff().getStaffID(),msr.getShopCategoryId()),
                    getStaffComboBox(ms.getStaff().getStaffID(),msr.getShopCategoryId()).getSelectedIndex() == 0 ? false :ms.getDesignated(),
                    msr
                };
                model.addRow(rowData);
            }
        } catch (SQLException e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        }        
    }
    
    /**
     * Load data reservation main staff by reservationNo          
     * @param reservationNo the reservation number Code     
     * @author IVS_Thanh
     * @since 20140715
     */
    private void initDataReservation(Integer reservationNo) {          
        ResultSetWrapper rs;
            try {
            //コネクションを取得
            ConnectionWrapper con = SystemInfo.getConnection();
            StringBuilder sql = new StringBuilder(1000);
            sql.append(" select \n");
            sql.append("     drm.shop_id,drm.designated_flag,drm.staff_id,staff_no,msc.shop_category_id,msc.shop_class_name \n");          
            sql.append(" from \n");
            sql.append("    mst_shop_category msc \n");
            sql.append("    inner join mst_shop_relation msr on msc.shop_category_id = msr.shop_category_id \n");
            sql.append("    left join  data_reservation_mainstaff drm on msr.shop_category_id = drm.shop_category_id  \n");
            sql.append("    and msr.shop_id = drm.shop_id  \n");
            sql.append("     and drm.reservation_no = " + SQLUtil.convertForSQL(reservationNo));
            sql.append("    left join mst_staff ms using(staff_id) \n");            
            sql.append(" where \n");
            sql.append("     drm.delete_date is null \n");   
            sql.append("     and msc.delete_date is null \n");  
            sql.append("     and msr.shop_id = " + SQLUtil.convertForSQL(shop.getShopID()));
            sql.append(" order by \n");
            sql.append("      msc.display_seq \n");  
            //前回の伝票NOを取得
            rs = con.executeQuery(sql.toString());
            boolean flag = false;
            SwingUtil.clearTable(searchResult);
            DefaultTableModel model = (DefaultTableModel) searchResult.getModel();
            while (rs.next()) {
                flag = true;
                MstShopRelation msr = new MstShopRelation();
                msr.setShopClassName(rs.getString("shop_class_name"));
                MstStaff ms = new MstStaff();
                ms.setStaffID(rs.getInt("staff_id"));
                ms.setStaffNo(rs.getString("staff_no"));
                msr.setShopCategoryId(rs.getInt("shop_category_id"));                
                Object[] rowData = {
                    msr.getShopClassName(),
                    getStaffComboBox(ms.getStaffID(),msr.getShopCategoryId()).getSelectedIndex() == 0 ? "" : ms.getStaffNo(),
                    getStaffComboBox(ms.getStaffID(),msr.getShopCategoryId()),
                    getStaffComboBox(ms.getStaffID(),msr.getShopCategoryId()).getSelectedIndex() == 0 ? false : rs.getBoolean("designated_flag"),
                    msr
                };
                model.addRow(rowData);
            } 
            rs.close();
//            if (!flag) {
//                initData();
//            }
            } catch (Exception e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        }
    }
    
    /**
     * Load data sale main staff by slipNO          
     * @param slipNO the order number 
     * @author IVS_Thanh
     * @since 20140715
     */
    private void initDataSale(Integer slipNo) {        
        ResultSetWrapper rs;
            try {
            //コネクションを取得
            ConnectionWrapper con = SystemInfo.getConnection();
            StringBuilder sql = new StringBuilder(1000);
            sql.append(" select \n");               
            sql.append("     dsm.shop_id,dsm.designated_flag,dsm.staff_id,staff_no,msc.shop_category_id,msc.shop_class_name \n");
            sql.append(" from \n");
            sql.append("    mst_shop_category msc \n");
            sql.append("    inner join mst_shop_relation msr on msc.shop_category_id = msr.shop_category_id \n");            
            sql.append("    left join  data_sales_mainstaff dsm on msr.shop_category_id = dsm.shop_category_id  \n");
            sql.append("    and msr.shop_id = dsm.shop_id  \n");
             sql.append("     and dsm.slip_no = " + SQLUtil.convertForSQL(slipNo));
            sql.append("    left join mst_staff ms using(staff_id) \n");
            sql.append(" where \n");
            sql.append("     dsm.delete_date is null \n");  
            sql.append("     and msc.delete_date is null \n");
            sql.append("     and msr.shop_id = " + SQLUtil.convertForSQL(shop.getShopID()));
            sql.append(" order by \n");
            sql.append("      msc.display_seq \n");  
            //前回の伝票NOを取得
            rs = con.executeQuery(sql.toString());
            boolean flag = false;
            SwingUtil.clearTable(searchResult);
            DefaultTableModel model = (DefaultTableModel) searchResult.getModel();
            while (rs.next()) {
                flag = true;
                MstShopRelation msr = new MstShopRelation();
                msr.setShopClassName(rs.getString("shop_class_name"));
                MstStaff ms = new MstStaff();
                ms.setStaffID(rs.getInt("staff_id"));
                ms.setStaffNo(rs.getString("staff_no"));
                msr.setShopCategoryId(rs.getInt("shop_category_id"));                
                Object[] rowData = {
                    msr.getShopClassName(),
                    getStaffComboBox(ms.getStaffID(),msr.getShopCategoryId()).getSelectedIndex() == 0 ? "" : ms.getStaffNo(),
                    getStaffComboBox(ms.getStaffID(),msr.getShopCategoryId()),
                    getStaffComboBox(ms.getStaffID(),msr.getShopCategoryId()).getSelectedIndex() == 0 ? false : rs.getBoolean("designated_flag"),
                    msr
                };
                model.addRow(rowData);
            } 
            rs.close();
//            if (!flag) {
//               initData();
//            }
        } catch (Exception e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        }
    }
    
    private void initTableColumnWidth() {
        //列の幅を設定する。
        searchResult.getColumnModel().getColumn(0).setPreferredWidth(100);
        searchResult.getColumnModel().getColumn(1).setPreferredWidth(40);
        searchResult.getColumnModel().getColumn(2).setPreferredWidth(100);
        searchResult.getColumnModel().getColumn(3).setPreferredWidth(40);
    }
    
    /**
     * show data for grid         
     * @return data for grid
     * @author IVS_Thanh
     * @since 20140715
     */
     private void showData() {
        SwingUtil.clearTable(searchResult);
        DefaultTableModel model = (DefaultTableModel) searchResult.getModel();
        for (MstShopRelation msr : arrMsRelation) {
            DataSalesMainstaff ms = getStaffIDByShopCategoryId(msr.getShopCategoryId());
            Object[] rowData = {
                msr.getShopClassName(),
                getStaffComboBox(ms.getStaff().getStaffID(),msr.getShopCategoryId()).getSelectedIndex() == 0 ? "" : ms.getStaff().getStaffNo(),
                getStaffComboBox(ms.getStaff().getStaffID(),msr.getShopCategoryId()),
                getStaffComboBox(ms.getStaff().getStaffID(),msr.getShopCategoryId()).getSelectedIndex() == 0 ? false : ms.getDesignated(),
                msr
            };
            model.addRow(rowData);
        }

    }
   
    /**
     * get Data sales main staff by shopCategoryId
     * @param shopCategoryId
     * @return an DataSalesMainstaff object
     * @author IVS_Thanh
     * @since 20140715
     */ 
    private DataSalesMainstaff getStaffIDByShopCategoryId(Integer shopCategoryId)
    {
        for (int i = 0; i < lastSaleMainstaffs.size(); i++) {
            if (lastSaleMainstaffs.get(i).getShopCategoryId() == shopCategoryId) {
                //return lastSaleMainstaffs.get(i).getStaff().getStaffID();
                return lastSaleMainstaffs.get(i);
            }
        }
        return new DataSalesMainstaff();
    }
    
    private DataReservationMainstaff getStaffByShopCategoryId(Integer shopCategoryId)
    {
        for (int i = 0; i < arrDataReservationMainstaff.size(); i++) {
            if (arrDataReservationMainstaff.get(i).getShopCategoryId() == shopCategoryId) {
                //return lastSaleMainstaffs.get(i).getStaff().getStaffID();
                return arrDataReservationMainstaff.get(i);
            }
        }
        return new DataReservationMainstaff();
    }
    
    /**
     * Load last sales by customerID
     * @author IVS_Thanh
     * @since 20140715
     */
    public void loadLastSalesMainStaffByShopCategoryID()
    {
            ResultSetWrapper rs;
            try {
            //コネクションを取得
            ConnectionWrapper con = SystemInfo.getConnection();
            StringBuilder sql = new StringBuilder(1000);
            sql.append(" select \n");
            sql.append("      dsm.*,ms.staff_no \n");          
            sql.append(" from \n");
            sql.append("     data_sales as ds \n");
            sql.append("    inner join data_sales_mainstaff dsm using(shop_id,slip_no) \n");
            sql.append("    left join mst_staff ms on ms.staff_id = dsm.staff_id \n");
            sql.append(" where \n");
            sql.append("         ds.delete_date is null \n");
            sql.append("     and dsm.delete_date is null \n");
            sql.append("     and ds.sales_date is not null \n");
            sql.append("     and ds.customer_id = " + SQLUtil.convertForSQL(customerID));
            sql.append("     and ds.shop_id = " + SQLUtil.convertForSQL(shop.getShopID()));
            //sql.append(" and slip_no = (select slip_no from data_sales ds1 inner join data_sales_mainstaff using(shop_id,slip_no) where sales_date is not null and ds1.delete_date \n");
            //sql.append(" is null and shop_id = ds.shop_id and customer_id = ds.customer_id  \n");
            sql.append(" and slip_no = (select max(slip_no) from data_sales where sales_date is not null and delete_date \n");
            sql.append(" is null and shop_id = ds.shop_id and customer_id = ds.customer_id ) \n");
            sql.append(" order by \n");
            sql.append("      ds.sales_date desc \n");
            sql.append("     ,ds.slip_no desc \n");
            //sql.append(" limit 1");
            
            //前回の伝票NOを取得
            rs = con.executeQuery(sql.toString());            
            while (rs.next()) {
                DataSalesMainstaff dsm = new DataSalesMainstaff();
                dsm.setData(rs);
                this.lastSaleMainstaffs.add(dsm);
            }
            rs.close();
            } catch (Exception e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        }
            
    }
     
    /**
     * スタッフ選択用JComboBoxを取得する。
     *
     * @param staffID 選択状態にするスタッフＩＤ
     * @return スタッフ選択用JComboBox
     */
    private JComboBox getStaffComboBox(Integer staffID, Integer shopCategoryID) {
        JComboBox staffCombo = new JComboBox();
        try {
         ConnectionWrapper con = SystemInfo.getConnection();        
        staffCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        staffCombo.addItem(new MstStaff());
        MstStaff.addRelationStaffDataToJComboBox(con,staffCombo,shopCategoryID,shop.getShopID());
        staffCombo.setSelectedIndex(0);

        this.setStaff(staffCombo, staffID);

        staffCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (searchResult.getSelectedColumn() == 2) {
                   changeStaff();
                }
            }
        });

               
        } catch (SQLException e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        }
       return staffCombo;    
        
    } 
    
    /**
     * get value currentdata row
     * @return Object a value of current row
     * @author IVS_Thanh
     * @since 20140715
     */
    private Object getCurrentCellObject() {
        return searchResult.getValueAt(searchResult.getSelectedRow(),
                searchResult.getSelectedColumn());
    }
    
    /**
     * set staff No when change combobox 
     * @author IVS_Thanh
     * @since 20140715
     */
    private void changeStaff() {        
        JComboBox staffCombo = (JComboBox) this.getCurrentCellObject();
        MstStaff ms = (MstStaff) staffCombo.getSelectedItem();
        searchResult.setValueAt(ms.getStaffNo(), searchResult.getSelectedRow(), 1);
    }
    
    /**
     * 指定したスタッフＩＤをスタッフ選択用JComboBoxで選択状態にする。
     *
     * @param staffCombo スタッフ選択用JComboBox
     * @param staffNo スタッフNo
     */
    private JComboBox setStaff(JComboBox staffCombo, String staffNo) {

        for (int i = 0; i < staffCombo.getItemCount(); i++) {

            MstStaff ms = (MstStaff) staffCombo.getItemAt(i);

            //空白をセット
            if (ms.getStaffID() == null) {

                staffCombo.setSelectedIndex(0);

            } else if (ms.getStaffNo().equals(staffNo)) {

                staffCombo.setSelectedIndex(i);
                return staffCombo;
            }
        }
        return staffCombo;
    }
    
    /**
     * 指定したスタッフＩＤをスタッフ選択用JComboBoxで選択状態にする。
     *
     * @param staffCombo スタッフ選択用JComboBox
     * @param staffID スタッフＩＤ
     */
    private void setStaff(JComboBox staffCombo, Integer staffID) {

        for (int i = 0; i < staffCombo.getItemCount(); i++) {

            MstStaff ms = (MstStaff) staffCombo.getItemAt(i);

            //空白をセット
            if (ms.getStaffID() == null) {

                staffCombo.setSelectedIndex(0);

            } else if (ms.getStaffID().equals(staffID)) {

                staffCombo.setSelectedIndex(i);
                return;
            }
        }
    }
    
    /**
     * set staff for staff combobox and staffNo field
     * @author IVS_Thanh
     * @since 20140715
     */
    private void setStaffNo() {
         int col = searchResult.getSelectedColumn();
         int row = searchResult.getSelectedRow();
         if (row < 0 || col < 0) {
            return;
         }
         if (col == 1) {
             String StaffNo = searchResult.getValueAt(row, col).toString();
             if (!StaffNo.equals(""))
             {
                 JComboBox staffCombo = (JComboBox)searchResult.getValueAt(row, 2);
                 this.setStaff(staffCombo, StaffNo);                 
                 if (staffCombo.getSelectedIndex() == 0) {
                     searchResult.setValueAt("", row, col);
                     searchResult.setValueAt(staffCombo, row, 2);
                     return;
                 }
                 searchResult.setValueAt(staffCombo, row, 2);  
             }
             else
             {
                 JComboBox staffCombo = (JComboBox)searchResult.getValueAt(row, 2);
                 staffCombo.setSelectedIndex(0);
                 searchResult.setValueAt(staffCombo, row, 2);                 
             }
         }
    }
}
