
/*
 * DataMonthlyBatchPanel.java
 *
 * Created on 2018/03/16, 10:58
 */
package com.geobeck.sosia.pos.hair.basicinfo.product;

import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;
import java.sql.*;
import java.util.logging.*;

import com.geobeck.sql.*;
import com.geobeck.swing.*;
import com.geobeck.util.*;
import com.geobeck.sosia.pos.util.*;
import com.geobeck.sosia.pos.swing.*;
import com.geobeck.sosia.pos.system.SystemInfo;
import com.geobeck.sosia.pos.data.account.DataPayment;
import com.geobeck.sosia.pos.data.account.DataPaymentDetail;
import com.geobeck.sosia.pos.hair.customer.MstCustomerPanel;
import com.geobeck.sosia.pos.hair.data.account.Course;
import com.geobeck.sosia.pos.hair.data.account.DataSales;
import com.geobeck.sosia.pos.hair.data.account.DataSalesDetail;
import com.geobeck.sosia.pos.hair.data.course.DataContract;
import com.geobeck.sosia.pos.hair.data.member.DataMonthlyBatchDetailLog;
import com.geobeck.sosia.pos.hair.data.member.DataMonthlyBatchLog;
import com.geobeck.sosia.pos.hair.report.util.JExcelApi;
import com.geobeck.sosia.pos.master.account.MstAccountSetting;
import com.geobeck.sosia.pos.master.account.MstPaymentClass;
import com.geobeck.sosia.pos.master.account.MstPaymentClasses;
import com.geobeck.sosia.pos.master.account.MstPaymentMethod;
import com.geobeck.sosia.pos.master.company.MstShop;
import com.geobeck.sosia.pos.master.company.MstStaff;
import com.geobeck.sosia.pos.master.company.MstStaffs;
import com.geobeck.sosia.pos.products.Product;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.border.BevelBorder;

/**
 *
 * @author lvtu
 */
public class DataMonthlyBatchPanel extends com.geobeck.sosia.pos.swing.AbstractImagePanelEx {

    private final int COL_BUTTON_CUSTOMER           = 1;
   
    private final int COL_CHECK                     = 10;
    /**
     * 売掛金コード
     */
    private final int CODE_ACCOUNTS_RECEIVABLE      = 999;
    /**
     * 売掛金
     */
    private final String NAME_ACCOUNTS_RECEIVABLE   = "売掛金";

    private MstPaymentClasses mp = new MstPaymentClasses();
    private ArrayList<DataMonthlyBatchLog> dataBatch = new ArrayList<DataMonthlyBatchLog>();
    private DataMonthlyBatchLog batch = new DataMonthlyBatchLog();
    /**
     * スタッフリスト
     */
    protected MstStaffs staffs = null;

    /**
     * Creates new form DataMonthlyBatchPanel
     */
    public DataMonthlyBatchPanel() {
        super();
        initComponents();
        addMouseCursorChange();
        this.setSize(900, 670);
        this.setPath("基本設定＞月会員管理");
        this.setTitle("一括処理");
        this.setListener();
        if (SystemInfo.getCurrentShop().getShopID() == 0) {
            cmbShop.addItem(new MstShop());
        }
        SystemInfo.initGroupShopComponents(cmbShop, 2);
        this.init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        praiseTimeLimitGroup = new javax.swing.ButtonGroup();
        btnOutputExcel = new javax.swing.JButton();
        TargetMonthLabel = new javax.swing.JLabel();
        cmbPayment = new JComboBox();
        batchButton = new javax.swing.JButton();
        shopLabel = new javax.swing.JLabel();
        extractionButton = new javax.swing.JButton();
        technicsScrollPane = new javax.swing.JScrollPane();
        dataMemberTable = new com.geobeck.swing.JTableEx();
        cmbShop = new com.geobeck.sosia.pos.swing.JComboBoxLabel();
        dayLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        checkProcessed = new javax.swing.JCheckBox();
        checkUntreated = new javax.swing.JCheckBox();
        paymentLabel = new javax.swing.JLabel();
        processDate = new jp.co.flatsoft.fscomponent.FSCalenderCombo();
        yeaLabel = new javax.swing.JLabel();
        monthLable = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox();
        cmbYear = new javax.swing.JComboBox();
        cmbStaff = new javax.swing.JComboBox();
        staffLable = new javax.swing.JLabel();

        setFocusCycleRoot(true);

        btnOutputExcel.setIcon(SystemInfo.getImageIcon("/button/print/excel_off.jpg"));
        btnOutputExcel.setBorderPainted(false);
        btnOutputExcel.setEnabled(false);
        btnOutputExcel.setPressedIcon(SystemInfo.getImageIcon("/button/print/excel_on.jpg"));
        btnOutputExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutputExcelActionPerformed(evt);
            }
        });

        TargetMonthLabel.setText("対象月");

        cmbPayment.setMaximumRowCount(12);
        cmbPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        batchButton.setIcon(SystemInfo.getImageIcon("/button/master/batch_off.jpg"));
        batchButton.setBorderPainted(false);
        batchButton.setEnabled(false);
        batchButton.setPressedIcon(SystemInfo.getImageIcon("/button/master/batch_on.jpg"));
        batchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchButtonActionPerformed(evt);
            }
        });

        shopLabel.setText("店舗名");

        extractionButton.setIcon(SystemInfo.getImageIcon("/button/master/extraction_off.jpg"));
        extractionButton.setBorderPainted(false);
        extractionButton.setPressedIcon(SystemInfo.getImageIcon("/button/master/extraction_on.jpg"));
        extractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractionButtonActionPerformed(evt);
            }
        });

        technicsScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dataMemberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "入会店舗", "顧客", "顧客No", "顧客名", "入会日", "契約プラン", "金額", "消化回数", "処理日", "処理区分", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataMemberTable.setSelectionBackground(new java.awt.Color(220, 220, 220));
        dataMemberTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        dataMemberTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        dataMemberTable.getTableHeader().setReorderingAllowed(false);
        SwingUtil.setJTableHeaderRenderer(dataMemberTable, SystemInfo.getTableHeaderRenderer());
        dataMemberTable.getColumnModel().getColumn(this.COL_CHECK).setHeaderRenderer(this.getTableHeaderRenderer(dataMemberTable.getTableHeader()));
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( SwingConstants.CENTER );
        dataMemberTable.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
        dataMemberTable.getColumnModel().getColumn(8).setCellRenderer( centerRenderer );
        dataMemberTable.getColumnModel().getColumn(9).setCellRenderer( centerRenderer );
        dataMemberTable.setRowHeight(SystemInfo.TABLE_ROW_HEIGHT);
        this.initTableColumnWidth();
        SelectTableCellRenderer.setSelectTableCellRenderer(dataMemberTable);
        dataMemberTable.setSelectionBackground(new java.awt.Color(255, 210, 142));
        technicsScrollPane.setViewportView(dataMemberTable);

        dayLabel.setText("処理日");

        statusLabel.setText("処理区分");

        checkProcessed.setText("処理済み");
        checkProcessed.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkProcessed.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkProcessed.setOpaque(false);

        checkUntreated.setText("未処理");
        checkUntreated.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkUntreated.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkUntreated.setOpaque(false);

        paymentLabel.setText("支払方法");

        processDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        processDate.setForeground(java.awt.Color.white);
        processDate.setDate(SystemInfo.getCurrentShop().getSystemDate().getTime());
        processDate.setMaximumSize(new java.awt.Dimension(65, 20));
        processDate.setMinimumSize(new java.awt.Dimension(65, 20));
        processDate.setPreferredSize(new java.awt.Dimension(85, 20));

        yeaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yeaLabel.setText("年");

        monthLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthLable.setText("月");

        cmbMonth.setMaximumRowCount(13);
        cmbMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        cmbYear.setMaximumRowCount(12);
        cmbYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        cmbStaff.setMaximumRowCount(20);
        cmbStaff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        staffLable.setText("レジ担当");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(TargetMonthLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .add(shopLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cmbShop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54)
                .add(statusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(checkUntreated, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(checkProcessed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(520, 520, 520)
                .add(extractionButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnOutputExcel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(batchButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(technicsScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 820, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(paymentLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cmbPayment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(dayLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(cmbYear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(yeaLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, 0)
                                .add(cmbMonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, 0)
                                .add(monthLable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(processDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(staffLable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cmbStaff, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(shopLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cmbShop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(statusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(checkUntreated, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(checkProcessed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(TargetMonthLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(2, 2, 2)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(yeaLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(monthLable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(cmbYear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cmbMonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(dayLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(processDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(staffLable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cmbStaff, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(paymentLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cmbPayment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(extractionButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnOutputExcel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(batchButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(technicsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void batchButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_batchButtonActionPerformed
	{//GEN-HEADEREND:event_batchButtonActionPerformed
            if (this.checkInput()) {
                if (MessageDialog.showYesNoDialog(
                        this,
                        "一括処理を行うと取消できません。\n処理を開始してよろしいですか？",
                        this.getTitle(),
                        JOptionPane.WARNING_MESSAGE,
                        JOptionPane.NO_OPTION) != JOptionPane.YES_OPTION) {
                    return;
                }
                if (this.regist()) {
                    MessageDialog.showMessageDialog(this,
					MessageUtil.getMessage(MessageUtil.INFO_REGIST_SUCCESS),
					this.getTitle(),
					JOptionPane.INFORMATION_MESSAGE);
                    //入力をクリアする
                    this.clear();
                } else {
                    MessageDialog.showMessageDialog(
                            this,
                            MessageUtil.getMessage(MessageUtil.ERROR_REGIST_FAILED, "一括処理"),
                            this.getTitle(),
                            JOptionPane.ERROR_MESSAGE);
                }
            }
	}//GEN-LAST:event_batchButtonActionPerformed

	private void btnOutputExcelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOutputExcelActionPerformed
	{//GEN-HEADEREND:event_btnOutputExcelActionPerformed
            btnOutputExcel.setCursor(null);
            try {
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                this.exportExcel();
            } finally {
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
	}//GEN-LAST:event_btnOutputExcelActionPerformed

	private void extractionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_extractionButtonActionPerformed
	{//GEN-HEADEREND:event_extractionButtonActionPerformed
            if (this.checkInputSearch()) {
                this.setData(this.batch);
                this.refresh();
                int index = dataMemberTable.getRowCount();
                this.changeButtonEnabled(0 < index);
                if(dataMemberTable.getRowCount() == 0) {
                    MessageDialog.showMessageDialog(this,
                                MessageUtil.getMessage(1112),
                                this.getTitle(),
                                JOptionPane.ERROR_MESSAGE);
        }
            }
	}//GEN-LAST:event_extractionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TargetMonthLabel;
    private javax.swing.JButton batchButton;
    private javax.swing.JButton btnOutputExcel;
    private javax.swing.JCheckBox checkProcessed;
    private javax.swing.JCheckBox checkUntreated;
    private javax.swing.JComboBox cmbMonth;
    private javax.swing.JComboBox cmbPayment;
    private com.geobeck.sosia.pos.swing.JComboBoxLabel cmbShop;
    private javax.swing.JComboBox cmbStaff;
    private javax.swing.JComboBox cmbYear;
    private javax.swing.JTable dataMemberTable;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JButton extractionButton;
    private javax.swing.JLabel monthLable;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.ButtonGroup praiseTimeLimitGroup;
    private jp.co.flatsoft.fscomponent.FSCalenderCombo processDate;
    private javax.swing.JLabel shopLabel;
    private javax.swing.JLabel staffLable;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JScrollPane technicsScrollPane;
    private javax.swing.JLabel yeaLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * 一括処理画面用FocusTraversalPolicy
     */
    private DataBatchFocusTraversalPolicy ftp
            = new DataBatchFocusTraversalPolicy();

    /**
     * 一括処理画面用FocusTraversalPolicyを取得する。
     *
     * @return 一括処理画面用FocusTraversalPolicy
     */
    public DataBatchFocusTraversalPolicy getFocusTraversalPolicy() {
        return ftp;
    }

    /**
     * ボタンにマウスカーソルが乗ったときにカーソルを変更するイベントを追加する。
     */
    private void addMouseCursorChange() {
        SystemInfo.addMouseCursorChange(extractionButton);
        SystemInfo.addMouseCursorChange(btnOutputExcel);
        SystemInfo.addMouseCursorChange(batchButton);

    }

    /**
     * コンポーネントの各リスナーをセットする。
     */
    private void setListener() {
        cmbShop.addKeyListener(SystemInfo.getMoveNextField());
        cmbYear.addKeyListener(SystemInfo.getMoveNextField());
        cmbMonth.addKeyListener(SystemInfo.getMoveNextField());
        cmbPayment.addKeyListener(SystemInfo.getMoveNextField());
        processDate.addKeyListener(SystemInfo.getMoveNextField());
        processDate.addFocusListener(SystemInfo.getSelectText());
        cmbStaff.addKeyListener(SystemInfo.getMoveNextField());
        cmbStaff.addFocusListener(SystemInfo.getSelectText());
    }

    /**
     * 初期化処理を行う。
     */
    private void init() {
        try {
            ConnectionWrapper con = SystemInfo.getConnection();

            mp.loadClasses(con);
            
            this.prefixPaymentMethodName();

            con.close();

            this.cmbPayment.addItem(new MstPaymentMethod());
            // 売掛金追加
            MstPaymentMethod mstpm = new MstPaymentMethod() ;
            mstpm.setPaymentMethodID(CODE_ACCOUNTS_RECEIVABLE);
            mstpm.setPaymentMethodName(NAME_ACCOUNTS_RECEIVABLE);
            this.cmbPayment.addItem(mstpm);
            for (MstPaymentClass paymentClass : mp) {
                for (MstPaymentMethod paymentMethod : paymentClass) {
                    this.cmbPayment.addItem(paymentMethod);
                }
            }
        } catch (SQLException e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        }
        this.initYearComboBox();
        processDate.setDate((java.util.Date) null);
        this.initStaff();
    }
    
    /**
     * set prefix payment method class
     */
    private void prefixPaymentMethodName() {
        for(MstPaymentClass methodClass : mp) {
            if(methodClass.size() > 1) {
                for (MstPaymentMethod method : methodClass) {
                    method.setPaymentMethodName(methodClass.getPaymentClassName() + "）" + method.getPaymentMethodName());
                }
            }
        }
    }
    
    /**
     * レジ担当者を初期化する。
     */
    private void initStaff() {
        cmbStaff.removeAllItems();

        staffs = new MstStaffs();
        staffs.setShopIDList(SystemInfo.getCurrentShop().getShopID().toString());

        try {

            staffs.load(SystemInfo.getConnection(), true);

        } catch (SQLException e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        }
        for (MstStaff ms : staffs) {
            cmbStaff.addItem(ms);
        }

        cmbStaff.setSelectedIndex(0);
    }

    /**
     * 再表示を行う。
     */
    private void refresh() {
        try {
            this.dataBatch.clear();
            ConnectionWrapper con = SystemInfo.getConnection();
            this.dataBatch = this.batch.load(con);
        } catch (Exception e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        }

        //テーブルに商品マスタデータを表示する
        this.showData();

        cmbShop.requestFocusInWindow();

    }

    /**
     * 入力項目をクリアする。
     */
    private void clear() {
        
        SwingUtil.clearTable(dataMemberTable);
        this.uncheckHeader();
        int index = dataMemberTable.getRowCount();

        if (0 < dataMemberTable.getRowCount()) {
            dataMemberTable.removeRowSelectionInterval(0, dataMemberTable.getRowCount() - 1);
        }
        this.cmbShop.setSelectedIndex(0);
        this.cmbYear.setSelectedIndex(0);
        this.cmbMonth.setSelectedIndex(0);
        this.cmbStaff.setSelectedIndex(0);
        this.cmbPayment.setSelectedIndex(0);
        processDate.setDate((java.util.Date) null);
        this.checkProcessed.setSelected(Boolean.FALSE);
        this.checkUntreated.setSelected(Boolean.FALSE);
        
        this.changeButtonEnabled(0 < index);
    }
    
    /**
     * ボタンのEnabledを変更する。
     *
     * @param enabled Enabled
     */
    private void changeButtonEnabled(boolean enabled) {
        batchButton.setEnabled(enabled);
        btnOutputExcel.setEnabled(enabled);
    }
    
    /**
     * uncheck checkbox header
     */
    private void uncheckHeader() {
        if(dataMemberTable.getColumnModel().getColumn(this.COL_CHECK).getHeaderRenderer() instanceof BevelBorderHeaderRenderer) {
            ((BevelBorderHeaderRenderer)dataMemberTable.getColumnModel().getColumn(this.COL_CHECK).getHeaderRenderer()).check.setSelected(Boolean.FALSE);
        }
    }

    /**
     * データを表示する。
     */
    private void showData() {
        SwingUtil.clearTable(dataMemberTable);
        this.uncheckHeader();
        DefaultTableModel model = (DefaultTableModel) dataMemberTable.getModel();

        for (DataMonthlyBatchLog item : this.dataBatch) {
            for (DataMonthlyBatchDetailLog detail : item) {
                Object[] rowData = {
                    item,
                    getUserSearchButton(detail.getCustomer().getCustomerID()),
                    detail.getCustomer().getCustomerNo(),
                    detail.getCustomer().getFullCustomerName(),
                    (detail.getDataMonthMember().getJoinDate() != null) ? DateUtil.format(detail.getDataMonthMember().getJoinDate(), "yyyy/MM/dd") : "",
                    detail.getDataMonthMember().getmPlan().getPlanName(),
                    detail.getCourse().getPrice(),
                    detail.getCourse().getNum(),
                    (item.getProcessDate() != null) ? DateUtil.format(item.getProcessDate(), "yyyy/MM/dd") : "",
                    item.isProcessed() ? this.checkProcessed.getText() : this.checkUntreated.getText()
                };
                model.addRow(rowData);
            }
        }
        if (dataMemberTable.getCellEditor() != null) {
            dataMemberTable.getCellEditor().stopCellEditing();
        }
    }

    /**
     * 入力チェックを行う。
     *
     * @return 入力エラーがなければtrueを返す。
     */
    private boolean checkInput() {
        //対象月
        if (cmbYear.getSelectedIndex() <= 0) {
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY, "対象月"),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            cmbYear.requestFocusInWindow();
            return false;
        }
        if (cmbMonth.getSelectedIndex() <= 0) {
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY, "対象月"),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            cmbMonth.requestFocusInWindow();
            return false;
        }
        // 処理日
        if (processDate.getDate() == null) {
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY, "処理日"),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            processDate.requestFocusInWindow();
            return false;
        }
        //レジ担当
        if (cmbStaff.getSelectedIndex() <= 0) {
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY, "レジ担当"),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            cmbStaff.requestFocusInWindow();
            return false;
        }
        //支払方法
        if (cmbPayment.getSelectedIndex() <= 0) {
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY, "支払方法"),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            cmbPayment.requestFocusInWindow();
            return false;
        }
        //一覧の?
        boolean isCheck = false;
        for (int row = 0; row < this.dataMemberTable.getRowCount(); row ++) {
            if((((Boolean)this.dataMemberTable.getValueAt(row, this.dataMemberTable.getColumnCount() - 1)) != null
                        && ((Boolean)this.dataMemberTable.getValueAt(row, this.dataMemberTable.getColumnCount() - 1)))) {
                
                isCheck = true;
            }
        }
        if(!isCheck) {
            MessageDialog.showMessageDialog(this,
                "対象処理がありません。",
                this.getTitle(),
                JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
    
    /**
     * 入力チェックを行う。
     *
     * @return 入力エラーがなければtrueを返す。
     */
    private boolean checkInputSearch() {
        //対象月
        if (cmbYear.getSelectedIndex() <= 0) {
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY, "対象月"),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            cmbYear.requestFocusInWindow();
            return false;
        }
        if (cmbMonth.getSelectedIndex() <= 0) {
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(MessageUtil.ERROR_INPUT_EMPTY, "対象月"),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            cmbMonth.requestFocusInWindow();
            return false;
        }

        return true;
    }

    /**
     * 入力されたデータを登録する。
     *
     * @return true - 成功
     */
    private boolean regist() {
        if (!this.checkInput()) {
            return false;
        }
        DataMonthlyBatchLog Regist = new DataMonthlyBatchLog();
        this.setData(Regist);

        if (dataMemberTable.getCellEditor() != null) {
            dataMemberTable.getCellEditor().stopCellEditing();
        }
        
        //コネクションを取得
        ConnectionWrapper con = SystemInfo.getConnection();
        try {
            con.begin();
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            //get valid_date
            GregorianCalendar calDate = new GregorianCalendar();
            if (processDate.getDate() != null) {
                calDate.setTime(processDate.getDate());
            }
            //会計設定マスタクラス
            MstAccountSetting ms = SystemInfo.getAccountSetting();
            ms.load(con);
            ms.setTaxRate(SystemInfo.getTaxRate(SystemInfo.getSystemDate()));

            DataSales dsSales;
            DataSalesDetail dsDetail;
            DataContract dContract;
            DataPayment dp;
            DataPaymentDetail dpd;
            boolean isChecked = false;

            for (int row = 0; row < this.dataMemberTable.getRowCount(); row ++) {
                if((((Boolean)this.dataMemberTable.getValueAt(row, this.dataMemberTable.getColumnCount() - 1)) != null
                        && ((Boolean)this.dataMemberTable.getValueAt(row, this.dataMemberTable.getColumnCount() - 1)))) {
                
                    DataMonthlyBatchLog batchLog = (DataMonthlyBatchLog)this.dataMemberTable.getValueAt(row, 0);
                    for (DataMonthlyBatchDetailLog detail : batchLog) {
                        dsSales = new DataSales();
                        dsDetail = new DataSalesDetail();
                        dContract = new DataContract();
                        dp = new DataPayment();
                        dpd = new DataPaymentDetail();
                        MstShop shopSales = detail.getDataMonthMember().getmShop();

                        dsSales.setShop(shopSales);
                        dsSales.setNewSlipNo(con);
                        dsSales.setSalesDate(Regist.getProcessDate());
                        dsSales.setCustomer(detail.getCustomer());
                        dsSales.setStaff(Regist.getStaff());
                        dsSales.setType(3);

                        Integer contractNo = dContract.loadMaxContractNo(con, dsSales.getShop().getShopID()) + 1;

                        Course course = detail.getCourse();
                        Product p = new Product();
                        p.setProductID(course.getCourseId());
                        dContract = new DataContract();
                        dContract.setContractNo(contractNo);
                        dContract.setShop(dsSales.getShop());
                        dContract.setSlipNo(dsSales.getSlipNo());
                        dContract.setProduct(p);
                        dContract.setProductValue(course.getPrice());
                        dContract.setProductNum(course.getNum());
                        dContract.setContractDetailNo(dContract.loadMaxContractDetailNo(con, dContract.getShop().getShopID(), dContract.getContractNo()) + 1);
                        dContract.setTaxRate(SystemInfo.getTaxRate(Regist.getProcessDate()));
                        if (course.getPraiseTimeLimit() > 0) {
                            calDate = new GregorianCalendar();
                            if (processDate.getDate() != null) {
                                calDate.setTime(processDate.getDate());
                            }
                            calDate.add(Calendar.MONTH, course.getPraiseTimeLimit());
                            calDate.add(Calendar.DAY_OF_MONTH, -1);
                            dContract.setValidDate(calDate.getTime());
                            detail.setValidDate(calDate.getTime());
                        }
                        dContract.setStaff(dsSales.getStaff());
                        //コース契約履歴
                        if (!dContract.registDataContract(con)) {
                            con.rollback();
                            return false;
                        }
                        //伝票ヘッダデータ
                        if (!dsSales.registDataSale(con)) {
                            con.rollback();
                            return false;
                        }

                        dsDetail.setAccountSetting(ms);
                        dsDetail.setSlipNo(dsSales.getSlipNo());
                        dsDetail.setShop(dsSales.getShop());
                        dsDetail.setNewSlipDetailNo(con);
                        dsDetail.setStaff(dsSales.getStaff());
                        // 5 = コース
                        dsDetail.setProductDivision(5);
                        dsDetail.setProductValue(course.getPrice());
                        dsDetail.setProductNum(1);
                        dsDetail.setProduct(p);
                        dsDetail.setTaxRate(SystemInfo.getTaxRate(Regist.getProcessDate()));
                        if (!dsDetail.regist(con)) {
                            con.rollback();
                            return false;
                        }

                        dp.setShop(dsSales.getShop());
                        dp.setSlipNo(dsSales.getSlipNo());
                        dp.setBillValue(0l);
                        // default paymentNo : 0
                        dp.setPaymentNo(0);
                        dp.setPaymentDate(Regist.getProcessDate());
                        dp.setStaff(dsSales.getStaff());

                        //IVS start edit 2020/04/01 口座振替連携
                        MstPaymentMethod paymentMethod = ((MstPaymentMethod)cmbPayment.getSelectedItem());
                        dpd.setPaymentMethod(paymentMethod);
                        dpd.setPaymentValue(course.getPrice());
                        if (paymentMethod.getPaymentMethodName().contains(NAME_ACCOUNTS_RECEIVABLE)) {
                            dp.setBillValue(course.getPrice());
                        } else {
                            dp.add(dpd);
                        }
                        //IVS end edit 2020/04/01 口座振替連携
                        if (!dp.registAll(con)) {
                            con.rollback();
                            return false;
                        }
                        detail.setSlipNO(dsSales.getSlipNo());
                        Regist.add(detail);
                    }
                    isChecked = true;
                }
            }
            if(isChecked) {
                if (!Regist.registAll(con)) {
                    con.rollback();
                    return false;
                }
            }

            //トランザクションコミット
            con.commit();
            con.close();

        } catch (Exception e) {
            try {
                SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
                con.rollback();
                return false;
            } catch (SQLException ex) {
                SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
            }
        } finally {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
        return true;
    }

    /**
     * 一括処理マスタデータからデータをセットする。
     *
     * @param mt 一括処理マスタデータ
     */
    private void setData(DataMonthlyBatchLog batch) {
        if (((MstShop) cmbShop.getSelectedItem()) != null && ((MstShop) cmbShop.getSelectedItem()).getShopID() != null) {
            batch.setShop((MstShop) cmbShop.getSelectedItem());
        } else {
            MstShop shop = new MstShop();
            shop.setShopID(0);
            batch.setShop(shop);
        }
        batch.setTargetMonth(this.setTargetMonth());
        batch.setProcessDate(this.processDate.getDate());
        if (((MstPaymentMethod) this.cmbPayment.getSelectedItem()) != null) {
            batch.setPaymentMethodID(((MstPaymentMethod) this.cmbPayment.getSelectedItem()).getPaymentMethodID());
        }
        batch.setProcessed(checkProcessed.isSelected());
        batch.setUntreated(checkUntreated.isSelected());
        MstStaff staff = new MstStaff();
        if(cmbStaff.getSelectedItem() instanceof MstStaff) {
            staff = (MstStaff)cmbStaff.getSelectedItem();
        }
        batch.setStaff(staff);
  
    }

    /**
     * 対象月
     * @return 
     */
    private java.util.Date setTargetMonth() {
        if (this.cmbYear.getSelectedItem().toString().equals("") || this.cmbMonth.getSelectedItem().toString().equals("")) {
            return null;
        }
        Calendar calendar = new GregorianCalendar(Integer.parseInt(this.cmbYear.getSelectedItem().toString()), (Integer.parseInt(this.cmbMonth.getSelectedItem().toString())-1), 1);

        return calendar.getTime();
    }

    /**
     * EXCEL出力
     */
    private void exportExcel() {
        if (dataMemberTable.getRowCount() == 0) {
            MessageDialog.showMessageDialog(this,
                    MessageUtil.getMessage(4001),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        JExcelApi jx = new JExcelApi("一括処理一覧");
        jx.setTemplateFile("/reports/一括処理一覧.xls");

        // ヘッダ出力
        //店舗名
        jx.setValue(2, 3, (this.batch.getShop() != null && this.batch.getShop().getShopName() != null)? this.batch.getShop().getShopName(): "");
        //対象月
        jx.setValue(2, 4, this.getTargetMonthExcel(this.batch.getTargetMonth()));
        //処理区分
        jx.setValue(5, 3, this.getProcessDivision(this.batch));

        int outRow = 7;

        // 追加行数セット
        jx.insertRow(outRow, dataMemberTable.getRowCount() - 1);

        // データセット
        DefaultTableModel model = (DefaultTableModel) dataMemberTable.getModel();
        for (int row = 0; row < dataMemberTable.getRowCount(); row++) {
            int step = 1;
            for (int col = 0; col < dataMemberTable.getColumnCount(); col++) {
                if (col == this.COL_BUTTON_CUSTOMER || col == this.COL_CHECK) {
                    step--;
                    continue;
                }
                if (col == 0) {
                    jx.setValue(col + step, outRow, model.getValueAt(row, col).toString());
                } else {
                    jx.setValue(col + step, outRow, model.getValueAt(row, col));
                }
            }
            outRow++;
        }

        jx.openWorkbook();
    }
    
    /**
     * 対象月
     * @param targetMonth
     * @return 
     */
    private String getTargetMonthExcel(java.util.Date targetMonth) {
        if(targetMonth == null) {
            return "";
        }
        Calendar cal = GregorianCalendar.getInstance();
        cal.setTime(targetMonth);
        int month = cal.get(Calendar.MONTH) + 1;
        int year = cal.get(Calendar.YEAR);
        return year + yeaLabel.getText() + month + monthLable.getText();
    }
    
    /**
     * 処理区分
     * @param batch
     * @return 
     */
    private String getProcessDivision(DataMonthlyBatchLog batch) {
        String divisonName = "";
        if(batch.isProcessed()) {
            divisonName = this.checkProcessed.getText();
        }
        if(batch.isUntreated()) {
            if(!divisonName.equals("")) {
                divisonName = divisonName + "、" + this.checkUntreated.getText();
            }else {
                divisonName = this.checkUntreated.getText();
            }
        }
        return divisonName;
    }

    /**
     * 対象月
     */
    private void initYearComboBox() {

        this.cmbYear.removeAllItems();
        Calendar cal = Calendar.getInstance();
        int nowYear = cal.get(Calendar.YEAR);
        //年
        this.cmbYear.addItem("");
        //IVS_LVTu start add 2020/12/07 月会員管理追加_初期値を当年として+1年まで表示するように
        this.cmbYear.addItem(String.valueOf(nowYear + 1));
        //IVS_LVTu end add 2020/12/07 月会員管理追加_初期値を当年として+1年まで表示するように
        for (int i = 0; i < 5; i++) {
            this.cmbYear.addItem(String.valueOf(nowYear - i));
        }
        //月
        this.cmbMonth.addItem("");
        for (int mon = 1; mon <= 12; mon++) {
            this.cmbMonth.addItem(String.valueOf(mon));
        }
    }

    /**
     * ユーザ検索ボタンを取得する
     */
    private JButton getUserSearchButton(final Integer customerID) {
        JButton searchButton = new JButton();
        searchButton.setBorderPainted(false);
        searchButton.setContentAreaFilled(false);
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                "/images/" + SystemInfo.getSkinPackage() + "/button/common/customer_off.jpg")));
        searchButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource(
                "/images/" + SystemInfo.getSkinPackage() + "/button/common/customer_on.jpg")));
        searchButton.setSize(48, 25);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MstCustomerPanel mcp = null;

                try {

                    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    mcp = new MstCustomerPanel(customerID, true, true);
                    SwingUtil.openAnchorDialog((JFrame) null, true, mcp, "顧客情報", SwingUtil.ANCHOR_HCENTER | SwingUtil.ANCHOR_VCENTER);

                } finally {
                    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                }

                mcp = null;
            }
        });
        return searchButton;
    }

    /**
     * 一括処理画面用FocusTraversalPolicy
     */
    private class DataBatchFocusTraversalPolicy
            extends FocusTraversalPolicy {

        /**
         * aComponent のあとでフォーカスを受け取る Component を返します。 aContainer は aComponent
         * のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダでなければなりません。
         *
         * @param aContainer aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
         * @param aComponent aContainer のおそらく間接的な子、または aContainer 自体
         * @return aComponent のあとにフォーカスを受け取る Component。適切な Component が見つからない場合は
         * null
         */
        public Component getComponentAfter(Container aContainer,
                Component aComponent) {
            
            if (aComponent.equals(cmbShop)) {
                return cmbYear;
            }else if(aComponent.equals(cmbYear)) {
                return cmbMonth;
            }else if(aComponent.equals(cmbMonth)) {
                return processDate;
            }else if(aComponent.equals(processDate)) {
                return cmbStaff;
            }else if(aComponent.equals(cmbStaff)) {
                return cmbPayment;
            }else if(aComponent.equals(cmbPayment)) {
                return checkUntreated;
            }else if(aComponent.equals(checkUntreated)) {
                return checkProcessed;
            }
            
            return cmbShop;
        }

        /**
         * aComponent の前にフォーカスを受け取る Component を返します。 aContainer は aComponent
         * のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダでなければなりません。
         *
         * @param aContainer aComponent のフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
         * @param aComponent aContainer のおそらく間接的な子、または aContainer 自体
         * @return aComponent の前にフォーカスを受け取る Component。適切な Component が見つからない場合は
         * null
         */
        public Component getComponentBefore(Container aContainer,
                Component aComponent) {
            
            if (aComponent.equals(cmbShop)) {
                return cmbShop;
            }else if(aComponent.equals(cmbYear)) {
                return cmbShop;
            }else if(aComponent.equals(cmbMonth)) {
                return cmbYear;
            }else if(aComponent.equals(processDate)) {
                return cmbMonth;
            }else if(aComponent.equals(cmbStaff)) {
                return processDate;
            }else if(aComponent.equals(cmbPayment)) {
                return cmbStaff;
            }else if(aComponent.equals(checkUntreated)) {
                return cmbPayment;
            }else if(aComponent.equals(checkProcessed)) {
                return checkUntreated;
            }

            return cmbShop;
        }

        /**
         * トラバーサルサイクルの最初の Component を返します。 このメソッドは、順方向のトラバーサルがラップするときに、次にフォーカスする
         * Component を判定するために使用します。
         *
         * @param aContainer 先頭の Component
         * を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
         * @return aContainer のトラバーサルサイクルの先頭の Componet、または適切な Component
         * が見つからない場合は null
         */
        public Component getFirstComponent(Container aContainer) {
            return cmbYear;
        }

        /**
         * トラバーサルサイクルの最後の Component を返します。 このメソッドは、逆方向のトラバーサルがラップするときに、次にフォーカスする
         * Component を判定するために使用します。
         *
         * @param aContainer aContainer - 最後の Component
         * を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
         * @return aContainer のトラバーサルサイクルの最後の Componet、または適切な Component
         * が見つからない場合は null
         */
        public Component getLastComponent(Container aContainer) {
            return checkProcessed;
        }

        /**
         * フォーカスを設定するデフォルトコンポーネントを返します。 aContainer
         * をルートとするフォーカストラバーサルサイクルが新しく開始されたときに、このコンポーネントに最初にフォーカスが設定されます。
         *
         * @param aContainer デフォルトの Component
         * を返すフォーカスサイクルのルートまたはフォーカストラバーサルポリシープロバイダ
         * @return aContainer のトラバーサルサイクルのデフォルトの Componet、または適切な Component
         * が見つからない場合は null
         */
        public Component getDefaultComponent(Container aContainer) {
            return cmbYear;
        }

        /**
         * ウィンドウが最初に表示されたときにフォーカスが設定されるコンポーネントを返します。 show() または setVisible(true)
         * の呼び出しで一度ウィンドウが表示されると、 初期化コンポーネントはそれ以降使用されません。
         * 一度別のウィンドウに移ったフォーカスが再び設定された場合、 または、一度非表示状態になったウィンドウが再び表示された場合は、
         * そのウィンドウの最後にフォーカスが設定されたコンポーネントがフォーカス所有者になります。
         * このメソッドのデフォルト実装ではデフォルトコンポーネントを返します。
         *
         * @param window 初期コンポーネントが返されるウィンドウ
         * @return 最初にウィンドウが表示されるときにフォーカス設定されるコンポーネント。適切なコンポーネントがない場合は null
         */
        public Component getInitialComponent(Window window) {
            return cmbYear;
        }
    }

    /**
     * JTableの列幅を初期化する。
     */
    private void initTableColumnWidth() {
        //列の幅を設定する。
        dataMemberTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        dataMemberTable.getColumnModel().getColumn(1).setPreferredWidth(50);
        dataMemberTable.getColumnModel().getColumn(2).setPreferredWidth(80);
        dataMemberTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        dataMemberTable.getColumnModel().getColumn(4).setPreferredWidth(80);
        dataMemberTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        dataMemberTable.getColumnModel().getColumn(6).setPreferredWidth(80);
        dataMemberTable.getColumnModel().getColumn(7).setPreferredWidth(80);
        dataMemberTable.getColumnModel().getColumn(8).setPreferredWidth(80);
        dataMemberTable.getColumnModel().getColumn(9).setPreferredWidth(80);
        dataMemberTable.getColumnModel().getColumn(10).setPreferredWidth(35);
    }

    /**
     * 列の表示位置を設定するTableCellRenderer
     */
    private class TableCellAlignRenderer extends DefaultTableCellRenderer {

        /**
         * Creates a new instance of ReservationTableCellRenderer
         */
        public TableCellAlignRenderer() {
            super();
        }

        /**
         * テーブルセルレンダリングを返します。
         *
         * @param table JTable
         * @param value セルに割り当てる値
         * @param isSelected セルが選択されている場合は true
         * @param hasFocus フォーカスがある場合は true
         * @param row 行
         * @param column 列
         * @return テーブルセルレンダリング
         */
        public Component getTableCellRendererComponent(JTable table,
                Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value,
                    isSelected, hasFocus, row, column);

            switch (column) {
                case 3:
                case 8:
                    super.setHorizontalAlignment(SwingConstants.CENTER);
                    break;
                default:
                    super.setHorizontalAlignment(SwingConstants.LEFT);
                    break;
            }

            return this;
        }
    }

    /**
     * テーブルヘッダーのレンダラーを取得する
     *
     * @return テーブルヘッダーのレンダラー
     */
    public BevelBorderHeaderRenderer getTableHeaderRenderer(JTableHeader header) {
        BevelBorderHeaderRenderer tableHeaderRenderer = null;
        if (tableHeaderRenderer == null) {
            tableHeaderRenderer = new BevelBorderHeaderRenderer(header);
        }
        return tableHeaderRenderer;
    }

    /**
     * JTableのヘッダの色を変更できるRenderer
     *
     * @author katagiri
     */
    public class BevelBorderHeaderRenderer extends DefaultTableCellRenderer implements TableCellRenderer {

        /**
         * 背景色と、ハイライト部・シャドウ部の色の差
         */
        private static final int DIFFERENCE_OF_COLOR = 50;

        private final JCheckBox check = new JCheckBox();

        /**
         * コンストラクタ
         *
         * @param baseColor 背景色
         */
        public BevelBorderHeaderRenderer(JTableHeader header) {
            super();
            Color baseColor = new Color(204, 204, 204);
            check.setOpaque(false);
            this.setIcon(new CheckBoxIcon(check));
            this.setHorizontalAlignment(SwingConstants.CENTER);
            this.setBackground(baseColor);
            this.setBorder(new BevelBorder(BevelBorder.RAISED,
                    this.createHighlightColor(),
                    this.createShadowColor()));

            header.addMouseListener(new MouseAdapter() {

                @Override
                public void mouseClicked(MouseEvent e) {
                    JTable table = ((JTableHeader) e.getSource()).getTable();
                    TableColumnModel columnModel = table.getColumnModel();
                    int viewColumn = columnModel.getColumnIndexAtX(e.getX());
                    int modelColumn = table.convertColumnIndexToModel(viewColumn);
                    if (modelColumn == COL_CHECK) {
                        check.setSelected(!check.isSelected());
                        TableModel m = table.getModel();
                        Boolean f = check.isSelected();
                        for (int i = 0; i < m.getRowCount(); i++) {
                            m.setValueAt(f, i, modelColumn);
                        }
                        ((JTableHeader) e.getSource()).repaint();
                    }
                }
            });
        }

        /**
         * コンストラクタ
         *
         * @param baseColor 背景色
         * @param highlight ハイライト
         * @param shadow シャドウ
         */
        public BevelBorderHeaderRenderer(Color baseColor, Color highlight, Color shadow) {
            super();
            this.setHorizontalAlignment(SwingConstants.CENTER);
            this.setBackground(baseColor);
            this.setBorder(new BevelBorder(BevelBorder.RAISED,
                    highlight, shadow));
        }

        /**
         *
         * @param table
         * @param value
         * @param isSelected
         * @param hasFocus
         * @param row
         * @param column
         * @return
         */
        public Component getTableCellRendererComponent(JTable table,
                Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
            this.setValue((value == null) ? "" : value.toString());
            return this;
        }

        /**
         * ハイライト色を作る
         *
         * @return
         */
        private Color createHighlightColor() {
            Color baseColor = this.getBackground();
            return new Color(
                    this.reviseValue(baseColor.getRed() + BevelBorderHeaderRenderer.DIFFERENCE_OF_COLOR),
                    this.reviseValue(baseColor.getGreen() + BevelBorderHeaderRenderer.DIFFERENCE_OF_COLOR),
                    this.reviseValue(baseColor.getBlue() + BevelBorderHeaderRenderer.DIFFERENCE_OF_COLOR));
        }

        /**
         * シャドウ色を作る
         *
         * @return
         */
        private Color createShadowColor() {
            Color baseColor = this.getBackground();
            return new Color(
                    this.reviseValue(baseColor.getRed() - BevelBorderHeaderRenderer.DIFFERENCE_OF_COLOR),
                    this.reviseValue(baseColor.getGreen() - BevelBorderHeaderRenderer.DIFFERENCE_OF_COLOR),
                    this.reviseValue(baseColor.getBlue() - BevelBorderHeaderRenderer.DIFFERENCE_OF_COLOR));
        }

        /**
         * 色を指定する数値が範囲外の場合補正する
         *
         * @param value 色を指定する数値
         * @return 補正後の色を指定する数値
         */
        private int reviseValue(int value) {
            if (value < 0) {
                return 0;
            } else if (255 < value) {
                return 255;
            } else {
                return value;
            }
        }

        private class CheckBoxIcon implements Icon {

            private final JCheckBox check;

            public CheckBoxIcon(JCheckBox check) {
                this.check = check;
            }

            @Override
            public int getIconWidth() {
                return check.getPreferredSize().width;
            }

            @Override
            public int getIconHeight() {
                return check.getPreferredSize().height;
            }

            @Override
            public void paintIcon(Component c, Graphics g, int x, int y) {
                SwingUtilities.paintComponent(
                        g, check, (Container) c, x, y, getIconWidth(), getIconHeight());
            }
        }
    }
}
