/*
 * MstAutoMailSettingDetailPanel.java
 *
 * Created on 2011/02/23
 */

package com.geobeck.sosia.pos.hair.basicinfo.product;

import com.geobeck.sosia.pos.hair.customer.MstCustomerPanel;
import com.geobeck.sosia.pos.system.SystemInfo;
import java.sql.*;
import java.util.logging.*;
import com.geobeck.sosia.pos.search.account.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.event.*;
import com.geobeck.sosia.pos.util.MessageUtil;
import com.geobeck.sql.*;
import com.geobeck.swing.*;
import com.geobeck.util.DateUtil;
import java.util.*;
import javax.swing.table.DefaultTableModel;

class RadioButtonRenderer implements TableCellRenderer {
  public Component getTableCellRendererComponent(JTable table, Object value,
                   boolean isSelected, boolean hasFocus, int row, int column) {
    if (value==null) return null;
    return (Component)value;
  }
}
class RadioButtonEditor extends    DefaultCellEditor
                        implements ItemListener {
  private JRadioButton button;

  public RadioButtonEditor(JCheckBox checkBox) {
    super(checkBox);
  }

  public Component getTableCellEditorComponent(JTable table, Object value,
                   boolean isSelected, int row, int column) {
    if (value==null) return null;
    button = (JRadioButton)value;
    button.addItemListener(this);
    return (Component)value;
  }

  public Object getCellEditorValue() {
    button.removeItemListener(this);
    return button;
  }

  public void itemStateChanged(ItemEvent e) {
    super.fireEditingStopped();
  }
}

/**
 *
 * @author  geobeck
 */
public class MstCustomerIntegrationDetailPanel extends com.geobeck.sosia.pos.swing.AbstractImagePanelEx
{
        private boolean name;
        private boolean post;
        private boolean address;
        private boolean tel1;
        private boolean tel2;
        private boolean birthday;
        private boolean chkNotMember;

	public MstCustomerIntegrationDetailPanel(Integer customerId,
                                                    boolean name,
                                                    boolean post,
                                                    boolean address,
                                                    boolean tel1,
                                                    boolean tel2,
                                                    boolean birthday,
                                                    boolean chkNotMember)
	{
            super();

            //チェック条件を保持
            this.name=name;
            this.post=post;
            this.address=address;
            this.tel1=tel1;
            this.tel2=tel2;
            this.birthday=birthday;
            this.chkNotMember=chkNotMember;
            
            initComponents();
            this.addMouseCursorChange();
	    this.setSize(800, 600);
            this.setPath("基本設定 >> 顧客関連");
            this.setTitle("顧客統合(詳細)");

            customer_info.getColumnModel().getColumn(1).setCellRenderer(new MyCellRenderer());



            this.load(customerId);
            this.showData();

	}

        class MyCellRenderer extends DefaultTableCellRenderer{
        public MyCellRenderer(){
            super();
        }

        public Component getTableCellRendererComponent(JTable table,
                                            Object value,boolean isSelected,boolean hasFocus,int row,int column){
            super.getTableCellRendererComponent(table,value,isSelected,hasFocus,row,column);

            //書式を設定、この場合は「左上」
            setHorizontalAlignment(this.LEFT);
            setVerticalAlignment(this.TOP);

            return this;
            }
        }

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateGroup = new javax.swing.ButtonGroup();
        sexGroup = new javax.swing.ButtonGroup();
        visitTypeGroup = new javax.swing.ButtonGroup();
        integrationButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        autoMailScrollPane = new javax.swing.JScrollPane();
        customer_list = new com.geobeck.swing.JTableEx();
        backButton = new javax.swing.JButton();
        autoMailScrollPane1 = new javax.swing.JScrollPane();
        customer_info = new com.geobeck.swing.JTableEx();

        setFocusCycleRoot(true);

        integrationButton.setIcon(SystemInfo.getImageIcon("/button/commodity/cust_integration_off.jpg"));
        integrationButton.setBorderPainted(false);
        integrationButton.setPressedIcon(SystemInfo.getImageIcon("/button/commodity/cust_integration_on.jpg"));
        integrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                integrationButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 12));
        jLabel3.setText("【重複顧客一覧】");

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 12));
        jLabel4.setText("【顧客情報】（左のリストを選択すると表示します）");

        jLabel35.setText("<html>顧客統合を行う場合は、主になる顧客に「主体」のチェックをしてください。<br><br>また、複数顧客が該当の場合は統合したい顧客に「統合」のチェックをしてください。");

        jLabel36.setForeground(java.awt.Color.red);
        jLabel36.setText("<html>顧客統合を行うと、過去の来店履歴が登録され、主体とならない顧客データは<br><br>削除されますので、顧客統合をされる際は十分にご注意ください。");

        autoMailScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        customer_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "顧客情報", "顧客NO", "顧客名", "来店回数", "主体", "統合"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customer_list.setSelectionBackground(new java.awt.Color(255, 205, 130));
        customer_list.setSelectionForeground(new java.awt.Color(0, 0, 0));
        customer_list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        customer_list.getTableHeader().setReorderingAllowed(false);
        SwingUtil.setJTableHeaderRenderer(customer_list, SystemInfo.getTableHeaderRenderer());
        customer_list.setRowHeight(SystemInfo.TABLE_ROW_HEIGHT);
        this.initTableColumnWidth();
        customer_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                customer_listMouseReleased(evt);
            }
        });
        customer_list.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                customer_listPropertyChange(evt);
            }
        });
        customer_list.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customer_listKeyReleased(evt);
            }
        });
        autoMailScrollPane.setViewportView(customer_list);
        customer_list.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        customer_list.getColumnModel().getColumn(0).setHeaderValue("顧客情報");
        customer_list.getColumnModel().getColumn(1).setHeaderValue("顧客NO");
        customer_list.getColumnModel().getColumn(2).setHeaderValue("顧客名");
        customer_list.getColumnModel().getColumn(3).setHeaderValue("来店回数");
        customer_list.getColumnModel().getColumn(4).setHeaderValue("主体");
        customer_list.getColumnModel().getColumn(5).setHeaderValue("統合");
        customer_list.getAccessibleContext().setAccessibleParent(customer_list);

        backButton.setIcon(SystemInfo.getImageIcon("/button/common/back_off.jpg"));
        backButton.setBorderPainted(false);
        backButton.setPressedIcon(SystemInfo.getImageIcon("/button/common/back_on.jpg"));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        autoMailScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        customer_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"顧客NO", null},
                {"氏名", null},
                {"ふりがな", null},
                {"郵便番号", null},
                {"都道府県", null},
                {"市区町村", null},
                {"町域・番地", null},
                {"マンション名等", null},
                {"電話番号", null},
                {"携帯番号", null},
                {"PCメール", null},
                {"携帯メール", null},
                {"生年月日", null},
                {"性別", null},
                {"職業", null},
                {"備考", null}
            },
            new String [] {
                "タイトル 1", "タイトル 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customer_info.setRowHeight(20);
        customer_info.setSelectionBackground(new java.awt.Color(204, 204, 204));
        customer_info.setSelectionForeground(new java.awt.Color(0, 0, 0));
        customer_info.setTableHeader(null);
        customer_list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        customer_list.getTableHeader().setReorderingAllowed(false);
        SwingUtil.setJTableHeaderRenderer(customer_list, SystemInfo.getTableHeaderRenderer());
        customer_list.setRowHeight(SystemInfo.TABLE_ROW_HEIGHT);
        this.initCustomerInfoColumnWidth();
        customer_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                customer_infoMouseReleased(evt);
            }
        });
        customer_info.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                customer_infoPropertyChange(evt);
            }
        });
        customer_info.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customer_infoKeyReleased(evt);
            }
        });
        autoMailScrollPane1.setViewportView(customer_info);
        customer_info.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel36)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 398, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, autoMailScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(layout.createSequentialGroup()
                        .add(82, 82, 82)
                        .add(integrationButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(backButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(37, 37, 37))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(autoMailScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(integrationButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(backButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(autoMailScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 386, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(autoMailScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                .add(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

/**/
        private void customer_listMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_listMouseReleased
            this.changeCurrentData();
}//GEN-LAST:event_customer_listMouseReleased

        private void customer_listKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customer_listKeyReleased
            this.changeCurrentData();
}//GEN-LAST:event_customer_listKeyReleased

        private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
            this.closeWindow();
        }//GEN-LAST:event_backButtonActionPerformed

        private void customer_listPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_customer_listPropertyChange
            // TODO add your handling code here:
            this.changeIntegration();
        }//GEN-LAST:event_customer_listPropertyChange

        private void integrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_integrationButtonActionPerformed
            // TODO add your handling code here:

            //入力チェック
            if (!checkInput())
            {
                return;
            }

            if (MessageDialog.showYesNoDialog(
                    this,
                    "顧客統合を行うと、元に戻すことはできません。\nこのまま実行してもよろしいですか？",
                    this.getTitle(),
                    JOptionPane.WARNING_MESSAGE) == JOptionPane.NO_OPTION)
            {
                return;
            }

            if(this.regist()) {
                MessageDialog.showMessageDialog(
                    this,
                    MessageUtil.getMessage(MessageUtil.INFO_REGIST_SUCCESS),
                    this.getTitle(),
                    JOptionPane.INFORMATION_MESSAGE);
           } else {
                MessageDialog.showMessageDialog(
                    this,
                    MessageUtil.getMessage(MessageUtil.ERROR_REGIST_FAILED,"重複顧客"),
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
           }

           this.closeWindow();
        }//GEN-LAST:event_integrationButtonActionPerformed

        private void customer_infoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_infoMouseReleased
            // TODO add your handling code here:
        }//GEN-LAST:event_customer_infoMouseReleased

        private void customer_infoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_customer_infoPropertyChange
            // TODO add your handling code here:
        }//GEN-LAST:event_customer_infoPropertyChange

        private void customer_infoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customer_infoKeyReleased
            // TODO add your handling code here:
        }//GEN-LAST:event_customer_infoKeyReleased

/**/
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane autoMailScrollPane;
    private javax.swing.JScrollPane autoMailScrollPane1;
    private javax.swing.JButton backButton;
    private com.geobeck.swing.JTableEx customer_info;
    private com.geobeck.swing.JTableEx customer_list;
    private javax.swing.ButtonGroup dateGroup;
    private javax.swing.JButton integrationButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.ButtonGroup sexGroup;
    private javax.swing.ButtonGroup visitTypeGroup;
    // End of variables declaration//GEN-END:variables

   protected SearchCostomer	sa	=	new SearchCostomer();
   protected MstCustomerIntegration customerIntegration = new MstCustomerIntegration();

   /**
    * 顧客検索処理を行う。
    */
    public void load(Integer customerId)
    {
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

                sa.setName(this.name);
                sa.setPost(this.post);
                sa.setAddress(this.address);
                sa.setTel1(this.tel1);
                sa.setTel2(this.tel2);
                sa.setBirthday(this.birthday);
                sa.setChkNotMember(this.chkNotMember);
                
                ConnectionWrapper con = SystemInfo.getConnection();
                sa.loadCustomerDetail(con, customerId);

        } catch(SQLException e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        } finally {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }

   /**
    * 重複顧客一覧を表示する。
    */
    private void showData()
    {
        SwingUtil.clearTable(customer_list);

        DefaultTableModel model = (DefaultTableModel)customer_list.getModel();
        if( customer_list.getCellEditor() != null ) customer_list.getCellEditor().stopCellEditing();
	model.setRowCount(0);

        TableColumn c = customer_list.getColumnModel().getColumn(4);
        c.setCellRenderer(new RadioButtonsRenderer());
        c.setCellEditor(new RadioButtonsEditor(model));


         //customer_list.setDefaultRenderer(Object.class, new MultiLineCellRenderer());
         //customer_list.setRowSelectionAllowed(false);
         //customer_list.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for(CustomerData cd : sa)
	{
            model.addRow(new Object[]{
                getDetailButton(cd),
                cd.getCustomerNo_D(),
                cd,
                cd.getVisitNumber_D(),
                null,
                true
            });

            ary_intergration.add(cd.getCustomerId_D());
        }

    }

   /**
    * 顧客統合登録処理を行う。
    */
    private boolean regist() {
        boolean result = false;
        try {

            ConnectionWrapper	con	=	SystemInfo.getConnection();

            con.begin();

            if(this.registData(con)) {
                con.commit();
                result = true ;
            } else {
                con.rollback();
                result = false;
            }
        } catch(SQLException e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
        }
        return result ;
    }

        /**
     *
     * @param con
     * @return
     */
    private boolean registData(ConnectionWrapper con) {
        try {

            //予約データ(data_reservation)
            if(!customerIntegration.data_reservation_regist(con, ary_intergration, ary_main)) {
                return	false;
            }

            //予約データTEMP(data_reservation_temp)
            if(!customerIntegration.data_reservation_temp_regist(con, ary_intergration, ary_main)) {
                return	false;
            }

            //販売データ(data_sales)
            if(!customerIntegration.data_sales_regist(con, ary_intergration, ary_main)) {
                return	false;
            }

            //顧客マスタ(mst_customer)
            if(!customerIntegration.mst_customer_regist(con, ary_intergration, ary_main)) {
                return	false;
            }

            //ポイント履歴データ(data_point)
            if(!customerIntegration.data_point_regist(con, ary_intergration, ary_main)) {
                return	false;
            }

            //イメージカルテデータ(data_image_karte)
            if(!customerIntegration.data_image_karte_regist(con, ary_intergration, ary_main)) {
                return	false;
            }

            //DM履歴詳細データ(data_dm_history_detail)
            if(!customerIntegration.data_dm_history_detail_regist(con, ary_intergration, ary_main)) {
                return	false;
            }

            //フリー項目ユーザデータ(mst_customer_free_heading)
            if(!customerIntegration.mst_customer_free_heading_regist(con, ary_intergration, ary_main)) {
                return	false;
            }

            // IVS start add 2022/08/05 data_salesなどのcustomer_idの更新対応
            // data_image_handkarte
            if(!customerIntegration.data_image_handkarte_regist(con, ary_intergration, ary_main)) {
                return	false;
            }

            // data_text_karte
            if(!customerIntegration.data_text_karte_regist(con, ary_intergration, ary_main)) {
                return	false;
            }

            // temp_data_technic_karte
            if(!customerIntegration.temp_data_technic_karte_regist(con, ary_intergration, ary_main)) {
                return	false;
            }

            // tmp_data_text_karte
            if(!customerIntegration.tmp_data_text_karte_regist(con, ary_intergration, ary_main)) {
                return	false;
            }
            // IVS end add 2022/08/05 data_salesなどのcustomer_idの更新対応
        } catch(SQLException e) {
            SystemInfo.getLogger().log(Level.SEVERE, e.getLocalizedMessage(), e);
            return	false;
        }

        return true;
    }

        /**
         * ボタンにマウスカーソルが乗ったときにカーソルを変更するイベントを追加する。
         */
        private void addMouseCursorChange() {
            SystemInfo.addMouseCursorChange(backButton);
            SystemInfo.addMouseCursorChange(integrationButton);
        }

        /**
	 * 詳細ボタンを取得する
	 */
	private JButton getDetailButton(final CustomerData ad)
	{
            JButton button = new JButton();
            button.setBorderPainted(false);
            button.setContentAreaFilled(false);

            button.setName("");
            button.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                            "/images/" + SystemInfo.getSkinPackage() + "/button/common/customer_off.jpg")));
            button.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource(
                            "/images/" + SystemInfo.getSkinPackage() + "/button/common/customer_on.jpg")));

            button.setSize(48, 25);
            button.setEnabled(true);

            button.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    MstCustomerPanel mcp = null;

                    try {

                        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                        mcp = new MstCustomerPanel(ad.getCustomerId_D() , false, false, true);
                        SwingUtil.openAnchorDialog( null, true, mcp, "顧客情報", SwingUtil.ANCHOR_HCENTER|SwingUtil.ANCHOR_VCENTER );

                    } finally {
                        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    }

                    ((JDialog)mcp.getParent().getParent().getParent().getParent()).dispose();
                }
            });
            return button;
	}

	/**
	 * 入力チェックを行う。
	 * @return 入力エラーがなければtrueを返す。
	 */
	private boolean checkInput()
	{
            if (ary_main.size()==0)
            {
                MessageDialog.showMessageDialog(this,
                            MessageUtil.getMessage(6004),
                            this.getTitle(),
                            JOptionPane.ERROR_MESSAGE);
                return false;
            }

            if (ary_intergration.size()<2)
            {
                MessageDialog.showMessageDialog(this,
                            MessageUtil.getMessage(6005),
                            this.getTitle(),
                            JOptionPane.ERROR_MESSAGE);
                return false;
            }

            if (ary_intergration.indexOf(ary_main.get(0)) == -1)
            {
                MessageDialog.showMessageDialog(this,
                            MessageUtil.getMessage(6006),
                            this.getTitle(),
                            JOptionPane.ERROR_MESSAGE);
                return false;
            }

            return true;
	}

        private ArrayList<Integer> ary_intergration = new ArrayList<Integer>();
        private ArrayList<Integer> ary_main = new ArrayList<Integer>();
        private void changeIntegration() {
            //int		index		=	category.getSelectedIndex();
            //JTable	table	=	customer_info;
            int	row	=	customer_list.getSelectedRow();
            int	col	=	customer_list.getSelectedColumn();

            if(row < 0 || col < 1)	return;

            Boolean	customerlist;
            int curRow = 0;

                for(CustomerData cd : sa)
                {
                   if (curRow==row)
                   {
                       if (col==5)  //統合
                       {
                           customerlist = (Boolean)customer_list.getValueAt(row, col);
                           if (customerlist==true)
                           {
                                if(!ary_intergration.contains(cd.getCustomerId_D()))
                                {
                                    ary_intergration.add(cd.getCustomerId_D());
                                }
                           }
                           else
                           {
                               if(ary_intergration.contains(cd.getCustomerId_D()))
                               {
                                    ary_intergration.remove(ary_intergration.indexOf(cd.getCustomerId_D()));
                               }
                           }
                       }
                       else if (col==4) //主体
                       {
                                ary_main.clear();
                                ary_main.add(cd.getCustomerId_D());
                       }
                    }
                    curRow+=1;
                }      
        }

	/**
	 * JTableの列幅を初期化する。
	 */
	private void initTableColumnWidth()
	{
            //列の幅を設定する。
            
            customer_list.getColumnModel().getColumn(0).setPreferredWidth(30);      //顧客情報
	    customer_list.getColumnModel().getColumn(1).setPreferredWidth(30);      //顧客NO
            customer_list.getColumnModel().getColumn(2).setPreferredWidth(80);      //顧客名
            customer_list.getColumnModel().getColumn(3).setPreferredWidth(25);      //来店回数
            customer_list.getColumnModel().getColumn(4).setPreferredWidth(15);      //主体
            customer_list.getColumnModel().getColumn(5).setPreferredWidth(15);      //統合
	}

        /**
	 * JTableの列幅を初期化する。
	 */
	private void initCustomerInfoColumnWidth()
	{
            //列の幅を設定する。

            customer_info.getColumnModel().getColumn(0).setPreferredWidth(30);
	    customer_info.getColumnModel().getColumn(1).setPreferredWidth(150);
            
            customer_info.setRowHeight(15, 144);

            DefaultTableCellRenderer renderer = new DefaultTableCellRenderer ();
            renderer.setBackground(Color.lightGray);
            customer_info.getColumnModel().getColumn(0).setCellRenderer(renderer);

	}

	/**
	 * ダイアログを閉じる
	 */
	private void closeWindow() {
                if(this.isDialog()) {
                        ((JDialog)this.getParent().getParent().getParent().getParent()).setVisible(false);
                } else {
                        this.setVisible(false);
                }
	}

        private void changeCurrentData() {

	    if (customer_list.getSelectedRow() < 0) return;

            CustomerData ad = (CustomerData)customer_list.getValueAt(customer_list.getSelectedRow(), 2);

            SwingUtil.clearTable(customer_info);

            DefaultTableModel model = (DefaultTableModel)customer_info.getModel();

            for (int row = 0; row < 16; row++) {
                switch (row) {
                    case 0:
                        model.addRow(new Object[]{
                        "顧客NO",
                        ad.getCustomerNo_D()
                        });
                        break;
                    case 1:
                        model.addRow(new Object[]{
                        "氏名",
                        ad.getCustomerName_D()
                        });
                        break;
                    case 2:
                        model.addRow(new Object[]{
                        "ふりがな",
                        ad.getCustomerKana_D()
                        });
                        break;
                    case 3:
                        model.addRow(new Object[]{
                        "郵便番号",
                        ad.getPostalcode_D()
                        });
                        break;
                    case 4:
                        model.addRow(new Object[]{
                        "都道府県",
                        ad.getAddress1_D()
                        });
                        break;
                    case 5:
                        model.addRow(new Object[]{
                        "市区町村",
                        ad.getAddress2_D()
                        });
                        break;
                    case 6:
                        model.addRow(new Object[]{
                        "町域・番地",
                        ad.getAddress3_D()
                        });
                        break;
                    case 7:
                        model.addRow(new Object[]{
                        "マンション名等",
                        ad.getAddress4_D()
                        });
                        break;
                    case 8:
                        model.addRow(new Object[]{
                        "電話番号",
                        ad.getPhoneNumber_D()
                        });
                        break;
                    case 9:
                        model.addRow(new Object[]{
                        "携帯番号",
                        ad.getCellularNumber_D()
                        });
                        break;
                    case 10:
                        model.addRow(new Object[]{
                        "PCメール",
                        ad.getPc_mail_address_D()
                        });
                        break;
                    case 11:
                        model.addRow(new Object[]{
                        "携帯メール",
                        ad.getCellular_mail_address_D()
                        });
                        break;
                    case 12:
                        model.addRow(new Object[]{
                        "生年月日",
                        DateUtil.format(ad.getBirthday_D(), "yyyy/MM/dd")
                        });
                        break;
                    case 13:
                        model.addRow(new Object[]{
                        "性別",
                        ad.getSex_D()
                        });
                        break;
                    case 14:
                        model.addRow(new Object[]{
                        "職業",
                        ad.getJob_D()
                        });
                        break;
                    case 15:
                        String crlf = "\n";
                        String note = ad.getNote_D();
                        if (note != null)
                        {
                            note = note.replace(crlf, "<br>");
                        }
                        else
                        {
                           note = "";
                        }

                        model.addRow(new Object[]{
                        "備考",
                        "<html>"+ note+"</html>+"
                        //ad.getNote_D()
                        });

                        customer_info.setRowHeight(15, 144);
                        break;
                }
            }

        }
}

        class RadioButtonsRenderer extends JRadioButton implements TableCellRenderer {
            public RadioButtonsRenderer() {
                super();
                setName("Table.cellRenderer");
                setHorizontalAlignment(SwingConstants.CENTER);
                setBackground(Color.white);
            }
            @Override public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                if(value instanceof Boolean) {
                    setSelected((Boolean)value);
                }
                return this;
            }
        }
        class RadioButtonsEditor extends JRadioButton implements TableCellEditor {
            public RadioButtonsEditor(final DefaultTableModel model) {
                super();
                setHorizontalAlignment(SwingConstants.CENTER);
                setBackground(Color.white);
                addActionListener(new ActionListener() {
                    @Override public void actionPerformed(ActionEvent e) {
                        fireEditingStopped();
                         for(int i=0; i<model.getRowCount(); i++) {
                             model.setValueAt(i==index, i, 4);
                         }
                    }
                });
            }
            private int index = -1;
            @Override public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
                index = table.convertRowIndexToModel(row);
                if(value instanceof Boolean) {
                    setSelected((Boolean)value);
                }
                return this;
            }
            @Override public Object getCellEditorValue() {
                return isSelected();
            }

            //Copid from AbstractCellEditor
            //protected EventListenerList listenerList = new EventListenerList();
            //transient protected ChangeEvent changeEvent = null;
            @Override public boolean isCellEditable(java.util.EventObject e) {
                return true;
            }
            @Override public boolean shouldSelectCell(java.util.EventObject anEvent) {
                return true;
            }
            @Override public boolean stopCellEditing() {
                fireEditingStopped();
                return true;
            }
            @Override public void  cancelCellEditing() {
                fireEditingCanceled();
            }
            @Override public void addCellEditorListener(CellEditorListener l) {
                listenerList.add(CellEditorListener.class, l);
            }
            @Override public void removeCellEditorListener(CellEditorListener l) {
                listenerList.remove(CellEditorListener.class, l);
            }
            public CellEditorListener[] getCellEditorListeners() {
                return (CellEditorListener[])listenerList.getListeners(CellEditorListener.class);
            }
            protected void fireEditingStopped() {
                // Guaranteed to return a non-null array
                Object[] listeners = listenerList.getListenerList();
                // Process the listeners last to first, notifying
                // those that are interested in this event
                for(int i = listeners.length-2; i>=0; i-=2) {
                    if(listeners[i]==CellEditorListener.class) {
                        // Lazily create the event:
                        if(changeEvent == null) changeEvent = new ChangeEvent(this);
                        ((CellEditorListener)listeners[i+1]).editingStopped(changeEvent);
                    }
                }
            }
            protected void fireEditingCanceled() {
                // Guaranteed to return a non-null array
                Object[] listeners = listenerList.getListenerList();
                // Process the listeners last to first, notifying
                // those that are interested in this event
                for(int i = listeners.length-2; i>=0; i-=2) {
                    if(listeners[i]==CellEditorListener.class) {
                        // Lazily create the event:
                        if(changeEvent == null) changeEvent = new ChangeEvent(this);
                        ((CellEditorListener)listeners[i+1]).editingCanceled(changeEvent);
                    }
                }
            }
        }

